//! Command line interface for the `hc` executable.
//!
//! Port of src/hc/configuration.c: argument parsing and dispatch to the modes
//! run functions (string/hash/file/dir). The yazap command tree mirrors the
//! release argv layout: algorithm is a top-level command, mode is a subcommand
//! (`hc <algorithm> <string|hash|file|dir> [options]`), and each mode owns only
//! its own options. Help is generated by yazap from that tree
//! (`hc -h`, `hc <algo> -h`, `hc <algo> <mode> -h`).

const std = @import("std");
const builtin = @import("builtin");
const yazap = @import("yazap");
const lib = @import("lib");
const hashes = @import("hashes");
const modes = @import("modes");

const build_options = @import("build_options");

const App = yazap.App;
const Arg = yazap.Arg;
const ArgMatches = yazap.ArgMatches;
const Command = yazap.Command;

pub const PROGRAM_NAME = "hc";

pub const opt_source = "source";
pub const opt_hash = "hash";
pub const opt_limit = "limit";
pub const opt_offset = "offset";
pub const opt_threads = "threads";
pub const opt_base64 = "base64";
pub const opt_sfv = "sfv";
pub const opt_noprobe = "noprobe";
pub const opt_noerroronfind = "noerroronfind";
pub const opt_save = "save";
pub const opt_lower = "lower";
pub const opt_time = "time";
pub const opt_checksumfile = "checksumfile";
pub const opt_recursively = "recursively";
pub const opt_performance = "performance";
pub const opt_dict = "dict";
pub const opt_min = "min";
pub const opt_max = "max";
pub const opt_include = "include";
pub const opt_exclude = "exclude";
pub const opt_search = "search";

const STRING_CMD = "string";
const HASH_CMD = "hash";
const FILE_CMD = "file";
const DIR_CMD = "dir";

pub const Mode = enum {
    none,
    string,
    hash,
    file,
    dir,
};

/// Active mode, mirrored from C's `hc_mode_t g_mode`. Published before
/// dispatch so the SIGINT handler in main.zig can decide whether to print
/// brute-force timings.
pub var active_mode: Mode = .none;

pub fn detectMode(cmd: []const u8) Mode {
    if (std.mem.eql(u8, cmd, STRING_CMD)) return .string;
    if (std.mem.eql(u8, cmd, HASH_CMD)) return .hash;
    if (std.mem.eql(u8, cmd, FILE_CMD)) return .file;
    if (std.mem.eql(u8, cmd, DIR_CMD)) return .dir;
    return .none;
}

// --- Number parsing (mirrors prconf_read_offset_parameter / sscanf %lli) ---

pub const NumberError = error{InvalidCharacter};

/// Parses a signed 64-bit number mirroring `sscanf("%lli", ...)`: out of range
/// values clamp to the signed extremum based on their sign rather than erroring.
pub fn parseBigNumber(s: []const u8) NumberError!i64 {
    const trimmed = std.mem.trim(u8, s, &std.ascii.whitespace);
    if (trimmed.len == 0) return error.InvalidCharacter;
    return std.fmt.parseInt(i64, trimmed, 10) catch |err| switch (err) {
        error.Overflow => blk: {
            const negative = trimmed[0] == '-';
            break :blk if (negative) std.math.minInt(i64) else std.math.maxInt(i64);
        },
        error.InvalidCharacter => return error.InvalidCharacter,
    };
}

/// Returns the architecture suffix used in the copyright banner. The C binary
/// hardcodes "x64"; we keep that on x86_64 and extend sensibly elsewhere.
pub fn archSuffix() []const u8 {
    return switch (builtin.cpu.arch) {
        .x86_64 => "x64",
        .aarch64 => "arm64",
        .x86 => "x86",
        else => "native",
    };
}

pub fn productVersion() []const u8 {
    return build_options.version;
}

pub fn appName() []const u8 {
    return "Hash Calculator";
}

/// Prints the copyright banner exactly like hc_print_copyright():
/// "\n<APP_NAME> <version> <arch>\nCopyright ...\n\n"
pub fn printCopyright(out: *std.Io.Writer) !void {
    try out.print(
        "\n{s} {s} {s}\nCopyright (C) 2009-2026 Alexander Egorov. All rights reserved.\n\n",
        .{ appName(), productVersion(), archSuffix() },
    );
}

// --- Threads resolution (mirrors prconf_get_threads_count) ----------------

pub fn resolveThreads(out: *std.Io.Writer, provided: ?[]const u8) i32 {
    const processors: u32 = lib.getProcessorCount();
    const processors_i32: i32 = @intCast(processors);

    var num: i32 = if (provided) |v|
        std.fmt.parseInt(i32, v, 10) catch 0
    else blk: {
        break :blk if (processors == 1) 1 else @intCast(@min(processors, processors / 2));
    };

    if (num < 1 or num > processors_i32) {
        const def: i32 = if (processors == 1) 1 else @intCast(processors / 2);
        out.print(
            "Threads number must be between 1 and {d} but it was set to {d}. Reset to default {d}\n",
            .{ processors, @as(u32, @bitCast(num)), @as(u32, @bitCast(def)) },
        ) catch {};
        num = def;
    }
    return num;
}

/// Reads and validates a limit/offset parameter. Prints the appropriate error
/// (no copyright for non-numeric, copyright + message for negative) and returns
/// false if the caller must abort.
fn readNumberParam(
    out: *std.Io.Writer,
    provided: ?[]const u8,
    option_name: []const u8,
) !bool {
    if (provided) |v| {
        const n = parseBigNumber(v) catch {
            try out.print("Invalid parameter --{s} {s}. Must be number\n", .{ option_name, v });
            return false;
        };
        if (n < 0) {
            try printCopyright(out);
            try out.print("Invalid {s} option must be positive but was {d}\n", .{ option_name, n });
            return false;
        }
    }
    return true;
}

// --- App construction (algorithm commands → mode subcommands) -------------

fn valueOption(
    name: []const u8,
    short_name: u8,
    description: []const u8,
    placeholder: ?[]const u8,
) Arg {
    var a = Arg.singleValueOption(name, short_name, description);
    a.setProperty(.allow_empty_value);
    if (placeholder) |p| a.setValuePlaceholder(p);
    return a;
}

fn valueOptionRequired(
    name: []const u8,
    short_name: u8,
    description: []const u8,
    placeholder: ?[]const u8,
) Arg {
    var a = Arg.singleValueOption(name, short_name, description);
    a.setProperty(.allow_empty_value);
    a.setProperty(.takes_value);
    if (placeholder) |p| a.setValuePlaceholder(p);
    return a;
}

fn addStringSubcommand(app: *App, parent: *Command) !void {
    var cmd = app.createCommand(STRING_CMD, "calculate hash sum of a string");
    cmd.setProperty(.help_on_empty_args);
    try cmd.addArg(valueOptionRequired(opt_source, 's', "string to calculate hash sum for", "string"));
    try cmd.addArg(Arg.booleanOption(opt_base64, 'b', "output hash as Base64"));
    try cmd.addArg(Arg.booleanOption(opt_lower, 'l', "output hash using low case (false by default)"));
    try parent.addSubcommand(cmd);
}

fn addHashSubcommand(app: *App, parent: *Command) !void {
    var cmd = app.createCommand(HASH_CMD, "restore the original string from a hash");
    cmd.setProperty(.help_on_empty_args);
    try cmd.addArg(valueOption(
        opt_source,
        's',
        "hash to restore initial string by. Required unless -p is specified",
        "string",
    ));
    try cmd.addArg(Arg.booleanOption(opt_base64, 'b', "interpret hash as Base64"));
    try cmd.addArg(valueOption(
        opt_dict,
        'a',
        "initial string's dictionary. All digits, upper and lower case latin symbols by default. Specify value ASCII here to use all ASCII charset as dictionary",
        "string",
    ));
    try cmd.addArg(valueOption(opt_min, 'n', "set minimum length of the string to restore. 1 by default", "int"));
    try cmd.addArg(valueOption(opt_max, 'x', "set maximum length of the string to restore. 10 by default", "int"));
    try cmd.addArg(Arg.booleanOption(opt_performance, 'p', "test performance by cracking 12345 string hash"));
    try cmd.addArg(Arg.booleanOption(opt_noprobe, null, "Disable hash crack time probing (how much time it may take)"));
    try cmd.addArg(valueOption(
        opt_threads,
        'T',
        "the number of threads to crack hash. The half of system processors by default. The value must be between 1 and processor count.",
        "int",
    ));
    try cmd.addArg(Arg.booleanOption(opt_lower, 'l', "output hash using low case (false by default)"));
    try parent.addSubcommand(cmd);
}

fn addFileSubcommand(app: *App, parent: *Command) !void {
    var cmd = app.createCommand(FILE_CMD, "calculate hash sum of a file");
    cmd.setProperty(.help_on_empty_args);
    try cmd.addArg(valueOptionRequired(
        opt_source,
        's',
        "full path to file to calculate hash sum of",
        "file",
    ));
    try cmd.addArg(valueOption(opt_hash, 'm', "hash to validate file", "string"));
    try cmd.addArg(valueOption(
        opt_limit,
        'z',
        "set the limit in bytes of the part of the file to calculate hash for. The whole file by default will be applied",
        "number",
    ));
    try cmd.addArg(valueOption(
        opt_offset,
        'q',
        "set start position within file to calculate hash from. Zero by default",
        "number",
    ));
    try cmd.addArg(Arg.booleanOption(opt_checksumfile, 'c', "output hash in file checksum format"));
    try cmd.addArg(valueOption(
        opt_save,
        'o',
        "save files' hashes into the file specified besides console output.",
        "file",
    ));
    try cmd.addArg(Arg.booleanOption(opt_time, 't', "show calculation time (false by default)"));
    try cmd.addArg(Arg.booleanOption(
        opt_sfv,
        null,
        "output hash in the SFV (Simple File Verification) format (false by default). Only for CRC32 or CRC32C.",
    ));
    try cmd.addArg(Arg.booleanOption(opt_lower, 'l', "output hash using low case (false by default)"));
    try cmd.addArg(Arg.booleanOption(opt_base64, 'b', "output hash as Base64"));
    try parent.addSubcommand(cmd);
}

fn addDirSubcommand(app: *App, parent: *Command) !void {
    var cmd = app.createCommand(DIR_CMD, "calculate hash sums of files in a directory");
    cmd.setProperty(.help_on_empty_args);
    try cmd.addArg(valueOptionRequired(
        opt_source,
        's',
        "full path to dir to calculate all content's hashes",
        "string",
    ));
    try cmd.addArg(valueOption(
        opt_hash,
        'm',
        "hash to validate files in directory",
        "string",
    ));
    try cmd.addArg(valueOption(
        opt_exclude,
        'e',
        "exclude files that match the pattern specified. It's possible to use several patterns separated by ;",
        "string",
    ));
    try cmd.addArg(valueOption(
        opt_include,
        'i',
        "include only files that match the pattern specified. It's possible to use several patterns separated by ;",
        "string",
    ));
    try cmd.addArg(valueOption(
        opt_limit,
        'z',
        "set the limit in bytes of the part of the file to calculate hash for. The whole file by default will be applied",
        "number",
    ));
    try cmd.addArg(valueOption(
        opt_offset,
        'q',
        "set start position within file to calculate hash from. Zero by default",
        "number",
    ));
    try cmd.addArg(valueOption(opt_search, 'H', "hash to search a file that matches it", "string"));
    try cmd.addArg(Arg.booleanOption(opt_recursively, 'r', "scan directory recursively"));
    try cmd.addArg(Arg.booleanOption(opt_checksumfile, 'c', "output hash in file checksum format"));
    try cmd.addArg(valueOption(
        opt_save,
        'o',
        "save files' hashes into the file specified besides console output.",
        "file",
    ));
    try cmd.addArg(Arg.booleanOption(opt_time, 't', "show calculation time (false by default)"));
    try cmd.addArg(Arg.booleanOption(
        opt_sfv,
        null,
        "output hash in the SFV (Simple File Verification) format (false by default). Only for CRC32 or CRC32C.",
    ));
    try cmd.addArg(Arg.booleanOption(opt_lower, 'l', "output hash using low case (false by default)"));
    try cmd.addArg(Arg.booleanOption(opt_base64, 'b', "output hash as Base64"));
    try cmd.addArg(Arg.booleanOption(
        opt_noerroronfind,
        null,
        "Disable error output while search files. False by default.",
    ));
    try parent.addSubcommand(cmd);
}

fn addAlgorithmCommand(app: *App, root: *Command, name: []const u8) !void {
    var algo = app.createCommand(name, null);
    algo.setProperty(.help_on_empty_args);
    algo.setProperty(.subcommand_required);
    try addStringSubcommand(app, &algo);
    try addHashSubcommand(app, &algo);
    try addFileSubcommand(app, &algo);
    try addDirSubcommand(app, &algo);
    try root.addSubcommand(algo);
}

fn createApp(allocator: std.mem.Allocator) !*App {
    const app = try allocator.create(App);
    errdefer allocator.destroy(app);

    const descr = try std.fmt.allocPrint(
        allocator,
        "{s} {s} {s}\nCopyright (C) 2009-2026 Alexander Egorov. All rights reserved.",
        .{ appName(), productVersion(), archSuffix() },
    );
    app.* = App.init(allocator, PROGRAM_NAME, descr);

    var root = app.rootCommand();
    root.setProperty(.help_on_empty_args);
    root.setProperty(.subcommand_required);

    for (hashes.hashes) |h| {
        try addAlgorithmCommand(app, root, h.name);
    }

    return app;
}

/// Short names of options that take a value.
const value_option_short = [_]u8{ 's', 'm', 'z', 'q', 'T', 'o', 'a', 'n', 'x', 'i', 'e', 'H' };

/// Long names of options that take a value.
const value_option_long = [_][]const u8{
    "source", "hash", "limit", "offset",  "threads", "save",
    "dict",   "min",  "max",   "include", "exclude", "search",
};

/// Short names of options that take a numeric value (limit/offset/min/max/threads).
const numeric_option_short = [_]u8{ 'z', 'q', 'n', 'x', 'T' };

/// Long names of options that take a numeric value.
const numeric_option_long = [_][]const u8{ "limit", "offset", "min", "max", "threads" };

/// True when `tok` is a bare value-expecting option token with no attached
/// value (e.g. `-s` or `--source` but not `-s=x` or `-sx`).
pub fn isBareValueOption(tok: []const u8) bool {
    if (tok.len == 2 and tok[0] == '-') {
        for (value_option_short) |c| if (tok[1] == c) return true;
        return false;
    }
    if (std.mem.startsWith(u8, tok, "--") and std.mem.indexOfScalar(u8, tok, '=') == null) {
        const name = tok[2..];
        for (value_option_long) |n| if (std.mem.eql(u8, name, n)) return true;
        return false;
    }
    return false;
}

/// True when `tok` is a bare numeric-value option (limit/offset/min/max/threads).
pub fn isNumericValueOption(tok: []const u8) bool {
    if (tok.len == 2 and tok[0] == '-') {
        for (numeric_option_short) |c| if (tok[1] == c) return true;
        return false;
    }
    if (std.mem.startsWith(u8, tok, "--") and std.mem.indexOfScalar(u8, tok, '=') == null) {
        const name = tok[2..];
        for (numeric_option_long) |n| if (std.mem.eql(u8, name, n)) return true;
        return false;
    }
    return false;
}

/// True when `tok` is a negative decimal integer (e.g. "-10"). Tokens that
/// look like options ("--limit", "-l") are rejected.
pub fn isNegativeNumber(tok: []const u8) bool {
    if (tok.len < 2 or tok[0] != '-') return false;
    for (tok[1..]) |c| if (c < '0' or c > '9') return false;
    return true;
}

/// yazap's tokenizer skips empty argv elements and treats `-10` as a short
/// option group, so a value passed as a separate token is lost in two cases:
///   * `-s ""`   -> empty value (argtable3 accepts it; C# EmptyStringHash)
///   * `-z -10`  -> negative numeric value (C# InvalidNumbericOptionsNegativeTest)
/// This rewrites such a bare value-option followed by the problematic token
/// into the attached form (`-s=` / `-z=-10`), which yazap captures. Mirrors
/// argtable3, which consumes the next token as a string regardless of `-`.
fn shouldAttach(opt_tok: []const u8, next_tok: []const u8) bool {
    if (!isBareValueOption(opt_tok)) return false;
    if (next_tok.len == 0) return true;
    if (isNumericValueOption(opt_tok) and isNegativeNumber(next_tok)) return true;
    return false;
}

fn attachValue(
    allocator: std.mem.Allocator,
    opt_tok: []const u8,
    val_tok: []const u8,
) ![:0]const u8 {
    const buf = try allocator.allocSentinel(u8, opt_tok.len + 1 + val_tok.len, 0);
    @memcpy(buf[0..opt_tok.len], opt_tok);
    buf[opt_tok.len] = '=';
    @memcpy(buf[opt_tok.len + 1 ..][0..val_tok.len], val_tok);
    return buf;
}

/// Rewrites argv so empty and negative-numeric option values are attached to
/// their option (see `shouldAttach`). Returns the original slice unchanged when
/// no rewrite is needed.
pub fn normalizeArgv(
    allocator: std.mem.Allocator,
    argv: []const [:0]const u8,
) ![]const [:0]const u8 {
    var merged: usize = 0;
    {
        var i: usize = 0;
        while (i < argv.len) {
            if (i + 1 < argv.len and shouldAttach(argv[i], argv[i + 1])) {
                merged += 1;
                i += 2;
            } else i += 1;
        }
    }
    if (merged == 0) return argv;

    const out = try allocator.alloc([:0]const u8, argv.len - merged);
    errdefer allocator.free(out);

    var oi: usize = 0;
    var i: usize = 0;
    while (i < argv.len) {
        if (i + 1 < argv.len and shouldAttach(argv[i], argv[i + 1])) {
            out[oi] = try attachValue(allocator, argv[i], argv[i + 1]);
            oi += 1;
            i += 2;
        } else {
            out[oi] = argv[i];
            oi += 1;
            i += 1;
        }
    }
    return out;
}

// --- Dispatch helpers ------------------------------------------------------

fn runString(
    matches: ArgMatches,
    bctx: *const modes.BuiltinCtx,
    env: modes.RunEnv,
) !void {
    const source = matches.getSingleValue(opt_source) orelse {
        try env.out.print("--{s} option is required\n", .{opt_source});
        return;
    };
    var sctx: modes.StringCtx = .{
        .builtin = bctx,
        .string = source,
        .is_base64 = matches.containsArg(opt_base64),
    };
    try modes.builtinRun(modes.StringCtx, bctx, &sctx, modes.strRun, env);
}

fn runHash(
    matches: ArgMatches,
    bctx: *const modes.BuiltinCtx,
    env: modes.RunEnv,
    app: *App,
    io: std.Io,
) !void {
    const performance = matches.containsArg(opt_performance);
    const source = matches.getSingleValue(opt_source);
    if (!performance and (source == null or source.?.len == 0)) {
        try env.out.print(
            "--{s} option is required to restore hash. Use -p to run performance test without it\n",
            .{opt_source},
        );
        // Flush our buffered stdout before yazap writes help via OS stdout.
        try env.out.flush();
        const help_out = try YazapStdoutRedirect.begin();
        defer help_out.restore();
        try app.displaySubcommandHelp(io);
        return;
    }

    const threads = resolveThreads(env.out, matches.getSingleValue(opt_threads));

    var hctx: modes.HashCtx = .{
        .builtin = bctx,
        .hash = source,
        .is_base64 = matches.containsArg(opt_base64),
        .no_probe = matches.containsArg(opt_noprobe),
        .performance = performance,
        .threads = threads,
    };
    if (matches.getSingleValue(opt_dict)) |d| hctx.dictionary = d;
    if (matches.getSingleValue(opt_min)) |m| hctx.min = std.fmt.parseInt(i32, m, 10) catch 0;
    if (matches.getSingleValue(opt_max)) |m| hctx.max = std.fmt.parseInt(i32, m, 10) catch 0;

    try modes.builtinRun(modes.HashCtx, bctx, &hctx, modes.hashRun, env);
}

fn runFile(
    matches: ArgMatches,
    bctx: *const modes.BuiltinCtx,
    env: modes.RunEnv,
) !void {
    if (!try readNumberParam(env.out, matches.getSingleValue(opt_limit), opt_limit)) return;
    if (!try readNumberParam(env.out, matches.getSingleValue(opt_offset), opt_offset)) return;

    const file_path = matches.getSingleValue(opt_source) orelse {
        try env.out.print("--{s} option is required\n", .{opt_source});
        return;
    };

    const limit_value: i64 = if (matches.getSingleValue(opt_limit)) |v| (parseBigNumber(v) catch 0) else std.math.maxInt(i64);
    const offset_value: i64 = if (matches.getSingleValue(opt_offset)) |v| (parseBigNumber(v) catch 0) else 0;

    var fctx: modes.FileCtx = .{
        .builtin = bctx,
        .file_path = file_path,
        .limit = limit_value,
        .offset = offset_value,
        .show_time = matches.containsArg(opt_time),
        .is_verify = matches.containsArg(opt_checksumfile),
        .result_in_sfv = matches.containsArg(opt_sfv),
        .is_base64 = matches.containsArg(opt_base64),
    };
    if (matches.getSingleValue(opt_hash)) |h| fctx.hash = h;
    if (matches.getSingleValue(opt_save)) |s| fctx.save_result_path = s;

    try modes.builtinRun(modes.FileCtx, bctx, &fctx, modes.fileRun, env);
}

fn runDir(
    matches: ArgMatches,
    bctx: *const modes.BuiltinCtx,
    env: modes.RunEnv,
) !void {
    if (!try readNumberParam(env.out, matches.getSingleValue(opt_limit), opt_limit)) return;
    if (!try readNumberParam(env.out, matches.getSingleValue(opt_offset), opt_offset)) return;

    const dir_path = matches.getSingleValue(opt_source) orelse {
        try env.out.print("--{s} option is required\n", .{opt_source});
        return;
    };

    const limit_value: i64 = if (matches.getSingleValue(opt_limit)) |v| (parseBigNumber(v) catch 0) else std.math.maxInt(i64);
    const offset_value: i64 = if (matches.getSingleValue(opt_offset)) |v| (parseBigNumber(v) catch 0) else 0;

    var dctx: modes.DirCtx = .{
        .builtin = bctx,
        .dir_path = dir_path,
        .limit = limit_value,
        .offset = offset_value,
        .show_time = matches.containsArg(opt_time),
        .is_verify = matches.containsArg(opt_checksumfile),
        .result_in_sfv = matches.containsArg(opt_sfv),
        .recursively = matches.containsArg(opt_recursively),
        .no_error_on_find = matches.containsArg(opt_noerroronfind),
        .is_base64 = matches.containsArg(opt_base64),
    };
    if (matches.getSingleValue(opt_hash)) |h| dctx.hash = h;
    if (matches.getSingleValue(opt_search)) |s| dctx.search_hash = s;
    if (matches.getSingleValue(opt_include)) |i| dctx.include_pattern = i;
    if (matches.getSingleValue(opt_exclude)) |e| dctx.exclude_pattern = e;
    if (matches.getSingleValue(opt_save)) |s| dctx.save_result_path = s;

    try modes.builtinRun(modes.DirCtx, bctx, &dctx, modes.dirRun, env);
}

fn knownAlgorithm(name: []const u8) bool {
    return hashes.getHash(name) != null;
}

/// Yazap hardcodes help and parse diagnostics to stderr; the release binary
/// wrote the same text to stdout. Point stderr at stdout for the duration of
/// yazap I/O so pipes (`hc -h | less`) and scripts see release-compatible
/// output. On Windows Zig's `File.stderr()` reads the PEB handle, so the
/// redirect mutates that; elsewhere `dup2` remaps fd 2.
const YazapStdoutRedirect = struct {
    saved: if (builtin.os.tag == .windows) std.os.windows.HANDLE else std.posix.fd_t,

    fn begin() !YazapStdoutRedirect {
        if (builtin.os.tag == .windows) {
            const params = std.os.windows.peb().ProcessParameters;
            const saved = params.hStdError;
            params.hStdError = params.hStdOutput;
            return .{ .saved = saved };
        } else {
            const saved = std.c.dup(std.posix.STDERR_FILENO);
            if (saved < 0) return error.Unexpected;
            if (std.c.dup2(std.posix.STDOUT_FILENO, std.posix.STDERR_FILENO) < 0) {
                _ = std.c.close(saved);
                return error.Unexpected;
            }
            return .{ .saved = saved };
        }
    }

    fn restore(self: YazapStdoutRedirect) void {
        if (builtin.os.tag == .windows) {
            std.os.windows.peb().ProcessParameters.hStdError = self.saved;
        } else {
            _ = std.c.dup2(self.saved, std.posix.STDERR_FILENO);
            _ = std.c.close(self.saved);
        }
    }
};

// --- Entry point -----------------------------------------------------------

pub const Outcome = enum { ok, invalid_command, invalid_options };

/// Parses argv and dispatches to the matching mode. Mirrors conf_run_app().
/// Returns the outcome so the caller can map it to a process exit code.
pub fn run(
    allocator: std.mem.Allocator,
    io: std.Io,
    out: *std.Io.Writer,
    argv: []const [:0]const u8,
) !Outcome {
    const app = try createApp(allocator);
    defer {
        app.deinit();
        allocator.destroy(app);
    }

    // Rewrite `-s ""` (empty value) and `-z -10` (negative numeric value)
    // into attached form so yazap captures them (it otherwise skips empty
    // argv elements and treats `-10` as a short option group).
    const argv_norm = try normalizeArgv(allocator, argv);

    // Empty argv / -h/--help: yazap prints structured help from the command
    // tree (algorithms → modes → options) and exits. Nested helps
    // (`hc md5 -h`, `hc md5 string -h`) use the same path. Diagnostics are
    // redirected to stdout for release parity (see YazapStdoutRedirect).
    const matches = blk: {
        const yazap_out = try YazapStdoutRedirect.begin();
        defer yazap_out.restore();
        break :blk app.parseFrom(io, argv_norm) catch |err| switch (err) {
            error.UnrecognizedCommand => {
                // Yazap already printed "unrecognized command …" to stdout.
                return if (argv_norm.len > 0 and knownAlgorithm(argv_norm[0]))
                    .invalid_command
                else
                    .invalid_options;
            },
            error.SubcommandNotProvided => return .invalid_command,
            error.UnrecognizedOption,
            error.OptionValueNotProvided,
            error.UnexpectedOptionValue,
            error.EmptyOptionValue,
            error.InvalidOptionValue,
            error.TooFewOptionValue,
            error.TooManyOptionValue,
            error.PositionalArgumentNotProvided,
            => return .invalid_options,
            else => return err,
        };
    };

    var algorithm: ?[]const u8 = null;
    var mode_matches: ?ArgMatches = null;
    var mode: Mode = .none;

    for (hashes.hashes) |h| {
        const algo_m = matches.subcommandMatches(h.name) orelse continue;
        algorithm = h.name;
        inline for (.{ STRING_CMD, HASH_CMD, FILE_CMD, DIR_CMD }) |mode_name| {
            if (algo_m.subcommandMatches(mode_name)) |mm| {
                mode_matches = mm;
                mode = detectMode(mode_name);
                break;
            }
        }
        break;
    }

    if (algorithm == null or mode == .none or mode_matches == null) {
        return .invalid_command;
    }

    const bctx: modes.BuiltinCtx = .{
        .hash_algorithm = algorithm.?,
        .is_print_low_case = mode_matches.?.containsArg(opt_lower),
    };

    const env: modes.RunEnv = .{
        .io = io,
        .allocator = allocator,
        .out = out,
    };

    active_mode = mode;

    switch (mode) {
        .string => try runString(mode_matches.?, &bctx, env),
        .hash => try runHash(mode_matches.?, &bctx, env, app, io),
        .file => try runFile(mode_matches.?, &bctx, env),
        .dir => try runDir(mode_matches.?, &bctx, env),
        .none => unreachable,
    }

    return .ok;
}

// Tests

test "detectMode maps commands" {
    try std.testing.expectEqual(Mode.string, detectMode("string"));
    try std.testing.expectEqual(Mode.hash, detectMode("hash"));
    try std.testing.expectEqual(Mode.file, detectMode("file"));
    try std.testing.expectEqual(Mode.dir, detectMode("dir"));
    try std.testing.expectEqual(Mode.none, detectMode("bogus"));
}

test "parseBigNumber valid values" {
    try std.testing.expectEqual(@as(i64, 0), try parseBigNumber("0"));
    try std.testing.expectEqual(@as(i64, 42), try parseBigNumber("42"));
    try std.testing.expectEqual(@as(i64, -10), try parseBigNumber("-10"));
    try std.testing.expectEqual(@as(i64, 1024), try parseBigNumber(" 1024 "));
}

test "parseBigNumber clamps overflow to signed extremum" {
    try std.testing.expectEqual(std.math.maxInt(i64), try parseBigNumber("18446744073709551615"));
    try std.testing.expectEqual(std.math.minInt(i64), try parseBigNumber("-10223372036854775808"));
}

test "parseBigNumber rejects non-numeric" {
    try std.testing.expectError(error.InvalidCharacter, parseBigNumber("a"));
    try std.testing.expectError(error.InvalidCharacter, parseBigNumber(""));
}

test "isNegativeNumber distinguishes values from options" {
    try std.testing.expect(isNegativeNumber("-10"));
    try std.testing.expect(isNegativeNumber("-10223372036854775808"));
    try std.testing.expect(!isNegativeNumber("10"));
    try std.testing.expect(!isNegativeNumber("--limit"));
    try std.testing.expect(!isNegativeNumber("-l"));
    try std.testing.expect(!isNegativeNumber("-"));
}

test "normalizeArgv attaches empty and negative values" {
    const allocator = std.testing.allocator;
    {
        const argv = [_][:0]const u8{ "-s", "" };
        const out = try normalizeArgv(allocator, &argv);
        defer if (out.ptr != argv.ptr) allocator.free(out);
        try std.testing.expectEqual(@as(usize, 1), out.len);
        try std.testing.expectEqualStrings("-s=", out[0]);
    }
    {
        const argv = [_][:0]const u8{ "-z", "-10" };
        const out = try normalizeArgv(allocator, &argv);
        defer if (out.ptr != argv.ptr) allocator.free(out);
        try std.testing.expectEqual(@as(usize, 1), out.len);
        try std.testing.expectEqualStrings("-z=-10", out[0]);
    }
    {
        // Positive numbers and normal tokens are untouched.
        const argv = [_][:0]const u8{ "-z", "10", "-s", "abc" };
        const out = try normalizeArgv(allocator, &argv);
        try std.testing.expect(out.ptr == argv.ptr);
    }
}

test "string mode dispatch produces hash output" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var writer = std.Io.Writer.Allocating.init(arena.allocator());
    const out = &writer.writer;

    const argv = [_][:0]const u8{ "tiger", "string", "-s", "abc" };
    const outcome = try run(arena.allocator(), std.testing.io, out, &argv);

    try std.testing.expectEqual(Outcome.ok, outcome);
    const got = writer.written();
    // tiger of "abc" -> known digest, uppercase hex + trailing newline.
    try std.testing.expect(std.mem.indexOf(u8, got, "\n") != null);
    try std.testing.expect(got.len >= 24 * 2);
}

test "unknown command reports invalid command" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var writer = std.Io.Writer.Allocating.init(arena.allocator());
    const out = &writer.writer;

    const argv = [_][:0]const u8{ "tiger", "bogus", "-s", "abc" };
    const outcome = try run(arena.allocator(), std.testing.io, out, &argv);

    try std.testing.expectEqual(Outcome.invalid_command, outcome);
}

test "missing mode subcommand is invalid without extra message" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var writer = std.Io.Writer.Allocating.init(arena.allocator());
    const out = &writer.writer;

    const argv = [_][:0]const u8{"md4"};
    const outcome = try run(arena.allocator(), std.testing.io, out, &argv);

    try std.testing.expectEqual(Outcome.invalid_command, outcome);
    try std.testing.expectEqual(@as(usize, 0), writer.written().len);
}

test "foreign option on string mode is rejected" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var writer = std.Io.Writer.Allocating.init(arena.allocator());
    const out = &writer.writer;

    const argv = [_][:0]const u8{ "md5", "string", "-s", "abc", "-m", "deadbeef" };
    const outcome = try run(arena.allocator(), std.testing.io, out, &argv);
    try std.testing.expectEqual(Outcome.invalid_options, outcome);
}
