//! Command line interface for the `hc` executable.
//!
//! Argument parsing and dispatch to the mode run functions (string/hash/file/dir).
//! The yazap command tree follows the release argv layout: algorithm is a
//! top-level command, mode is a subcommand
//! (`hc <algorithm> <string|hash|file|dir> [options]`), and each mode owns only
//! its own options. Help is generated by yazap from that tree
//! (`hc -h`, `hc <algo> -h`, `hc <algo> <mode> -h`).

const std = @import("std");
const builtin = @import("builtin");
const yazap = @import("yazap");
const lib = @import("lib");
const hashes = @import("hashes");
const modes = @import("modes");

const App = yazap.App;
const Arg = yazap.Arg;
const ArgMatches = yazap.ArgMatches;
const Command = yazap.Command;
const YazapStdoutRedirect = lib.YazapStdoutRedirect;

pub const PROGRAM_NAME = "hc";

pub const opt_source = "source";
pub const opt_hash = "hash";
pub const opt_limit = "limit";
pub const opt_offset = "offset";
pub const opt_threads = "threads";
pub const opt_base64 = "base64";
pub const opt_sfv = "sfv";
pub const opt_noprobe = "noprobe";
pub const opt_noerroronfind = "noerroronfind";
pub const opt_save = "save";
pub const opt_lower = "lower";
pub const opt_time = "time";
pub const opt_checksumfile = "checksumfile";
pub const opt_recursively = "recursively";
pub const opt_performance = "performance";
pub const opt_dict = "dict";
pub const opt_min = "min";
pub const opt_max = "max";
pub const opt_include = "include";
pub const opt_exclude = "exclude";
pub const opt_search = "search";

const STRING_CMD = "string";
const HASH_CMD = "hash";
const FILE_CMD = "file";
const DIR_CMD = "dir";

pub const Mode = enum {
    string,
    hash,
    file,
    dir,
};

// --- Number parsing --------------------------------------------------------

pub const NumberError = error{InvalidCharacter};

/// Parses a signed 64-bit number: out of range values clamp to the signed
/// extremum based on their sign rather than erroring.
pub fn parseBigNumber(s: []const u8) NumberError!i64 {
    const trimmed = std.mem.trim(u8, s, &std.ascii.whitespace);
    if (trimmed.len == 0) return error.InvalidCharacter;
    return std.fmt.parseInt(i64, trimmed, 10) catch |err| switch (err) {
        error.Overflow => blk: {
            const negative = trimmed[0] == '-';
            break :blk if (negative) std.math.minInt(i64) else std.math.maxInt(i64);
        },
        error.InvalidCharacter => return error.InvalidCharacter,
    };
}

pub fn appName() []const u8 {
    return "Hash Calculator";
}

/// Prints the copyright banner:
/// "\n<APP_NAME> <version> <arch>\nCopyright ...\n\n"
pub fn printCopyright(out: *std.Io.Writer) !void {
    try lib.printProductBanner(out, appName());
}

// --- Threads resolution ----------------------------------------------------

pub fn resolveThreads(out: *std.Io.Writer, provided: ?[]const u8) i32 {
    const processors: u32 = @intCast(std.Thread.getCpuCount() catch 1);
    const processors_i32: i32 = @intCast(processors);

    var num: i32 = if (provided) |v|
        std.fmt.parseInt(i32, v, 10) catch 0
    else blk: {
        break :blk if (processors == 1) 1 else @intCast(@min(processors, processors / 2));
    };

    if (num < 1 or num > processors_i32) {
        const def: i32 = if (processors == 1) 1 else @intCast(processors / 2);
        out.print(
            "Threads number must be between 1 and {d} but it was set to {d}. Reset to default {d}\n",
            .{ processors, @as(u32, @bitCast(num)), @as(u32, @bitCast(def)) },
        ) catch {};
        num = def;
    }
    return num;
}

/// Reads and validates a limit/offset parameter. Prints the appropriate error
/// (no copyright for non-numeric, copyright + message for negative) and returns
/// `error.InvalidArgument` if the caller must abort (mapped to exit 1 in main).
fn readNumberParam(
    out: *std.Io.Writer,
    provided: ?[]const u8,
    option_name: []const u8,
) !void {
    if (provided) |v| {
        const n = parseBigNumber(v) catch {
            try out.print("Invalid parameter --{s} {s}. Must be number\n", .{ option_name, v });
            return error.InvalidArgument;
        };
        if (n < 0) {
            try printCopyright(out);
            try out.print("Invalid {s} option must be positive but was {d}\n", .{ option_name, n });
            return error.InvalidArgument;
        }
    }
}

// --- App construction (algorithm commands → mode subcommands) -------------

/// Value-taking option that also accepts attached empty values (`-s=`).
/// Yazap has no "required option" property; modes that need `--source`
/// enforce it themselves in `run*` (see issue #2 / InvalidArgument).
fn valueOption(
    name: []const u8,
    short_name: u8,
    description: []const u8,
    placeholder: ?[]const u8,
) Arg {
    var a = Arg.singleValueOption(name, short_name, description);
    a.setProperty(.allow_empty_value);
    if (placeholder) |p| a.setValuePlaceholder(p);
    return a;
}

fn addStringSubcommand(app: *App, parent: *Command) !void {
    var cmd = app.createCommand(STRING_CMD, "calculate hash sum of a string");
    cmd.setProperty(.help_on_empty_args);
    try cmd.addArg(valueOption(opt_source, 's', "string to calculate hash sum for", "string"));
    try cmd.addArg(Arg.booleanOption(opt_base64, 'b', "output hash as Base64"));
    try cmd.addArg(Arg.booleanOption(opt_lower, 'l', "output hash using low case (false by default)"));
    try parent.addSubcommand(cmd);
}

fn addHashSubcommand(app: *App, parent: *Command) !void {
    var cmd = app.createCommand(HASH_CMD, "restore the original string from a hash");
    cmd.setProperty(.help_on_empty_args);
    try cmd.addArg(valueOption(
        opt_source,
        's',
        "hash to restore initial string by. Required unless -p is specified",
        "string",
    ));
    try cmd.addArg(Arg.booleanOption(opt_base64, 'b', "interpret hash as Base64"));
    try cmd.addArg(valueOption(
        opt_dict,
        'a',
        "initial string's dictionary. All digits, upper and lower case latin symbols by default. Specify value ASCII here to use all ASCII charset as dictionary",
        "string",
    ));
    try cmd.addArg(valueOption(opt_min, 'n', "set minimum length of the string to restore. 1 by default", "int"));
    try cmd.addArg(valueOption(opt_max, 'x', "set maximum length of the string to restore. 10 by default", "int"));
    try cmd.addArg(Arg.booleanOption(opt_performance, 'p', "test performance by cracking 12345 string hash"));
    try cmd.addArg(Arg.booleanOption(opt_noprobe, null, "Disable hash crack time probing (how much time it may take)"));
    try cmd.addArg(valueOption(
        opt_threads,
        'T',
        "the number of threads to crack hash. The half of system processors by default. The value must be between 1 and processor count.",
        "int",
    ));
    try parent.addSubcommand(cmd);
}

/// Shared file/dir options: hash window + output format flags.
fn addSharedFileOpts(cmd: *Command) !void {
    try cmd.addArg(valueOption(
        opt_limit,
        'z',
        "set the limit in bytes of the part of the file to calculate hash for. The whole file by default will be applied",
        "number",
    ));
    try cmd.addArg(valueOption(
        opt_offset,
        'q',
        "set start position within file to calculate hash from. Zero by default",
        "number",
    ));
    try cmd.addArg(Arg.booleanOption(opt_checksumfile, 'c', "output hash in file checksum format"));
    try cmd.addArg(valueOption(
        opt_save,
        'o',
        "save files' hashes into the file specified besides console output.",
        "file",
    ));
    try cmd.addArg(Arg.booleanOption(opt_time, 't', "show calculation time (false by default)"));
    try cmd.addArg(Arg.booleanOption(
        opt_sfv,
        null,
        "output hash in the SFV (Simple File Verification) format (false by default). Only for CRC32 or CRC32C.",
    ));
    try cmd.addArg(Arg.booleanOption(opt_lower, 'l', "output hash using low case (false by default)"));
    try cmd.addArg(Arg.booleanOption(opt_base64, 'b', "output hash as Base64"));
}

fn addFileSubcommand(app: *App, parent: *Command) !void {
    var cmd = app.createCommand(FILE_CMD, "calculate hash sum of a file");
    cmd.setProperty(.help_on_empty_args);
    try cmd.addArg(valueOption(
        opt_source,
        's',
        "full path to file to calculate hash sum of",
        "file",
    ));
    try cmd.addArg(valueOption(opt_hash, 'm', "hash to validate file", "string"));
    try addSharedFileOpts(&cmd);
    try parent.addSubcommand(cmd);
}

fn addDirSubcommand(app: *App, parent: *Command) !void {
    var cmd = app.createCommand(DIR_CMD, "calculate hash sums of files in a directory");
    cmd.setProperty(.help_on_empty_args);
    try cmd.addArg(valueOption(
        opt_source,
        's',
        "full path to dir to calculate all content's hashes",
        "string",
    ));
    try cmd.addArg(valueOption(
        opt_hash,
        'm',
        "hash to validate files in directory",
        "string",
    ));
    try cmd.addArg(valueOption(
        opt_exclude,
        'e',
        "exclude files that match the pattern specified. It's possible to use several patterns separated by ;",
        "string",
    ));
    try cmd.addArg(valueOption(
        opt_include,
        'i',
        "include only files that match the pattern specified. It's possible to use several patterns separated by ;",
        "string",
    ));
    try cmd.addArg(valueOption(opt_search, 'H', "hash to search a file that matches it", "string"));
    try cmd.addArg(Arg.booleanOption(opt_recursively, 'r', "scan directory recursively"));
    try addSharedFileOpts(&cmd);
    try cmd.addArg(Arg.booleanOption(
        opt_noerroronfind,
        null,
        "Disable error output while search files. False by default.",
    ));
    try parent.addSubcommand(cmd);
}

fn addAlgorithmCommand(app: *App, root: *Command, name: []const u8) !void {
    var algo = app.createCommand(name, null);
    algo.setProperty(.help_on_empty_args);
    algo.setProperty(.subcommand_required);
    try addStringSubcommand(app, &algo);
    try addHashSubcommand(app, &algo);
    try addFileSubcommand(app, &algo);
    try addDirSubcommand(app, &algo);
    try root.addSubcommand(algo);
}

fn algoNameLess(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.order(u8, a, b) == .lt;
}

fn createApp(allocator: std.mem.Allocator) !*App {
    const app = try allocator.create(App);
    errdefer allocator.destroy(app);

    const descr = try lib.productBanner(allocator, appName());
    app.* = App.init(allocator, PROGRAM_NAME, descr);

    var root = app.rootCommand();
    root.setProperty(.help_on_empty_args);
    root.setProperty(.subcommand_required);

    // Register algorithms in lexicographic order so `hc -h` lists them sorted.
    var names: [hashes.hashes.len][]const u8 = undefined;
    for (hashes.hashes, 0..) |h, i| names[i] = h.name;
    std.mem.sort([]const u8, &names, {}, algoNameLess);
    for (names) |name| {
        try addAlgorithmCommand(app, root, name);
    }

    return app;
}

/// Short names of options that take a value.
const value_option_short = [_]u8{ 's', 'm', 'z', 'q', 'T', 'o', 'a', 'n', 'x', 'i', 'e', 'H' };

/// Long names of options that take a value.
const value_option_long = [_][]const u8{
    "source", "hash", "limit", "offset",  "threads", "save",
    "dict",   "min",  "max",   "include", "exclude", "search",
};

/// Short names of options that take a numeric value (limit/offset/min/max/threads).
const numeric_option_short = [_]u8{ 'z', 'q', 'n', 'x', 'T' };

/// Long names of options that take a numeric value.
const numeric_option_long = [_][]const u8{ "limit", "offset", "min", "max", "threads" };

fn isBareValueOption(tok: []const u8) bool {
    return lib.isBareNamedOption(tok, &value_option_short, &value_option_long);
}

fn isNumericValueOption(tok: []const u8) bool {
    return lib.isBareNamedOption(tok, &numeric_option_short, &numeric_option_long);
}

/// yazap's tokenizer skips empty argv elements and treats `-10` as a short
/// option group, so a value passed as a separate token is lost in two cases:
///   * `-s ""`   -> empty value
///   * `-z -10`  -> negative numeric value
/// This rewrites such a bare value-option followed by the problematic token
/// into the attached form (`-s=` / `-z=-10`), which yazap captures.
fn shouldAttach(opt_tok: []const u8, next_tok: []const u8) bool {
    if (!isBareValueOption(opt_tok)) return false;
    if (next_tok.len == 0) return true;
    if (isNumericValueOption(opt_tok) and lib.isNegativeNumber(next_tok)) return true;
    return false;
}

// --- Dispatch helpers ------------------------------------------------------

fn runString(
    matches: ArgMatches,
    bctx: *const modes.BuiltinCtx,
    env: modes.RunEnv,
) !void {
    const source = matches.getSingleValue(opt_source) orelse {
        try env.out.print("--{s} option is required\n", .{opt_source});
        return error.InvalidArgument;
    };
    var sctx: modes.StringCtx = .{
        .builtin = bctx,
        .string = source,
        .is_base64 = matches.containsArg(opt_base64),
    };
    const h = try modes.builtinInit(bctx, env);
    try modes.strRun(&sctx, env, h);
}

fn runHash(
    matches: ArgMatches,
    bctx: *const modes.BuiltinCtx,
    env: modes.RunEnv,
    app: *App,
    io: std.Io,
) !void {
    const performance = matches.containsArg(opt_performance);
    const source = matches.getSingleValue(opt_source);
    if (!performance and (source == null or source.?.len == 0)) {
        try env.out.print(
            "--{s} option is required to restore hash. Use -p to run performance test without it\n",
            .{opt_source},
        );
        // Flush our buffered stdout before yazap writes help via OS stdout.
        // Skip in unit tests: YazapStdoutRedirect remaps stderr→stdout, and under
        // `zig build test --listen` that stdout is the IPC pipe (would hang).
        if (!builtin.is_test) {
            try env.out.flush();
            const help_out = try YazapStdoutRedirect.begin();
            defer help_out.restore();
            try app.displaySubcommandHelp(io);
        }
        return error.InvalidArgument;
    }

    const threads = resolveThreads(env.out, matches.getSingleValue(opt_threads));

    var hctx: modes.HashCtx = .{
        .builtin = bctx,
        .hash = source,
        .is_base64 = matches.containsArg(opt_base64),
        .no_probe = matches.containsArg(opt_noprobe),
        .performance = performance,
        .threads = threads,
    };
    if (matches.getSingleValue(opt_dict)) |d| hctx.dictionary = d;
    if (matches.getSingleValue(opt_min)) |m| hctx.min = std.fmt.parseInt(i32, m, 10) catch 0;
    if (matches.getSingleValue(opt_max)) |m| hctx.max = std.fmt.parseInt(i32, m, 10) catch 0;

    const h = try modes.builtinInit(bctx, env);
    try modes.hashRun(&hctx, env, h);
}

/// Shared FileOptions fill for file/dir modes (limit/offset + output flags).
fn fileOptionsFromMatches(
    matches: ArgMatches,
    bctx: *const modes.BuiltinCtx,
    out: *std.Io.Writer,
) !modes.FileOptions {
    try readNumberParam(out, matches.getSingleValue(opt_limit), opt_limit);
    try readNumberParam(out, matches.getSingleValue(opt_offset), opt_offset);

    var opts: modes.FileOptions = .{
        .builtin = bctx,
        .limit = if (matches.getSingleValue(opt_limit)) |v| (parseBigNumber(v) catch 0) else std.math.maxInt(i64),
        .offset = if (matches.getSingleValue(opt_offset)) |v| (parseBigNumber(v) catch 0) else 0,
        .show_time = matches.containsArg(opt_time),
        .is_verify = matches.containsArg(opt_checksumfile),
        .result_in_sfv = matches.containsArg(opt_sfv),
        .is_base64 = matches.containsArg(opt_base64),
    };
    if (matches.getSingleValue(opt_hash)) |h| opts.hash = h;
    if (matches.getSingleValue(opt_save)) |s| opts.save_result_path = s;
    return opts;
}

fn runFile(
    matches: ArgMatches,
    bctx: *const modes.BuiltinCtx,
    env: modes.RunEnv,
) !void {
    const file_path = matches.getSingleValue(opt_source) orelse {
        try env.out.print("--{s} option is required\n", .{opt_source});
        return error.InvalidArgument;
    };

    var fctx: modes.FileCtx = .{
        .opts = try fileOptionsFromMatches(matches, bctx, env.out),
        .file_path = file_path,
    };

    const h = try modes.builtinInit(bctx, env);
    try modes.fileRun(&fctx, env, h);
}

fn runDir(
    matches: ArgMatches,
    bctx: *const modes.BuiltinCtx,
    env: modes.RunEnv,
) !void {
    const dir_path = matches.getSingleValue(opt_source) orelse {
        try env.out.print("--{s} option is required\n", .{opt_source});
        return error.InvalidArgument;
    };

    var dctx: modes.DirCtx = .{
        .opts = try fileOptionsFromMatches(matches, bctx, env.out),
        .dir_path = dir_path,
        .recursively = matches.containsArg(opt_recursively),
        .no_error_on_find = matches.containsArg(opt_noerroronfind),
    };
    if (matches.getSingleValue(opt_search)) |s| dctx.search_hash = s;
    if (matches.getSingleValue(opt_include)) |i| dctx.include_pattern = i;
    if (matches.getSingleValue(opt_exclude)) |e| dctx.exclude_pattern = e;

    const h = try modes.builtinInit(bctx, env);
    try modes.dirRun(&dctx, env, h);
}

fn knownAlgorithm(name: []const u8) bool {
    return hashes.getHash(name) != null;
}

// --- Entry point -----------------------------------------------------------

pub const Outcome = enum { ok, invalid_command, invalid_options };

/// Parses argv and dispatches to the matching mode.
/// Returns the outcome so the caller can map it to a process exit code.
pub fn run(
    allocator: std.mem.Allocator,
    io: std.Io,
    out: *std.Io.Writer,
    argv: []const [:0]const u8,
) !Outcome {
    const app = try createApp(allocator);
    defer {
        app.deinit();
        allocator.destroy(app);
    }

    // Rewrite `-s ""` (empty value) and `-z -10` (negative numeric value)
    // into attached form so yazap captures them (it otherwise skips empty
    // argv elements and treats `-10` as a short option group).
    const argv_norm = try lib.normalizeArgv(allocator, argv, shouldAttach);

    // Empty argv / -h/--help: yazap prints structured help from the command
    // tree (algorithms → modes → options) and exits. Nested helps
    // (`hc md5 -h`, `hc md5 string -h`) use the same path. Diagnostics are
    // redirected to stdout for release parity (see YazapStdoutRedirect).
    const matches = blk: {
        const yazap_out = try YazapStdoutRedirect.begin();
        defer yazap_out.restore();
        break :blk app.parseFrom(io, argv_norm) catch |err| switch (err) {
            error.UnrecognizedCommand => {
                // Yazap already printed "unrecognized command …" to stdout.
                return if (argv_norm.len > 0 and knownAlgorithm(argv_norm[0]))
                    .invalid_command
                else
                    .invalid_options;
            },
            error.SubcommandNotProvided => return .invalid_command,
            error.UnrecognizedOption,
            error.OptionValueNotProvided,
            error.UnexpectedOptionValue,
            error.EmptyOptionValue,
            error.InvalidOptionValue,
            error.TooFewOptionValue,
            error.TooManyOptionValue,
            error.PositionalArgumentNotProvided,
            => return .invalid_options,
            else => return err,
        };
    };

    var algorithm: ?[]const u8 = null;
    var mode_matches: ?ArgMatches = null;
    var mode: ?Mode = null;

    for (hashes.hashes) |h| {
        const algo_m = matches.subcommandMatches(h.name) orelse continue;
        algorithm = h.name;
        inline for (.{
            .{ Mode.string, STRING_CMD },
            .{ Mode.hash, HASH_CMD },
            .{ Mode.file, FILE_CMD },
            .{ Mode.dir, DIR_CMD },
        }) |pair| {
            if (algo_m.subcommandMatches(pair[1])) |mm| {
                mode_matches = mm;
                mode = pair[0];
                break;
            }
        }
        break;
    }

    if (algorithm == null or mode == null or mode_matches == null) {
        return .invalid_command;
    }

    const bctx: modes.BuiltinCtx = .{
        .hash_algorithm = algorithm.?,
        .is_print_low_case = mode_matches.?.containsArg(opt_lower),
    };

    const env: modes.RunEnv = .{
        .io = io,
        .allocator = allocator,
        .out = out,
    };

    switch (mode.?) {
        .string => try runString(mode_matches.?, &bctx, env),
        .hash => try runHash(mode_matches.?, &bctx, env, app, io),
        .file => try runFile(mode_matches.?, &bctx, env),
        .dir => try runDir(mode_matches.?, &bctx, env),
    }

    return .ok;
}

// Tests

test "parseBigNumber valid values" {
    try std.testing.expectEqual(@as(i64, 0), try parseBigNumber("0"));
    try std.testing.expectEqual(@as(i64, 42), try parseBigNumber("42"));
    try std.testing.expectEqual(@as(i64, -10), try parseBigNumber("-10"));
    try std.testing.expectEqual(@as(i64, 1024), try parseBigNumber(" 1024 "));
}

test "parseBigNumber clamps overflow to signed extremum" {
    try std.testing.expectEqual(std.math.maxInt(i64), try parseBigNumber("18446744073709551615"));
    try std.testing.expectEqual(std.math.minInt(i64), try parseBigNumber("-10223372036854775808"));
}

test "parseBigNumber rejects non-numeric" {
    try std.testing.expectError(error.InvalidCharacter, parseBigNumber("a"));
    try std.testing.expectError(error.InvalidCharacter, parseBigNumber(""));
}

test "algorithm help names sort lexicographically" {
    var names: [hashes.hashes.len][]const u8 = undefined;
    for (hashes.hashes, 0..) |h, i| names[i] = h.name;
    std.mem.sort([]const u8, &names, {}, algoNameLess);
    for (names[0 .. names.len - 1], names[1..]) |a, b| {
        try std.testing.expect(std.mem.order(u8, a, b) == .lt);
    }
}

test "isNegativeNumber distinguishes values from options" {
    try std.testing.expect(lib.isNegativeNumber("-10"));
    try std.testing.expect(lib.isNegativeNumber("-10223372036854775808"));
    try std.testing.expect(!lib.isNegativeNumber("10"));
    try std.testing.expect(!lib.isNegativeNumber("--limit"));
    try std.testing.expect(!lib.isNegativeNumber("-l"));
    try std.testing.expect(!lib.isNegativeNumber("-"));
}

test "normalizeArgv attaches empty and negative values" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    {
        const argv = [_][:0]const u8{ "-s", "" };
        const argv_slice: []const [:0]const u8 = &argv;
        const out = try lib.normalizeArgv(allocator, argv_slice, shouldAttach);
        try std.testing.expectEqual(@as(usize, 1), out.len);
        try std.testing.expectEqualStrings("-s=", out[0]);
    }
    {
        const argv = [_][:0]const u8{ "-z", "-10" };
        const argv_slice: []const [:0]const u8 = &argv;
        const out = try lib.normalizeArgv(allocator, argv_slice, shouldAttach);
        try std.testing.expectEqual(@as(usize, 1), out.len);
        try std.testing.expectEqualStrings("-z=-10", out[0]);
    }
    {
        // Positive numbers and normal tokens are untouched.
        const argv = [_][:0]const u8{ "-z", "10", "-s", "abc" };
        const argv_slice: []const [:0]const u8 = &argv;
        const out = try lib.normalizeArgv(allocator, argv_slice, shouldAttach);
        try std.testing.expect(out.ptr == argv_slice.ptr);
    }
}

test "string mode dispatch produces hash output" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var writer = std.Io.Writer.Allocating.init(arena.allocator());
    const out = &writer.writer;

    const argv = [_][:0]const u8{ "tiger", "string", "-s", "abc" };
    const outcome = try run(arena.allocator(), std.testing.io, out, &argv);

    try std.testing.expectEqual(Outcome.ok, outcome);
    const got = writer.written();
    // tiger of "abc" -> known digest, uppercase hex + trailing newline.
    try std.testing.expect(std.mem.indexOf(u8, got, "\n") != null);
    try std.testing.expect(got.len >= 24 * 2);
}

test "unknown command reports invalid command" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var writer = std.Io.Writer.Allocating.init(arena.allocator());
    const out = &writer.writer;

    const argv = [_][:0]const u8{ "tiger", "bogus", "-s", "abc" };
    const outcome = try run(arena.allocator(), std.testing.io, out, &argv);

    try std.testing.expectEqual(Outcome.invalid_command, outcome);
}

test "foreign option on string mode is rejected" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var writer = std.Io.Writer.Allocating.init(arena.allocator());
    const out = &writer.writer;

    const argv = [_][:0]const u8{ "md5", "string", "-s", "abc", "-m", "deadbeef" };
    const outcome = try run(arena.allocator(), std.testing.io, out, &argv);
    try std.testing.expectEqual(Outcome.invalid_options, outcome);
}

test "missing source returns InvalidArgument" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var writer = std.Io.Writer.Allocating.init(arena.allocator());
    const out = &writer.writer;

    // Pass a harmless flag so yazap does not take the help_on_empty_args →
    // process.exit(0) path; we want the mode's own validation.
    const cases = [_][]const [:0]const u8{
        &[_][:0]const u8{ "md5", "string", "-l" },
        &[_][:0]const u8{ "md5", "hash", "--noprobe" },
        &[_][:0]const u8{ "md5", "file", "-t" },
        &[_][:0]const u8{ "md5", "dir", "-t" },
    };
    for (cases) |argv| {
        try std.testing.expectError(
            error.InvalidArgument,
            run(arena.allocator(), std.testing.io, out, argv),
        );
    }
}
