//! Command line interface for the `hc` executable.
//!
//! Argument parsing and dispatch to the mode run functions (string/hash/file/dir).
//! The yazap command tree follows the release argv layout: algorithm is a
//! top-level command, mode is a subcommand
//! (`hc <algorithm> <string|hash|file|dir> [options]`), and each mode owns only
//! its own options. Help is generated by yazap from that tree
//! (`hc -h`, `hc <algo> -h`, `hc <algo> <mode> -h`).

const std = @import("std");
const builtin = @import("builtin");
const yazap = @import("yazap");
const lib = @import("lib");
const hashes = @import("hashes");
const modes = @import("modes");

const App = yazap.App;
const Arg = yazap.Arg;
const ArgMatches = yazap.ArgMatches;
const Command = yazap.Command;
const YazapStdoutRedirect = lib.YazapStdoutRedirect;

pub const PROGRAM_NAME = "hc";

pub const opt_source = "source";
pub const opt_hash = "hash";
pub const opt_limit = "limit";
pub const opt_offset = "offset";
pub const opt_threads = "threads";
pub const opt_base64 = "base64";
pub const opt_sfv = "sfv";
pub const opt_noprobe = "noprobe";
pub const opt_noerroronfind = "noerroronfind";
pub const opt_save = "save";
pub const opt_lower = "lower";
pub const opt_time = "time";
pub const opt_checksumfile = "checksumfile";
pub const opt_recursively = "recursively";
pub const opt_performance = "performance";
pub const opt_dict = "dict";
pub const opt_min = "min";
pub const opt_max = "max";
pub const opt_include = "include";
pub const opt_exclude = "exclude";
pub const opt_search = "search";

const STRING_CMD = "string";
const HASH_CMD = "hash";
const FILE_CMD = "file";
const DIR_CMD = "dir";

pub const Mode = enum {
    string,
    hash,
    file,
    dir,
};

fn parseI64(s: []const u8) std.fmt.ParseIntError!i64 {
    return std.fmt.parseInt(i64, std.mem.trim(u8, s, &std.ascii.whitespace), 10);
}

pub fn appName() []const u8 {
    return "Hash Calculator";
}

/// Prints the copyright banner:
/// "\n<APP_NAME> <version> <arch>\nCopyright ...\n\n"
pub fn printCopyright(out: *std.Io.Writer) !void {
    try lib.printProductBanner(out, appName());
}

// --- Threads resolution ----------------------------------------------------

pub fn resolveThreads(out: *std.Io.Writer, provided: ?[]const u8) i32 {
    const processors: u32 = @intCast(std.Thread.getCpuCount() catch 1);
    const processors_i32: i32 = @intCast(processors);

    var num: i32 = if (provided) |v|
        std.fmt.parseInt(i32, v, 10) catch 0
    else blk: {
        break :blk if (processors == 1) 1 else @intCast(@min(processors, processors / 2));
    };

    if (num < 1 or num > processors_i32) {
        const def: i32 = if (processors == 1) 1 else @intCast(processors / 2);
        out.print(
            "Threads number must be between 1 and {d} but it was set to {d}. Reset to default {d}\n",
            .{ processors, num, def },
        ) catch {};
        num = def;
    }
    return num;
}

fn reportParseNumberError(
    out: *std.Io.Writer,
    option_name: []const u8,
    v: []const u8,
    err: std.fmt.ParseIntError,
) !void {
    switch (err) {
        error.InvalidCharacter => try out.print("Invalid parameter --{s} {s}. Must be number\n", .{ option_name, v }),
        error.Overflow => try out.print("Invalid parameter --{s} {s}. Must be a 64-bit number\n", .{ option_name, v }),
    }
}

/// Reads and validates a limit/offset parameter. Absent option yields `default`.
/// Prints the appropriate error (no copyright for non-numeric, copyright +
/// message for negative) and returns `error.InvalidArgument` if the caller
/// must abort (mapped to exit 1 in main).
fn readNumberParam(
    out: *std.Io.Writer,
    provided: ?[]const u8,
    option_name: []const u8,
    default: i64,
) !i64 {
    const v = provided orelse return default;
    const n = parseI64(v) catch |err| {
        try reportParseNumberError(out, option_name, v, err);
        return error.InvalidArgument;
    };
    if (n < 0) {
        try printCopyright(out);
        try out.print("Invalid {s} option must be positive but was {d}\n", .{ option_name, n });
        return error.InvalidArgument;
    }
    return n;
}

/// Reads and validates a brute-force length bound (-n/-x): readNumberParam's
/// contract plus the i32 range (`HashCtx.min`/`max` are i32). Returns the
/// parsed value, or 0 when the option was not given (mode default marker).
fn readLengthParam(
    out: *std.Io.Writer,
    provided: ?[]const u8,
    option_name: []const u8,
) !i32 {
    const n = try readNumberParam(out, provided, option_name, 0);
    if (provided == null) return 0;
    return std.math.cast(i32, n) orelse {
        try out.print("Invalid parameter --{s} {s}. Must be a 32-bit number\n", .{ option_name, provided.? });
        return error.InvalidArgument;
    };
}

// --- App construction (algorithm commands → mode subcommands) -------------

/// Value-taking option that also accepts attached empty values (`-s=`).
/// Yazap has no "required option" property; modes that need `--source`
/// enforce it themselves in `run*` (see issue #2 / InvalidArgument).
fn valueOption(
    name: []const u8,
    short_name: u8,
    description: []const u8,
    placeholder: ?[]const u8,
) Arg {
    var a = Arg.singleValueOption(name, short_name, description);
    a.setProperty(.allow_empty_value);
    if (placeholder) |p| a.setValuePlaceholder(p);
    return a;
}

fn addStringSubcommand(app: *App, parent: *Command) !void {
    var cmd = app.createCommand(STRING_CMD, "calculate hash sum of a string");
    cmd.setProperty(.help_on_empty_args);
    try cmd.addArg(valueOption(opt_source, 's', "string to calculate hash sum for", "string"));
    try cmd.addArg(Arg.booleanOption(opt_base64, 'b', "output hash as Base64"));
    try cmd.addArg(Arg.booleanOption(opt_lower, 'l', "output hash using low case (false by default)"));
    try parent.addSubcommand(cmd);
}

fn addHashSubcommand(app: *App, parent: *Command) !void {
    var cmd = app.createCommand(HASH_CMD, "restore the original string from a hash");
    cmd.setProperty(.help_on_empty_args);
    try cmd.addArg(valueOption(
        opt_source,
        's',
        "hash to restore initial string by. Required unless -p is specified",
        "string",
    ));
    try cmd.addArg(Arg.booleanOption(opt_base64, 'b', "interpret hash as Base64"));
    try cmd.addArg(valueOption(
        opt_dict,
        'a',
        "initial string's dictionary. All digits, upper and lower case latin symbols by default. Specify value ASCII here to use all ASCII charset as dictionary",
        "string",
    ));
    try cmd.addArg(valueOption(opt_min, 'n', "set minimum length of the string to restore. 1 by default", "int"));
    try cmd.addArg(valueOption(opt_max, 'x', "set maximum length of the string to restore. 10 by default", "int"));
    try cmd.addArg(Arg.booleanOption(opt_performance, 'p', "test performance by cracking 12345 string hash"));
    try cmd.addArg(Arg.booleanOption(opt_noprobe, null, "Disable hash crack time probing (how much time it may take)"));
    try cmd.addArg(valueOption(
        opt_threads,
        'T',
        "the number of threads to crack hash. The half of system processors by default. The value must be between 1 and processor count.",
        "int",
    ));
    try parent.addSubcommand(cmd);
}

/// Shared file/dir options: hash window + output format flags.
fn addSharedFileOpts(cmd: *Command) !void {
    try cmd.addArg(valueOption(
        opt_limit,
        'z',
        "set the limit in bytes of the part of the file to calculate hash for. The whole file by default will be applied",
        "number",
    ));
    try cmd.addArg(valueOption(
        opt_offset,
        'q',
        "set start position within file to calculate hash from. Zero by default",
        "number",
    ));
    try cmd.addArg(Arg.booleanOption(opt_checksumfile, 'c', "output hash in file checksum format"));
    try cmd.addArg(valueOption(
        opt_save,
        'o',
        "save files' hashes into the file specified besides console output.",
        "file",
    ));
    try cmd.addArg(Arg.booleanOption(opt_time, 't', "show calculation time (false by default)"));
    try cmd.addArg(Arg.booleanOption(
        opt_sfv,
        null,
        "output hash in the SFV (Simple File Verification) format (false by default). Only for CRC32 or CRC32C.",
    ));
    try cmd.addArg(Arg.booleanOption(opt_lower, 'l', "output hash using low case (false by default)"));
    try cmd.addArg(Arg.booleanOption(opt_base64, 'b', "output hash as Base64"));
}

fn addFileSubcommand(app: *App, parent: *Command) !void {
    var cmd = app.createCommand(FILE_CMD, "calculate hash sum of a file");
    cmd.setProperty(.help_on_empty_args);
    try cmd.addArg(valueOption(
        opt_source,
        's',
        "full path to file to calculate hash sum of",
        "file",
    ));
    try cmd.addArg(valueOption(opt_hash, 'm', "hash to validate file", "string"));
    try addSharedFileOpts(&cmd);
    try parent.addSubcommand(cmd);
}

fn addDirSubcommand(app: *App, parent: *Command) !void {
    var cmd = app.createCommand(DIR_CMD, "calculate hash sums of files in a directory");
    cmd.setProperty(.help_on_empty_args);
    try cmd.addArg(valueOption(
        opt_source,
        's',
        "full path to dir to calculate all content's hashes",
        "string",
    ));
    try cmd.addArg(valueOption(
        opt_hash,
        'm',
        "hash to validate files in directory",
        "string",
    ));
    try cmd.addArg(valueOption(
        opt_exclude,
        'e',
        "exclude files that match the pattern specified. It's possible to use several patterns separated by ;",
        "string",
    ));
    try cmd.addArg(valueOption(
        opt_include,
        'i',
        "include only files that match the pattern specified. It's possible to use several patterns separated by ;",
        "string",
    ));
    try cmd.addArg(valueOption(opt_search, 'H', "hash to search a file that matches it", "string"));
    try cmd.addArg(Arg.booleanOption(opt_recursively, 'r', "scan directory recursively"));
    try addSharedFileOpts(&cmd);
    try cmd.addArg(Arg.booleanOption(
        opt_noerroronfind,
        null,
        "Disable error output while search files. False by default.",
    ));
    try parent.addSubcommand(cmd);
}

fn addAlgorithmCommand(app: *App, root: *Command, name: []const u8) !void {
    var algo = app.createCommand(name, null);
    algo.setProperty(.help_on_empty_args);
    algo.setProperty(.subcommand_required);
    try addStringSubcommand(app, &algo);
    try addHashSubcommand(app, &algo);
    try addFileSubcommand(app, &algo);
    try addDirSubcommand(app, &algo);
    try root.addSubcommand(algo);
}

fn algoNameLess(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.order(u8, a, b) == .lt;
}

fn createApp(allocator: std.mem.Allocator) !*App {
    const app = try allocator.create(App);
    errdefer allocator.destroy(app);

    const descr = try lib.productBanner(allocator, appName());
    app.* = App.init(allocator, PROGRAM_NAME, descr);

    var root = app.rootCommand();
    root.setProperty(.help_on_empty_args);
    root.setProperty(.subcommand_required);

    // Register algorithms in lexicographic order so `hc -h` lists them sorted.
    var names: [hashes.hashes.len][]const u8 = undefined;
    for (hashes.hashes, 0..) |h, i| names[i] = h.name;
    std.mem.sort([]const u8, &names, {}, algoNameLess);
    for (names) |name| {
        try addAlgorithmCommand(app, root, name);
    }

    return app;
}

/// Single source of truth for value-taking options used by the argv
/// normalizer: long name, short name, and whether the value is numeric
/// (numeric options additionally accept a separate negative token).
/// Keep in sync with the `valueOption(...)` registrations above.
const ValueOpt = struct {
    long: []const u8,
    short: u8,
    numeric: bool = false,
};

const value_options = [_]ValueOpt{
    .{ .long = "source", .short = 's' },
    .{ .long = "hash", .short = 'm' },
    .{ .long = "limit", .short = 'z', .numeric = true },
    .{ .long = "offset", .short = 'q', .numeric = true },
    .{ .long = "threads", .short = 'T', .numeric = true },
    .{ .long = "save", .short = 'o' },
    .{ .long = "dict", .short = 'a' },
    .{ .long = "min", .short = 'n', .numeric = true },
    .{ .long = "max", .short = 'x', .numeric = true },
    .{ .long = "include", .short = 'i' },
    .{ .long = "exclude", .short = 'e' },
    .{ .long = "search", .short = 'H' },
};

/// yazap's tokenizer skips empty argv elements and treats `-10` as a short
/// option group, so a value passed as a separate token is lost in two cases:
///   * `-s ""`   -> empty value
///   * `-z -10`  -> negative numeric value
/// This rewrites such a bare value-option followed by the problematic token
/// into the attached form (`-s=` / `-z=-10`), which yazap captures.
fn shouldAttach(opt_tok: []const u8, next_tok: []const u8) bool {
    const numeric = blk: {
        if (opt_tok.len == 2 and opt_tok[0] == '-') {
            for (value_options) |o| if (opt_tok[1] == o.short) break :blk o.numeric;
        } else if (std.mem.startsWith(u8, opt_tok, "--") and std.mem.indexOfScalar(u8, opt_tok, '=') == null) {
            for (value_options) |o| if (std.mem.eql(u8, opt_tok[2..], o.long)) break :blk o.numeric;
        }
        return false;
    };
    if (next_tok.len == 0) return true;
    return numeric and lib.isNegativeNumber(next_tok);
}

// --- Dispatch helpers ------------------------------------------------------

fn runString(
    matches: ArgMatches,
    low_case: bool,
    env: modes.RunEnv,
    hash_def: *const hashes.HashDefinition,
) !void {
    const source = matches.getSingleValue(opt_source) orelse {
        try env.out.print("--{s} option is required\n", .{opt_source});
        return error.InvalidArgument;
    };
    var sctx: modes.StringCtx = .{
        .string = source,
        .is_base64 = matches.containsArg(opt_base64),
        .low_case = low_case,
    };
    try modes.strRun(&sctx, env, hash_def);
}

fn runHash(
    matches: ArgMatches,
    env: modes.RunEnv,
    app: *App,
    io: std.Io,
    hash_def: *const hashes.HashDefinition,
) !void {
    const performance = matches.containsArg(opt_performance);
    const source = matches.getSingleValue(opt_source);
    if (!performance and (source == null or source.?.len == 0)) {
        try env.out.print(
            "--{s} option is required to restore hash. Use -p to run performance test without it\n",
            .{opt_source},
        );
        // Flush our buffered stdout before yazap writes help via OS stdout.
        // Skip in unit tests: YazapStdoutRedirect remaps stderr→stdout, and under
        // `zig build test --listen` that stdout is the IPC pipe (would hang).
        if (!builtin.is_test) {
            try env.out.flush();
            const help_out = try YazapStdoutRedirect.begin();
            defer help_out.restore();
            try app.displaySubcommandHelp(io);
        }
        return error.InvalidArgument;
    }

    const threads = resolveThreads(env.out, matches.getSingleValue(opt_threads));

    var hctx: modes.HashCtx = .{
        .hash = source,
        .is_base64 = matches.containsArg(opt_base64),
        .no_probe = matches.containsArg(opt_noprobe),
        .performance = performance,
        .threads = threads,
    };
    if (matches.getSingleValue(opt_dict)) |d| hctx.dictionary = d;
    hctx.min = try readLengthParam(env.out, matches.getSingleValue(opt_min), opt_min);
    hctx.max = try readLengthParam(env.out, matches.getSingleValue(opt_max), opt_max);

    try modes.hashRun(&hctx, env, hash_def);
}

/// Shared FileOptions fill for file/dir modes (limit/offset + output flags).
fn fileOptionsFromMatches(
    matches: ArgMatches,
    low_case: bool,
    out: *std.Io.Writer,
) !modes.FileOptions {
    var opts: modes.FileOptions = .{
        .limit = try readNumberParam(out, matches.getSingleValue(opt_limit), opt_limit, std.math.maxInt(i64)),
        .offset = try readNumberParam(out, matches.getSingleValue(opt_offset), opt_offset, 0),
        .show_time = matches.containsArg(opt_time),
        .is_verify = matches.containsArg(opt_checksumfile),
        .result_in_sfv = matches.containsArg(opt_sfv),
        .is_base64 = matches.containsArg(opt_base64),
        .low_case = low_case,
    };
    if (matches.getSingleValue(opt_hash)) |h| opts.hash = h;
    if (matches.getSingleValue(opt_save)) |s| opts.save_result_path = s;
    return opts;
}

fn runFile(
    matches: ArgMatches,
    low_case: bool,
    env: modes.RunEnv,
    hash_def: *const hashes.HashDefinition,
) !void {
    const file_path = matches.getSingleValue(opt_source) orelse {
        try env.out.print("--{s} option is required\n", .{opt_source});
        return error.InvalidArgument;
    };

    var fctx: modes.FileCtx = .{
        .opts = try fileOptionsFromMatches(matches, low_case, env.out),
        .file_path = file_path,
    };

    try modes.fileRun(&fctx, env, hash_def);
}

fn runDir(
    matches: ArgMatches,
    low_case: bool,
    env: modes.RunEnv,
    hash_def: *const hashes.HashDefinition,
) !void {
    const dir_path = matches.getSingleValue(opt_source) orelse {
        try env.out.print("--{s} option is required\n", .{opt_source});
        return error.InvalidArgument;
    };

    var dctx: modes.DirCtx = .{
        .opts = try fileOptionsFromMatches(matches, low_case, env.out),
        .dir_path = dir_path,
        .recursively = matches.containsArg(opt_recursively),
        .no_error_on_find = matches.containsArg(opt_noerroronfind),
    };
    if (matches.getSingleValue(opt_search)) |s| dctx.search_hash = s;
    if (matches.getSingleValue(opt_include)) |i| dctx.include_pattern = i;
    if (matches.getSingleValue(opt_exclude)) |e| dctx.exclude_pattern = e;

    try modes.dirRun(&dctx, env, hash_def);
}

fn knownAlgorithm(name: []const u8) bool {
    return hashes.getHash(name) != null;
}

// --- Entry point -----------------------------------------------------------

pub const Outcome = enum { ok, invalid_command, invalid_options };

/// Parses argv and dispatches to the matching mode.
/// Returns the outcome so the caller can map it to a process exit code.
pub fn run(
    allocator: std.mem.Allocator,
    io: std.Io,
    out: *std.Io.Writer,
    argv: []const [:0]const u8,
) !Outcome {
    const app = try createApp(allocator);
    defer {
        app.deinit();
        allocator.destroy(app);
    }

    // Rewrite `-s ""` (empty value) and `-z -10` (negative numeric value)
    // into attached form so yazap captures them (it otherwise skips empty
    // argv elements and treats `-10` as a short option group).
    const argv_norm = try lib.normalizeArgv(allocator, argv, shouldAttach);

    // Empty argv / -h/--help: yazap prints structured help from the command
    // tree (algorithms → modes → options) and exits. Nested helps
    // (`hc md5 -h`, `hc md5 string -h`) use the same path. Diagnostics are
    // redirected to stdout for release parity (see YazapStdoutRedirect).
    const matches = blk: {
        const yazap_out = try YazapStdoutRedirect.begin();
        defer yazap_out.restore();
        break :blk app.parseFrom(io, argv_norm) catch |err| switch (err) {
            error.UnrecognizedCommand => {
                // Yazap already printed "unrecognized command …" to stdout.
                return if (argv_norm.len > 0 and knownAlgorithm(argv_norm[0]))
                    .invalid_command
                else
                    .invalid_options;
            },
            error.SubcommandNotProvided => return .invalid_command,
            error.UnrecognizedOption,
            error.OptionValueNotProvided,
            error.UnexpectedOptionValue,
            error.EmptyOptionValue,
            error.InvalidOptionValue,
            error.TooFewOptionValue,
            error.TooManyOptionValue,
            error.PositionalArgumentNotProvided,
            => return .invalid_options,
            else => return err,
        };
    };

    var algorithm: ?[]const u8 = null;
    var mode_matches: ?ArgMatches = null;
    var mode: ?Mode = null;

    for (hashes.hashes) |h| {
        const algo_m = matches.subcommandMatches(h.name) orelse continue;
        algorithm = h.name;
        inline for (.{
            .{ Mode.string, STRING_CMD },
            .{ Mode.hash, HASH_CMD },
            .{ Mode.file, FILE_CMD },
            .{ Mode.dir, DIR_CMD },
        }) |pair| {
            if (algo_m.subcommandMatches(pair[1])) |mm| {
                mode_matches = mm;
                mode = pair[0];
                break;
            }
        }
        break;
    }

    if (algorithm == null or mode == null or mode_matches == null) {
        return .invalid_command;
    }

    const env: modes.RunEnv = .{
        .io = io,
        .allocator = allocator,
        .out = out,
    };

    const low_case = mode_matches.?.containsArg(opt_lower);
    const hash_def = try modes.builtinInit(algorithm.?, env);

    switch (mode.?) {
        .string => try runString(mode_matches.?, low_case, env, hash_def),
        .hash => try runHash(mode_matches.?, env, app, io, hash_def),
        .file => try runFile(mode_matches.?, low_case, env, hash_def),
        .dir => try runDir(mode_matches.?, low_case, env, hash_def),
    }

    return .ok;
}

// Tests

test "readLengthParam accepts absent and valid bounds" {
    // Arrange
    var buf: [512]u8 = undefined;
    var writer: std.Io.Writer = .fixed(&buf);
    const out = &writer;

    // Act
    const absent = try readLengthParam(out, null, opt_min);
    const valid = try readLengthParam(out, "7", opt_max);

    // Assert — absent keeps the 0 "use mode default" marker; nothing printed.
    try std.testing.expectEqual(@as(i32, 0), absent);
    try std.testing.expectEqual(@as(i32, 7), valid);
    try std.testing.expectEqual(@as(usize, 0), std.Io.Writer.buffered(&writer).len);
}

test "readLengthParam rejects bad -n/-x values with a message" {
    // Arrange — a silent catch-0 reset of the crack bounds is the bug this
    // guards against (cf. --limit/--offset validation).
    var buf: [512]u8 = undefined;
    var writer: std.Io.Writer = .fixed(&buf);
    const out = &writer;

    // Act
    const non_numeric = readLengthParam(out, "abc", opt_min);
    const negative = readLengthParam(out, "-5", opt_max);
    const too_big = readLengthParam(out, "3000000000", opt_max);

    // Assert
    try std.testing.expectError(error.InvalidArgument, non_numeric);
    try std.testing.expectError(error.InvalidArgument, negative);
    try std.testing.expectError(error.InvalidArgument, too_big);
    const got = std.Io.Writer.buffered(&writer);
    try std.testing.expect(std.mem.indexOf(u8, got, "Invalid parameter --min abc. Must be number") != null);
    try std.testing.expect(std.mem.indexOf(u8, got, "Invalid max option must be positive but was -5") != null);
    try std.testing.expect(std.mem.indexOf(u8, got, "Invalid parameter --max 3000000000. Must be a 32-bit number") != null);
}

test "readLengthParam rejects i64 overflow before the 32-bit check" {
    // Arrange
    var buf: [256]u8 = undefined;
    var writer: std.Io.Writer = .fixed(&buf);

    // Act
    const err = readLengthParam(&writer, "18446744073709551615", opt_max);

    // Assert
    try std.testing.expectError(error.InvalidArgument, err);
    const got = std.Io.Writer.buffered(&writer);
    try std.testing.expect(std.mem.indexOf(u8, got, "Must be a 64-bit number") != null);
}

test "readNumberParam rejects overflow with a 64-bit message" {
    // Arrange
    var buf: [256]u8 = undefined;
    var writer: std.Io.Writer = .fixed(&buf);

    // Act
    const err = readNumberParam(&writer, "18446744073709551615", opt_limit, std.math.maxInt(i64));

    // Assert
    try std.testing.expectError(error.InvalidArgument, err);
    const got = std.Io.Writer.buffered(&writer);
    try std.testing.expectEqualStrings(
        "Invalid parameter --limit 18446744073709551615. Must be a 64-bit number\n",
        got,
    );
}

test "resolveThreads reports a negative value as signed" {
    // Arrange — a negative -T must print "-5", not the u32 bitcast 4294967291.
    var buf: [256]u8 = undefined;
    var writer: std.Io.Writer = .fixed(&buf);
    const processors: i32 = @intCast(std.Thread.getCpuCount() catch 1);
    const def: i32 = if (processors == 1) 1 else @divTrunc(processors, 2);

    // Act
    const resolved = resolveThreads(&writer, "-5");

    // Assert
    const got = std.Io.Writer.buffered(&writer);
    try std.testing.expect(std.mem.indexOf(u8, got, "it was set to -5") != null);
    try std.testing.expect(std.mem.indexOf(u8, got, "4294967291") == null);
    try std.testing.expectEqual(def, resolved);
}

test "resolveThreads rejects non-numeric and resets to default" {
    // Arrange
    var buf: [256]u8 = undefined;
    var writer: std.Io.Writer = .fixed(&buf);
    const processors: i32 = @intCast(std.Thread.getCpuCount() catch 1);
    const def: i32 = if (processors == 1) 1 else @divTrunc(processors, 2);

    // Act
    const resolved = resolveThreads(&writer, "not-a-number");

    // Assert — invalid input parses to 0, which still lands in the reset branch.
    const got = std.Io.Writer.buffered(&writer);
    try std.testing.expect(std.mem.indexOf(u8, got, "it was set to 0") != null);
    try std.testing.expectEqual(def, resolved);
}

test "algorithm names are pairwise distinct" {
    for (hashes.hashes, 0..) |a, i| {
        for (hashes.hashes[i + 1 ..]) |b| {
            try std.testing.expect(!std.mem.eql(u8, a.name, b.name));
        }
    }
}

test "isNegativeNumber distinguishes values from options" {
    try std.testing.expect(lib.isNegativeNumber("-10"));
    try std.testing.expect(lib.isNegativeNumber("-10223372036854775808"));
    try std.testing.expect(!lib.isNegativeNumber("10"));
    try std.testing.expect(!lib.isNegativeNumber("--limit"));
    try std.testing.expect(!lib.isNegativeNumber("-l"));
    try std.testing.expect(!lib.isNegativeNumber("-"));
}

test "normalizeArgv attaches empty and negative values" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    {
        const argv = [_][:0]const u8{ "-s", "" };
        const argv_slice: []const [:0]const u8 = &argv;
        const out = try lib.normalizeArgv(allocator, argv_slice, shouldAttach);
        try std.testing.expectEqual(@as(usize, 1), out.len);
        try std.testing.expectEqualStrings("-s=", out[0]);
    }
    {
        const argv = [_][:0]const u8{ "-z", "-10" };
        const argv_slice: []const [:0]const u8 = &argv;
        const out = try lib.normalizeArgv(allocator, argv_slice, shouldAttach);
        try std.testing.expectEqual(@as(usize, 1), out.len);
        try std.testing.expectEqualStrings("-z=-10", out[0]);
    }
    {
        // Positive numbers and normal tokens are untouched.
        const argv = [_][:0]const u8{ "-z", "10", "-s", "abc" };
        const argv_slice: []const [:0]const u8 = &argv;
        const out = try lib.normalizeArgv(allocator, argv_slice, shouldAttach);
        try std.testing.expect(out.ptr == argv_slice.ptr);
    }
}

test "string mode dispatch produces hash output" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var writer = std.Io.Writer.Allocating.init(arena.allocator());
    const out = &writer.writer;

    const argv = [_][:0]const u8{ "tiger", "string", "-s", "abc" };
    const outcome = try run(arena.allocator(), std.testing.io, out, &argv);

    try std.testing.expectEqual(Outcome.ok, outcome);
    const got = writer.written();
    // tiger of "abc" -> known digest, uppercase hex + trailing newline.
    try std.testing.expect(std.mem.indexOf(u8, got, "\n") != null);
    try std.testing.expect(got.len >= 24 * 2);
}

test "unknown command reports invalid command" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var writer = std.Io.Writer.Allocating.init(arena.allocator());
    const out = &writer.writer;

    const argv = [_][:0]const u8{ "tiger", "bogus", "-s", "abc" };
    const outcome = try run(arena.allocator(), std.testing.io, out, &argv);

    try std.testing.expectEqual(Outcome.invalid_command, outcome);
}

test "foreign option on string mode is rejected" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var writer = std.Io.Writer.Allocating.init(arena.allocator());
    const out = &writer.writer;

    const argv = [_][:0]const u8{ "md5", "string", "-s", "abc", "-m", "deadbeef" };
    const outcome = try run(arena.allocator(), std.testing.io, out, &argv);
    try std.testing.expectEqual(Outcome.invalid_options, outcome);
}

test "missing source returns InvalidArgument" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var writer = std.Io.Writer.Allocating.init(arena.allocator());
    const out = &writer.writer;

    // Pass a harmless flag so yazap does not take the help_on_empty_args →
    // process.exit(0) path; we want the mode's own validation.
    const cases = [_][]const [:0]const u8{
        &[_][:0]const u8{ "md5", "string", "-l" },
        &[_][:0]const u8{ "md5", "hash", "--noprobe" },
        &[_][:0]const u8{ "md5", "file", "-t" },
        &[_][:0]const u8{ "md5", "dir", "-t" },
    };
    for (cases) |argv| {
        try std.testing.expectError(
            error.InvalidArgument,
            run(arena.allocator(), std.testing.io, out, argv),
        );
    }
}
