#ifndef HC_OCL_PREFIX_H_
#define HC_OCL_PREFIX_H_
/* Rename public GPU ABI symbols for a prefixed backend build. */

#define gpu_get_props ocl_gpu_get_props
#define gpu_get_device_props ocl_gpu_get_device_props
#define gpu_can_use_gpu ocl_gpu_can_use_gpu
#define gpu_driver_version ocl_gpu_driver_version
#define gpu_runtime_version ocl_gpu_runtime_version
#define gpu_number_to_version ocl_gpu_number_to_version
#define gpu_init_pipeline ocl_gpu_init_pipeline
#define gpu_synchronize ocl_gpu_synchronize
#define gpu_cleanup ocl_gpu_cleanup
#define gpu_run ocl_gpu_run

#define md5_run_on_gpu ocl_md5_run_on_gpu
#define md5_on_gpu_prepare ocl_md5_on_gpu_prepare
#define md2_run_on_gpu ocl_md2_run_on_gpu
#define md2_on_gpu_prepare ocl_md2_on_gpu_prepare
#define md4_run_on_gpu ocl_md4_run_on_gpu
#define md4_on_gpu_prepare ocl_md4_on_gpu_prepare
#define sha1_run_on_gpu ocl_sha1_run_on_gpu
#define sha1_on_gpu_prepare ocl_sha1_on_gpu_prepare
#define sha224_run_on_gpu ocl_sha224_run_on_gpu
#define sha224_on_gpu_prepare ocl_sha224_on_gpu_prepare
#define sha256_run_on_gpu ocl_sha256_run_on_gpu
#define sha256_on_gpu_prepare ocl_sha256_on_gpu_prepare
#define sha384_run_on_gpu ocl_sha384_run_on_gpu
#define sha384_on_gpu_prepare ocl_sha384_on_gpu_prepare
#define sha512_run_on_gpu ocl_sha512_run_on_gpu
#define sha512_on_gpu_prepare ocl_sha512_on_gpu_prepare
#define sha3_224_run_on_gpu ocl_sha3_224_run_on_gpu
#define sha3_224_on_gpu_prepare ocl_sha3_224_on_gpu_prepare
#define sha3_256_run_on_gpu ocl_sha3_256_run_on_gpu
#define sha3_256_on_gpu_prepare ocl_sha3_256_on_gpu_prepare
#define sha3_384_run_on_gpu ocl_sha3_384_run_on_gpu
#define sha3_384_on_gpu_prepare ocl_sha3_384_on_gpu_prepare
#define sha3_512_run_on_gpu ocl_sha3_512_run_on_gpu
#define sha3_512_on_gpu_prepare ocl_sha3_512_on_gpu_prepare
#define keccak_224_run_on_gpu ocl_keccak_224_run_on_gpu
#define keccak_224_on_gpu_prepare ocl_keccak_224_on_gpu_prepare
#define keccak_256_run_on_gpu ocl_keccak_256_run_on_gpu
#define keccak_256_on_gpu_prepare ocl_keccak_256_on_gpu_prepare
#define keccak_384_run_on_gpu ocl_keccak_384_run_on_gpu
#define keccak_384_on_gpu_prepare ocl_keccak_384_on_gpu_prepare
#define keccak_512_run_on_gpu ocl_keccak_512_run_on_gpu
#define keccak_512_on_gpu_prepare ocl_keccak_512_on_gpu_prepare
#define rmd128_run_on_gpu ocl_rmd128_run_on_gpu
#define rmd128_on_gpu_prepare ocl_rmd128_on_gpu_prepare
#define rmd160_run_on_gpu ocl_rmd160_run_on_gpu
#define rmd160_on_gpu_prepare ocl_rmd160_on_gpu_prepare
#define rmd256_run_on_gpu ocl_rmd256_run_on_gpu
#define rmd256_on_gpu_prepare ocl_rmd256_on_gpu_prepare
#define rmd320_run_on_gpu ocl_rmd320_run_on_gpu
#define rmd320_on_gpu_prepare ocl_rmd320_on_gpu_prepare
#define blake2s_run_on_gpu ocl_blake2s_run_on_gpu
#define blake2s_on_gpu_prepare ocl_blake2s_on_gpu_prepare
#define blake2b_run_on_gpu ocl_blake2b_run_on_gpu
#define blake2b_on_gpu_prepare ocl_blake2b_on_gpu_prepare
#define tiger_run_on_gpu ocl_tiger_run_on_gpu
#define tiger_on_gpu_prepare ocl_tiger_on_gpu_prepare
#define tiger2_run_on_gpu ocl_tiger2_run_on_gpu
#define tiger2_on_gpu_prepare ocl_tiger2_on_gpu_prepare
#define whirl_run_on_gpu ocl_whirl_run_on_gpu
#define whirl_on_gpu_prepare ocl_whirl_on_gpu_prepare
#define crc32_run_on_gpu ocl_crc32_run_on_gpu
#define crc32_on_gpu_prepare ocl_crc32_on_gpu_prepare

#endif /* HC_OCL_PREFIX_H_ */
