/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : C:\\hg\\hc\\src\\hlinq\\HLINQ.g
 *     -                            On : 2011-11-18 09:19:31
 *     -                for the parser : HLINQParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

   #include "compiler.h"

/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "HLINQParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pHLINQParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pHLINQParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pHLINQParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pHLINQParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */

/* ruleAttributeScopeFuncDecl(scope)
 */
/* -----------------------------------------------------------------------------
 * Function declarations for creating a HLINQParser_statement scope set
 */
static pHLINQParser_statement_SCOPE   pHLINQParser_statementPush(pHLINQParser ctx);
static void ANTLR3_CDECL statementFree(pHLINQParser_statement_SCOPE scope);
/* ----------------------------------------------------------------------------- */


/* ruleAttributeScopeFuncs(scope)
 */
/* attributeFuncs(scope)
 */

static void ANTLR3_CDECL statementFree(pHLINQParser_statement_SCOPE scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Allocate initial memory for a HLINQParser statement scope variable stack entry and
 *         add it to the top of the stack.
 *
 * \remark
 * By default the structure is freed with ANTLR_FREE(), but you can use the
 * the \@init action to install a pointer to a custom free() routine by
 * adding the code:
 * \code
 *   ctx->pHLINQParser_statementTop->free = myroutine;
 * \endcode
 *
 * With lots of comments of course! The routine should be declared in
 * \@members { } as:
 * \code
 *   void ANTLR3_CDECL myfunc( pHLINQParser_statement_SCOPE ptr).
 * \endcode
 *
 * It should perform any custom freeing stuff that you need (call ANTLR_FREE3, not free()
 * NB: It should not free the pointer it is given, which is the scope stack entry itself
 * and will be freed by the function that calls your custom free routine.
 *
 */
static pHLINQParser_statement_SCOPE
pHLINQParser_statementPush(pHLINQParser ctx)
{
    /* Pointer used to create a new set of attributes
     */
    pHLINQParser_statement_SCOPE      newAttributes;

    /* Allocate the memory for a new structure if we need one.
     */
    if (ctx->pHLINQParser_statementStack->size(ctx->pHLINQParser_statementStack) > ctx->pHLINQParser_statementStack_limit)
    {
        // The current limit value was less than the number of scopes available on the stack so
        // we can just reuse one. Our limit tracks the stack count, so the index of the entry we want
        // is one less than that, or conveniently, the current value of limit.
        //
        newAttributes = (pHLINQParser_statement_SCOPE)ctx->pHLINQParser_statementStack->get(ctx->pHLINQParser_statementStack, ctx->pHLINQParser_statementStack_limit);
    }
    else
    {
        // Need a new allocation
        //
        newAttributes = (pHLINQParser_statement_SCOPE) ANTLR3_MALLOC(sizeof(HLINQParser_statement_SCOPE));
        if  (newAttributes != NULL)
        {
            /* Standard ANTLR3 library implementation
             */
            ctx->pHLINQParser_statementStack->push(ctx->pHLINQParser_statementStack, newAttributes, (void (*)(void *))statementFree);
        }
    }

    // Blank out any previous free pointer, the user might or might install a new one.
    //
    newAttributes->free = NULL;

    // Indicate the position in the available stack that the current level is at
    //
    ctx->pHLINQParser_statementStack_limit++;

	/* Return value is the pointer to the new entry, which may be used locally
	 * without de-referencing via the context.
     */
    return  newAttributes;
}







/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   HLINQParserTokenNames[41+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "AND",
        (pANTLR3_UINT8) "COMMENT",
        (pANTLR3_UINT8) "COND_OP",
        (pANTLR3_UINT8) "COND_OP_INT",
        (pANTLR3_UINT8) "COND_OP_STR",
        (pANTLR3_UINT8) "DO",
        (pANTLR3_UINT8) "ECHAR",
        (pANTLR3_UINT8) "EOL",
        (pANTLR3_UINT8) "EQUAL",
        (pANTLR3_UINT8) "FOR",
        (pANTLR3_UINT8) "GE",
        (pANTLR3_UINT8) "HASH",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "ID_PART",
        (pANTLR3_UINT8) "ID_START",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "LE",
        (pANTLR3_UINT8) "MATCH",
        (pANTLR3_UINT8) "NEWLINE",
        (pANTLR3_UINT8) "NOT",
        (pANTLR3_UINT8) "OR",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "STRING",
        (pANTLR3_UINT8) "STRING1",
        (pANTLR3_UINT8) "STRING2",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "','",
        (pANTLR3_UINT8) "'.'",
        (pANTLR3_UINT8) "'copy'",
        (pANTLR3_UINT8) "'crack'",
        (pANTLR3_UINT8) "'delete'",
        (pANTLR3_UINT8) "'in'",
        (pANTLR3_UINT8) "'let'",
        (pANTLR3_UINT8) "'limit'",
        (pANTLR3_UINT8) "'move'",
        (pANTLR3_UINT8) "'name'",
        (pANTLR3_UINT8) "'offset'",
        (pANTLR3_UINT8) "'print'",
        (pANTLR3_UINT8) "'recursively'",
        (pANTLR3_UINT8) "'size'",
        (pANTLR3_UINT8) "'where'"
       };


/* ruleAttributeScopeFuncMacro(scope)
 */
/** Function for popping the top value from a pHLINQParser_statementStack
 */
void
pHLINQParser_statementPop(pHLINQParser ctx)
{
    // First see if the user defined a function they want to be called when a
    // scope is popped/freed.
    //
	// If the user supplied the scope entries with a free function,then call it first
	//
    if	(SCOPE_TOP(statement)->free != NULL)
	{
        SCOPE_TOP(statement)->free(SCOPE_TOP(statement));
	}

    // Now we decrement the scope's upper limit bound. We do not actually pop the scope as
    // we want to reuse scope entries if we do continuous push and pops. Most scopes don't
    // next too far so we don't want to keep freeing and allocating them
    //
    ctx->pHLINQParser_statementStack_limit--;
    SCOPE_TOP(statement) = (pHLINQParser_statement_SCOPE)(ctx->pHLINQParser_statementStack->get(ctx->pHLINQParser_statementStack, ctx->pHLINQParser_statementStack_limit - 1));
}



// Forward declare the locally static matching functions we have generated.
//
static 
 void
	prog    (pHLINQParser ctx, apr_pool_t* root);
static 
 void
	statement    (pHLINQParser ctx);
static 
 void
	expr    (pHLINQParser ctx);
static 
 void
	identifier    (pHLINQParser ctx);
static 
 void
	recursively    (pHLINQParser ctx);
static 
 void
	do_clause_file    (pHLINQParser ctx);
static 
 void
	do_clause_string    (pHLINQParser ctx);
static 
 void
	print_clause    (pHLINQParser ctx);
static 
 void
	print    (pHLINQParser ctx);
static 
 void
	attr_clause    (pHLINQParser ctx);
static 
 void
	attr    (pHLINQParser ctx);
static 
 void
	delete_clause    (pHLINQParser ctx);
static 
 void
	copy_clause    (pHLINQParser ctx);
static 
 void
	move_clause    (pHLINQParser ctx);
static 
 void
	hash_clause    (pHLINQParser ctx);
static 
 void
	brute_force_clause    (pHLINQParser ctx);
static 
 void
	let_clause    (pHLINQParser ctx);
static 
 void
	where_clause    (pHLINQParser ctx);
static 
 void
	boolean_expression    (pHLINQParser ctx);
static 
 void
	conditional_or_expression    (pHLINQParser ctx);
static 
 void
	conditional_and_expression    (pHLINQParser ctx);
static 
 void
	exclusive_or_expression    (pHLINQParser ctx);
static 
 void
	str_attr    (pHLINQParser ctx);
static 
 void
	int_attr    (pHLINQParser ctx);
static void	HLINQParserFree(pHLINQParser ctx);
static void     HLINQParserReset (pHLINQParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "C:\\hg\\hc\\src\\hlinq\\HLINQ.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new HLINQParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pHLINQParser
HLINQParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return HLINQParserNewSSD(instream, NULL);
}

/** \brief Create a new HLINQParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pHLINQParser
HLINQParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pHLINQParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pHLINQParser) ANTLR3_CALLOC(1, sizeof(HLINQParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in HLINQParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our HLINQParser interface
     */
    ctx->prog	= prog;
    ctx->statement	= statement;
    ctx->expr	= expr;
    ctx->identifier	= identifier;
    ctx->recursively	= recursively;
    ctx->do_clause_file	= do_clause_file;
    ctx->do_clause_string	= do_clause_string;
    ctx->print_clause	= print_clause;
    ctx->print	= print;
    ctx->attr_clause	= attr_clause;
    ctx->attr	= attr;
    ctx->delete_clause	= delete_clause;
    ctx->copy_clause	= copy_clause;
    ctx->move_clause	= move_clause;
    ctx->hash_clause	= hash_clause;
    ctx->brute_force_clause	= brute_force_clause;
    ctx->let_clause	= let_clause;
    ctx->where_clause	= where_clause;
    ctx->boolean_expression	= boolean_expression;
    ctx->conditional_or_expression	= conditional_or_expression;
    ctx->conditional_and_expression	= conditional_and_expression;
    ctx->exclusive_or_expression	= exclusive_or_expression;
    ctx->str_attr	= str_attr;
    ctx->int_attr	= int_attr;
    ctx->free			= HLINQParserFree;
    ctx->reset			= HLINQParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
    /* ruleAttributeScope(scope)
     */
    ctx->pHLINQParser_statementPush     = pHLINQParser_statementPush;
    ctx->pHLINQParser_statementStack    = antlr3StackNew(0);
    ctx->pHLINQParser_statementStack_limit    = 0;
    ctx->pHLINQParser_statementTop      = NULL;




    /* Install the token table
     */
    PSRSTATE->tokenNames   = HLINQParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
HLINQParserReset (pHLINQParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 HLINQParserFree(pHLINQParser ctx)
 {
    /* Free any scope memory
     */
    /* ruleAttributeScope(scope)
     */
    ctx->pHLINQParser_statementStack->free(ctx->pHLINQParser_statementStack);



	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return HLINQParserTokenNames;
}





/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_statement_in_prog70  */
static	ANTLR3_BITWORD FOLLOW_statement_in_prog70_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000402002) };
static  ANTLR3_BITSET_LIST FOLLOW_statement_in_prog70	= { FOLLOW_statement_in_prog70_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_statement108  */
static	ANTLR3_BITWORD FOLLOW_expr_in_statement108_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_statement108	= { FOLLOW_expr_in_statement108_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_statement110  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_statement110_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_statement110	= { FOLLOW_NEWLINE_in_statement110_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_statement116  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_statement116_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_statement116	= { FOLLOW_NEWLINE_in_statement116_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FOR_in_expr132  */
static	ANTLR3_BITWORD FOLLOW_FOR_in_expr132_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_FOR_in_expr132	= { FOLLOW_FOR_in_expr132_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_identifier_in_expr134  */
static	ANTLR3_BITWORD FOLLOW_identifier_in_expr134_bits[]	= { ANTLR3_UINT64_LIT(0x0000000800000000) };
static  ANTLR3_BITSET_LIST FOLLOW_identifier_in_expr134	= { FOLLOW_identifier_in_expr134_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_35_in_expr136  */
static	ANTLR3_BITWORD FOLLOW_35_in_expr136_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004000000) };
static  ANTLR3_BITSET_LIST FOLLOW_35_in_expr136	= { FOLLOW_35_in_expr136_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_expr140  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_expr140_bits[]	= { ANTLR3_UINT64_LIT(0x0000141000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_expr140	= { FOLLOW_STRING_in_expr140_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_recursively_in_expr143  */
static	ANTLR3_BITWORD FOLLOW_recursively_in_expr143_bits[]	= { ANTLR3_UINT64_LIT(0x0000101000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_recursively_in_expr143	= { FOLLOW_recursively_in_expr143_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_let_clause_in_expr148  */
static	ANTLR3_BITWORD FOLLOW_let_clause_in_expr148_bits[]	= { ANTLR3_UINT64_LIT(0x0000100000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_let_clause_in_expr148	= { FOLLOW_let_clause_in_expr148_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_where_clause_in_expr153  */
static	ANTLR3_BITWORD FOLLOW_where_clause_in_expr153_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_where_clause_in_expr153	= { FOLLOW_where_clause_in_expr153_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_do_clause_file_in_expr157  */
static	ANTLR3_BITWORD FOLLOW_do_clause_file_in_expr157_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_do_clause_file_in_expr157	= { FOLLOW_do_clause_file_in_expr157_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FOR_in_expr169  */
static	ANTLR3_BITWORD FOLLOW_FOR_in_expr169_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004000000) };
static  ANTLR3_BITSET_LIST FOLLOW_FOR_in_expr169	= { FOLLOW_FOR_in_expr169_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_expr173  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_expr173_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_expr173	= { FOLLOW_STRING_in_expr173_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_do_clause_string_in_expr175  */
static	ANTLR3_BITWORD FOLLOW_do_clause_string_in_expr175_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_do_clause_string_in_expr175	= { FOLLOW_do_clause_string_in_expr175_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_identifier194  */
static	ANTLR3_BITWORD FOLLOW_ID_in_identifier194_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_identifier194	= { FOLLOW_ID_in_identifier194_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_42_in_recursively208  */
static	ANTLR3_BITWORD FOLLOW_42_in_recursively208_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_42_in_recursively208	= { FOLLOW_42_in_recursively208_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DO_in_do_clause_file234  */
static	ANTLR3_BITWORD FOLLOW_DO_in_do_clause_file234_bits[]	= { ANTLR3_UINT64_LIT(0x0000024500008000) };
static  ANTLR3_BITSET_LIST FOLLOW_DO_in_do_clause_file234	= { FOLLOW_DO_in_do_clause_file234_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_print_clause_in_do_clause_file237  */
static	ANTLR3_BITWORD FOLLOW_print_clause_in_do_clause_file237_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_print_clause_in_do_clause_file237	= { FOLLOW_print_clause_in_do_clause_file237_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_delete_clause_in_do_clause_file241  */
static	ANTLR3_BITWORD FOLLOW_delete_clause_in_do_clause_file241_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_delete_clause_in_do_clause_file241	= { FOLLOW_delete_clause_in_do_clause_file241_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_copy_clause_in_do_clause_file245  */
static	ANTLR3_BITWORD FOLLOW_copy_clause_in_do_clause_file245_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_copy_clause_in_do_clause_file245	= { FOLLOW_copy_clause_in_do_clause_file245_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_move_clause_in_do_clause_file249  */
static	ANTLR3_BITWORD FOLLOW_move_clause_in_do_clause_file249_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_move_clause_in_do_clause_file249	= { FOLLOW_move_clause_in_do_clause_file249_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_hash_clause_in_do_clause_file253  */
static	ANTLR3_BITWORD FOLLOW_hash_clause_in_do_clause_file253_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_hash_clause_in_do_clause_file253	= { FOLLOW_hash_clause_in_do_clause_file253_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DO_in_do_clause_string266  */
static	ANTLR3_BITWORD FOLLOW_DO_in_do_clause_string266_bits[]	= { ANTLR3_UINT64_LIT(0x0000000200008000) };
static  ANTLR3_BITSET_LIST FOLLOW_DO_in_do_clause_string266	= { FOLLOW_DO_in_do_clause_string266_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_hash_clause_in_do_clause_string269  */
static	ANTLR3_BITWORD FOLLOW_hash_clause_in_do_clause_string269_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_hash_clause_in_do_clause_string269	= { FOLLOW_hash_clause_in_do_clause_string269_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_brute_force_clause_in_do_clause_string272  */
static	ANTLR3_BITWORD FOLLOW_brute_force_clause_in_do_clause_string272_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_brute_force_clause_in_do_clause_string272	= { FOLLOW_brute_force_clause_in_do_clause_string272_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_41_in_print_clause288  */
static	ANTLR3_BITWORD FOLLOW_41_in_print_clause288_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004090000) };
static  ANTLR3_BITSET_LIST FOLLOW_41_in_print_clause288	= { FOLLOW_41_in_print_clause288_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_print_in_print_clause290  */
static	ANTLR3_BITWORD FOLLOW_print_in_print_clause290_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002000002) };
static  ANTLR3_BITSET_LIST FOLLOW_print_in_print_clause290	= { FOLLOW_print_in_print_clause290_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_print_clause293  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_print_clause293_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004090000) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_print_clause293	= { FOLLOW_PLUS_in_print_clause293_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_print_in_print_clause295  */
static	ANTLR3_BITWORD FOLLOW_print_in_print_clause295_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002000002) };
static  ANTLR3_BITSET_LIST FOLLOW_print_in_print_clause295	= { FOLLOW_print_in_print_clause295_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attr_clause_in_print314  */
static	ANTLR3_BITWORD FOLLOW_attr_clause_in_print314_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_attr_clause_in_print314	= { FOLLOW_attr_clause_in_print314_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_print318  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_print318_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_print318	= { FOLLOW_STRING_in_print318_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_print322  */
static	ANTLR3_BITWORD FOLLOW_INT_in_print322_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_print322	= { FOLLOW_INT_in_print322_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_attr_clause335  */
static	ANTLR3_BITWORD FOLLOW_ID_in_attr_clause335_bits[]	= { ANTLR3_UINT64_LIT(0x0000000080000000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_attr_clause335	= { FOLLOW_ID_in_attr_clause335_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_31_in_attr_clause337  */
static	ANTLR3_BITWORD FOLLOW_31_in_attr_clause337_bits[]	= { ANTLR3_UINT64_LIT(0x000009A000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_31_in_attr_clause337	= { FOLLOW_31_in_attr_clause337_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attr_in_attr_clause339  */
static	ANTLR3_BITWORD FOLLOW_attr_in_attr_clause339_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_attr_in_attr_clause339	= { FOLLOW_attr_in_attr_clause339_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_str_attr_in_attr363  */
static	ANTLR3_BITWORD FOLLOW_str_attr_in_attr363_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_str_attr_in_attr363	= { FOLLOW_str_attr_in_attr363_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_int_attr_in_attr367  */
static	ANTLR3_BITWORD FOLLOW_int_attr_in_attr367_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_int_attr_in_attr367	= { FOLLOW_int_attr_in_attr367_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_34_in_delete_clause385  */
static	ANTLR3_BITWORD FOLLOW_34_in_delete_clause385_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_34_in_delete_clause385	= { FOLLOW_34_in_delete_clause385_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_32_in_copy_clause401  */
static	ANTLR3_BITWORD FOLLOW_32_in_copy_clause401_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004000000) };
static  ANTLR3_BITSET_LIST FOLLOW_32_in_copy_clause401	= { FOLLOW_32_in_copy_clause401_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_copy_clause405  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_copy_clause405_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_copy_clause405	= { FOLLOW_STRING_in_copy_clause405_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_38_in_move_clause422  */
static	ANTLR3_BITWORD FOLLOW_38_in_move_clause422_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004000000) };
static  ANTLR3_BITSET_LIST FOLLOW_38_in_move_clause422	= { FOLLOW_38_in_move_clause422_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_move_clause426  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_move_clause426_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_move_clause426	= { FOLLOW_STRING_in_move_clause426_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_HASH_in_hash_clause443  */
static	ANTLR3_BITWORD FOLLOW_HASH_in_hash_clause443_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_HASH_in_hash_clause443	= { FOLLOW_HASH_in_hash_clause443_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_33_in_brute_force_clause461  */
static	ANTLR3_BITWORD FOLLOW_33_in_brute_force_clause461_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_33_in_brute_force_clause461	= { FOLLOW_33_in_brute_force_clause461_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_HASH_in_brute_force_clause463  */
static	ANTLR3_BITWORD FOLLOW_HASH_in_brute_force_clause463_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_HASH_in_brute_force_clause463	= { FOLLOW_HASH_in_brute_force_clause463_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_36_in_let_clause473  */
static	ANTLR3_BITWORD FOLLOW_36_in_let_clause473_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_36_in_let_clause473	= { FOLLOW_36_in_let_clause473_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_exclusive_or_expression_in_let_clause475  */
static	ANTLR3_BITWORD FOLLOW_exclusive_or_expression_in_let_clause475_bits[]	= { ANTLR3_UINT64_LIT(0x0000000040000002) };
static  ANTLR3_BITSET_LIST FOLLOW_exclusive_or_expression_in_let_clause475	= { FOLLOW_exclusive_or_expression_in_let_clause475_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_30_in_let_clause478  */
static	ANTLR3_BITWORD FOLLOW_30_in_let_clause478_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_30_in_let_clause478	= { FOLLOW_30_in_let_clause478_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_exclusive_or_expression_in_let_clause480  */
static	ANTLR3_BITWORD FOLLOW_exclusive_or_expression_in_let_clause480_bits[]	= { ANTLR3_UINT64_LIT(0x0000000040000002) };
static  ANTLR3_BITSET_LIST FOLLOW_exclusive_or_expression_in_let_clause480	= { FOLLOW_exclusive_or_expression_in_let_clause480_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_44_in_where_clause495  */
static	ANTLR3_BITWORD FOLLOW_44_in_where_clause495_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_44_in_where_clause495	= { FOLLOW_44_in_where_clause495_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_boolean_expression_in_where_clause497  */
static	ANTLR3_BITWORD FOLLOW_boolean_expression_in_where_clause497_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_boolean_expression_in_where_clause497	= { FOLLOW_boolean_expression_in_where_clause497_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_conditional_or_expression_in_boolean_expression510  */
static	ANTLR3_BITWORD FOLLOW_conditional_or_expression_in_boolean_expression510_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_conditional_or_expression_in_boolean_expression510	= { FOLLOW_conditional_or_expression_in_boolean_expression510_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_conditional_and_expression_in_conditional_or_expression518  */
static	ANTLR3_BITWORD FOLLOW_conditional_and_expression_in_conditional_or_expression518_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001000002) };
static  ANTLR3_BITSET_LIST FOLLOW_conditional_and_expression_in_conditional_or_expression518	= { FOLLOW_conditional_and_expression_in_conditional_or_expression518_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_OR_in_conditional_or_expression522  */
static	ANTLR3_BITWORD FOLLOW_OR_in_conditional_or_expression522_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_OR_in_conditional_or_expression522	= { FOLLOW_OR_in_conditional_or_expression522_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_conditional_and_expression_in_conditional_or_expression524  */
static	ANTLR3_BITWORD FOLLOW_conditional_and_expression_in_conditional_or_expression524_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001000002) };
static  ANTLR3_BITSET_LIST FOLLOW_conditional_and_expression_in_conditional_or_expression524	= { FOLLOW_conditional_and_expression_in_conditional_or_expression524_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_exclusive_or_expression_in_conditional_and_expression535  */
static	ANTLR3_BITWORD FOLLOW_exclusive_or_expression_in_conditional_and_expression535_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000012) };
static  ANTLR3_BITSET_LIST FOLLOW_exclusive_or_expression_in_conditional_and_expression535	= { FOLLOW_exclusive_or_expression_in_conditional_and_expression535_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_AND_in_conditional_and_expression540  */
static	ANTLR3_BITWORD FOLLOW_AND_in_conditional_and_expression540_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_AND_in_conditional_and_expression540	= { FOLLOW_AND_in_conditional_and_expression540_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_exclusive_or_expression_in_conditional_and_expression542  */
static	ANTLR3_BITWORD FOLLOW_exclusive_or_expression_in_conditional_and_expression542_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000012) };
static  ANTLR3_BITSET_LIST FOLLOW_exclusive_or_expression_in_conditional_and_expression542	= { FOLLOW_exclusive_or_expression_in_conditional_and_expression542_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_exclusive_or_expression553  */
static	ANTLR3_BITWORD FOLLOW_ID_in_exclusive_or_expression553_bits[]	= { ANTLR3_UINT64_LIT(0x0000000080000000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_exclusive_or_expression553	= { FOLLOW_ID_in_exclusive_or_expression553_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_31_in_exclusive_or_expression555  */
static	ANTLR3_BITWORD FOLLOW_31_in_exclusive_or_expression555_bits[]	= { ANTLR3_UINT64_LIT(0x000009A000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_31_in_exclusive_or_expression555	= { FOLLOW_31_in_exclusive_or_expression555_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_str_attr_in_exclusive_or_expression559  */
static	ANTLR3_BITWORD FOLLOW_str_attr_in_exclusive_or_expression559_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000140) };
static  ANTLR3_BITSET_LIST FOLLOW_str_attr_in_exclusive_or_expression559	= { FOLLOW_str_attr_in_exclusive_or_expression559_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_exclusive_or_expression561  */
static	ANTLR3_BITWORD FOLLOW_set_in_exclusive_or_expression561_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004000000) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_exclusive_or_expression561	= { FOLLOW_set_in_exclusive_or_expression561_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_exclusive_or_expression569  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_exclusive_or_expression569_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_exclusive_or_expression569	= { FOLLOW_STRING_in_exclusive_or_expression569_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_int_attr_in_exclusive_or_expression575  */
static	ANTLR3_BITWORD FOLLOW_int_attr_in_exclusive_or_expression575_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000000C0) };
static  ANTLR3_BITSET_LIST FOLLOW_int_attr_in_exclusive_or_expression575	= { FOLLOW_int_attr_in_exclusive_or_expression575_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_exclusive_or_expression577  */
static	ANTLR3_BITWORD FOLLOW_set_in_exclusive_or_expression577_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080000) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_exclusive_or_expression577	= { FOLLOW_set_in_exclusive_or_expression577_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_exclusive_or_expression585  */
static	ANTLR3_BITWORD FOLLOW_INT_in_exclusive_or_expression585_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_exclusive_or_expression585	= { FOLLOW_INT_in_exclusive_or_expression585_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start prog
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:33:1: prog[apr_pool_t* root] : ( statement )+ ;
 */
static void
prog(pHLINQParser ctx, apr_pool_t* root)
{
    /* Initialize rule variables
     */

     InitProgram(root); 
    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:35:2: ( ( statement )+ )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:35:4: ( statement )+
        {
            // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:35:4: ( statement )+
            {
                int cnt1=0;

                for (;;)
                {
                    int alt1=2;
            	switch ( LA(1) )
            	{
            	case FOR:
            	case NEWLINE:
            		{
            			alt1=1;
            		}
            	    break;

            	}

            	switch (alt1)
            	{
            	    case 1:
            	        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:35:4: statement
            	        {
            	            FOLLOWPUSH(FOLLOW_statement_in_prog70);
            	            statement(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleprogEx;
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt1 >= 1 )
            		{
            		    goto loop1;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleprogEx;
            	}
            	cnt1++;
                }
                loop1: ;	/* Jump to here if this rule does not match */
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprogEx; /* Prevent compiler warnings */
    ruleprogEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end prog */

/**
 * $ANTLR start statement
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:39:1: statement : ( expr NEWLINE | NEWLINE );
 */
static void
statement(pHLINQParser ctx)
{
    /* Initialize rule variables
     */
    ctx->pHLINQParser_statementTop = pHLINQParser_statementPush(ctx);

    	OpenStatement(); 

    {
        {
            //  C:\\hg\\hc\\src\\hlinq\\HLINQ.g:49:5: ( expr NEWLINE | NEWLINE )

            ANTLR3_UINT32 alt2;

            alt2=2;

            switch ( LA(1) )
            {
            case FOR:
            	{
            		alt2=1;
            	}
                break;
            case NEWLINE:
            	{
            		alt2=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto rulestatementEx;

            }

            switch (alt2)
            {
        	case 1:
        	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:49:9: expr NEWLINE
        	    {
        	        FOLLOWPUSH(FOLLOW_expr_in_statement108);
        	        expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }


        	         MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_statement110);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:49:26: NEWLINE
        	    {
        	         MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_statement116);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulestatementEx; /* Prevent compiler warnings */
    rulestatementEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {

                    	CloseStatement((SCOPE_TOP(statement))->id);

                }
            }


    pHLINQParser_statementPop(ctx);

    return ;
}
/* $ANTLR end statement */

/**
 * $ANTLR start expr
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:52:1: expr : ( FOR identifier 'in' searchIn= STRING ( recursively )? ( let_clause )? ( where_clause )? do_clause_file | FOR s= STRING do_clause_string );
 */
static void
expr(pHLINQParser ctx)
{
    pANTLR3_COMMON_TOKEN    searchIn;
    pANTLR3_COMMON_TOKEN    s;

    /* Initialize rule variables
     */

    searchIn       = NULL;
    s       = NULL;

    {
        {
            //  C:\\hg\\hc\\src\\hlinq\\HLINQ.g:52:5: ( FOR identifier 'in' searchIn= STRING ( recursively )? ( let_clause )? ( where_clause )? do_clause_file | FOR s= STRING do_clause_string )

            ANTLR3_UINT32 alt6;

            alt6=2;

            switch ( LA(1) )
            {
            case FOR:
            	{
            		switch ( LA(2) )
            		{
            		case STRING:
            			{
            				alt6=2;
            			}
            		    break;
            		case ID:
            			{
            				alt6=1;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 6;
            		    EXCEPTION->state        = 1;


            		    goto ruleexprEx;

            		}

            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 6;
                EXCEPTION->state        = 0;


                goto ruleexprEx;

            }

            switch (alt6)
            {
        	case 1:
        	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:53:5: FOR identifier 'in' searchIn= STRING ( recursively )? ( let_clause )? ( where_clause )? do_clause_file
        	    {
        	         MATCHT(FOR, &FOLLOW_FOR_in_expr132);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_identifier_in_expr134);
        	        identifier(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	         MATCHT(35, &FOLLOW_35_in_expr136);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        searchIn = (pANTLR3_COMMON_TOKEN) MATCHT(STRING, &FOLLOW_STRING_in_expr140);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:53:41: ( recursively )?
        	        {
        	            int alt3=2;
        	            switch ( LA(1) )
        	            {
        	                case 42:
        	                	{
        	                		alt3=1;
        	                	}
        	                    break;
        	            }

        	            switch (alt3)
        	            {
        	        	case 1:
        	        	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:53:42: recursively
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_recursively_in_expr143);
        	        	        recursively(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleexprEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }

        	        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:53:56: ( let_clause )?
        	        {
        	            int alt4=2;
        	            switch ( LA(1) )
        	            {
        	                case 36:
        	                	{
        	                		alt4=1;
        	                	}
        	                    break;
        	            }

        	            switch (alt4)
        	            {
        	        	case 1:
        	        	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:53:57: let_clause
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_let_clause_in_expr148);
        	        	        let_clause(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleexprEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }

        	        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:53:70: ( where_clause )?
        	        {
        	            int alt5=2;
        	            switch ( LA(1) )
        	            {
        	                case 44:
        	                	{
        	                		alt5=1;
        	                	}
        	                    break;
        	            }

        	            switch (alt5)
        	            {
        	        	case 1:
        	        	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:53:71: where_clause
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_where_clause_in_expr153);
        	        	        where_clause(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleexprEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }

        	        FOLLOWPUSH(FOLLOW_do_clause_file_in_expr157);
        	        do_clause_file(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        {

        	            		SetSearchRoot((searchIn->getText(searchIn))->chars, (SCOPE_TOP(statement))->id);
        	            	
        	        }


        	    }
        	    break;
        	case 2:
        	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:58:2: FOR s= STRING do_clause_string
        	    {
        	         MATCHT(FOR, &FOLLOW_FOR_in_expr169);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        s = (pANTLR3_COMMON_TOKEN) MATCHT(STRING, &FOLLOW_STRING_in_expr173);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_do_clause_string_in_expr175);
        	        do_clause_string(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end expr */

/**
 * $ANTLR start identifier
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:61:1: identifier : ID ;
 */
static void
identifier(pHLINQParser ctx)
{
    pANTLR3_COMMON_TOKEN    ID1;

    /* Initialize rule variables
     */

    ID1       = NULL;

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:62:2: ( ID )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:62:4: ID
        {
            ID1 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_identifier194);
            if  (HASEXCEPTION())
            {
                goto ruleidentifierEx;
            }


            {

                		(SCOPE_TOP(statement))->id= (const char*)(ID1->getText(ID1))->chars;
                		CreateStatementContext((SCOPE_TOP(statement))->id);
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleidentifierEx; /* Prevent compiler warnings */
    ruleidentifierEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end identifier */

/**
 * $ANTLR start recursively
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:68:1: recursively : 'recursively' ;
 */
static void
recursively(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:68:12: ( 'recursively' )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:69:5: 'recursively'
        {
             MATCHT(42, &FOLLOW_42_in_recursively208);
            if  (HASEXCEPTION())
            {
                goto rulerecursivelyEx;
            }


            {

                    	SetRecursively((SCOPE_TOP(statement))->id);
                    
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulerecursivelyEx; /* Prevent compiler warnings */
    rulerecursivelyEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end recursively */

/**
 * $ANTLR start do_clause_file
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:75:1: do_clause_file : DO ( print_clause | delete_clause | copy_clause | move_clause | hash_clause ) ;
 */
static void
do_clause_file(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:75:15: ( DO ( print_clause | delete_clause | copy_clause | move_clause | hash_clause ) )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:76:5: DO ( print_clause | delete_clause | copy_clause | move_clause | hash_clause )
        {
             MATCHT(DO, &FOLLOW_DO_in_do_clause_file234);
            if  (HASEXCEPTION())
            {
                goto ruledo_clause_fileEx;
            }


            // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:76:8: ( print_clause | delete_clause | copy_clause | move_clause | hash_clause )
            {
                int alt7=5;
                switch ( LA(1) )
                {
                case 41:
                	{
                		alt7=1;
                	}
                    break;
                case 34:
                	{
                		alt7=2;
                	}
                    break;
                case 32:
                	{
                		alt7=3;
                	}
                    break;
                case 38:
                	{
                		alt7=4;
                	}
                    break;
                case HASH:
                	{
                		alt7=5;
                	}
                    break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 7;
                    EXCEPTION->state        = 0;


                    goto ruledo_clause_fileEx;

                }

                switch (alt7)
                {
            	case 1:
            	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:76:9: print_clause
            	    {
            	        FOLLOWPUSH(FOLLOW_print_clause_in_do_clause_file237);
            	        print_clause(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledo_clause_fileEx;
            	        }


            	    }
            	    break;
            	case 2:
            	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:76:24: delete_clause
            	    {
            	        FOLLOWPUSH(FOLLOW_delete_clause_in_do_clause_file241);
            	        delete_clause(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledo_clause_fileEx;
            	        }


            	    }
            	    break;
            	case 3:
            	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:76:40: copy_clause
            	    {
            	        FOLLOWPUSH(FOLLOW_copy_clause_in_do_clause_file245);
            	        copy_clause(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledo_clause_fileEx;
            	        }


            	    }
            	    break;
            	case 4:
            	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:76:54: move_clause
            	    {
            	        FOLLOWPUSH(FOLLOW_move_clause_in_do_clause_file249);
            	        move_clause(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledo_clause_fileEx;
            	        }


            	    }
            	    break;
            	case 5:
            	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:76:68: hash_clause
            	    {
            	        FOLLOWPUSH(FOLLOW_hash_clause_in_do_clause_file253);
            	        hash_clause(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledo_clause_fileEx;
            	        }


            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruledo_clause_fileEx; /* Prevent compiler warnings */
    ruledo_clause_fileEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end do_clause_file */

/**
 * $ANTLR start do_clause_string
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:78:1: do_clause_string : DO ( hash_clause | brute_force_clause ) ;
 */
static void
do_clause_string(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:78:17: ( DO ( hash_clause | brute_force_clause ) )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:79:2: DO ( hash_clause | brute_force_clause )
        {
             MATCHT(DO, &FOLLOW_DO_in_do_clause_string266);
            if  (HASEXCEPTION())
            {
                goto ruledo_clause_stringEx;
            }


            // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:79:5: ( hash_clause | brute_force_clause )
            {
                int alt8=2;
                switch ( LA(1) )
                {
                case HASH:
                	{
                		alt8=1;
                	}
                    break;
                case 33:
                	{
                		alt8=2;
                	}
                    break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 8;
                    EXCEPTION->state        = 0;


                    goto ruledo_clause_stringEx;

                }

                switch (alt8)
                {
            	case 1:
            	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:79:6: hash_clause
            	    {
            	        FOLLOWPUSH(FOLLOW_hash_clause_in_do_clause_string269);
            	        hash_clause(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledo_clause_stringEx;
            	        }


            	    }
            	    break;
            	case 2:
            	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:79:19: brute_force_clause
            	    {
            	        FOLLOWPUSH(FOLLOW_brute_force_clause_in_do_clause_string272);
            	        brute_force_clause(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledo_clause_stringEx;
            	        }


            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruledo_clause_stringEx; /* Prevent compiler warnings */
    ruledo_clause_stringEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end do_clause_string */

/**
 * $ANTLR start print_clause
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:81:1: print_clause : 'print' print ( PLUS print )* ;
 */
static void
print_clause(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:81:13: ( 'print' print ( PLUS print )* )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:82:5: 'print' print ( PLUS print )*
        {
             MATCHT(41, &FOLLOW_41_in_print_clause288);
            if  (HASEXCEPTION())
            {
                goto ruleprint_clauseEx;
            }


            FOLLOWPUSH(FOLLOW_print_in_print_clause290);
            print(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleprint_clauseEx;
            }


            // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:82:19: ( PLUS print )*

            for (;;)
            {
                int alt9=2;
                switch ( LA(1) )
                {
                case PLUS:
                	{
                		alt9=1;
                	}
                    break;

                }

                switch (alt9)
                {
            	case 1:
            	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:82:20: PLUS print
            	    {
            	         MATCHT(PLUS, &FOLLOW_PLUS_in_print_clause293);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleprint_clauseEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_print_in_print_clause295);
            	        print(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleprint_clauseEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop9;	/* break out of the loop */
            	    break;
                }
            }
            loop9: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprint_clauseEx; /* Prevent compiler warnings */
    ruleprint_clauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end print_clause */

/**
 * $ANTLR start print
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:85:1: print : ( attr_clause | STRING | INT );
 */
static void
print(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        {
            //  C:\\hg\\hc\\src\\hlinq\\HLINQ.g:85:6: ( attr_clause | STRING | INT )

            ANTLR3_UINT32 alt10;

            alt10=3;

            switch ( LA(1) )
            {
            case ID:
            	{
            		alt10=1;
            	}
                break;
            case STRING:
            	{
            		alt10=2;
            	}
                break;
            case INT:
            	{
            		alt10=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 10;
                EXCEPTION->state        = 0;


                goto ruleprintEx;

            }

            switch (alt10)
            {
        	case 1:
        	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:86:2: attr_clause
        	    {
        	        FOLLOWPUSH(FOLLOW_attr_clause_in_print314);
        	        attr_clause(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleprintEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:86:16: STRING
        	    {
        	         MATCHT(STRING, &FOLLOW_STRING_in_print318);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleprintEx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:86:25: INT
        	    {
        	         MATCHT(INT, &FOLLOW_INT_in_print322);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleprintEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleprintEx; /* Prevent compiler warnings */
    ruleprintEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end print */

/**
 * $ANTLR start attr_clause
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:89:1: attr_clause : ID '.' attr ;
 */
static void
attr_clause(pHLINQParser ctx)
{
    pANTLR3_COMMON_TOKEN    ID2;

    /* Initialize rule variables
     */

    ID2       = NULL;

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:89:12: ( ID '.' attr )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:90:5: ID '.' attr
        {
            ID2 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_attr_clause335);
            if  (HASEXCEPTION())
            {
                goto ruleattr_clauseEx;
            }


             MATCHT(31, &FOLLOW_31_in_attr_clause337);
            if  (HASEXCEPTION())
            {
                goto ruleattr_clauseEx;
            }


            FOLLOWPUSH(FOLLOW_attr_in_attr_clause339);
            attr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleattr_clauseEx;
            }


            {

                		if (!CallAttiribute((ID2->getText(ID2))->chars)) {
                			// TODO: implement error
                		};
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleattr_clauseEx; /* Prevent compiler warnings */
    ruleattr_clauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end attr_clause */

/**
 * $ANTLR start attr
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:98:1: attr : ( str_attr | int_attr ) ;
 */
static void
attr(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:98:5: ( ( str_attr | int_attr ) )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:99:5: ( str_attr | int_attr )
        {
            // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:99:5: ( str_attr | int_attr )
            {
                int alt11=2;
                switch ( LA(1) )
                {
                case HASH:
                case 39:
                	{
                		alt11=1;
                	}
                    break;
                case 37:
                case 40:
                case 43:
                	{
                		alt11=2;
                	}
                    break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 11;
                    EXCEPTION->state        = 0;


                    goto ruleattrEx;

                }

                switch (alt11)
                {
            	case 1:
            	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:99:7: str_attr
            	    {
            	        FOLLOWPUSH(FOLLOW_str_attr_in_attr363);
            	        str_attr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleattrEx;
            	        }


            	    }
            	    break;
            	case 2:
            	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:99:18: int_attr
            	    {
            	        FOLLOWPUSH(FOLLOW_int_attr_in_attr367);
            	        int_attr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleattrEx;
            	        }


            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleattrEx; /* Prevent compiler warnings */
    ruleattrEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end attr */

/**
 * $ANTLR start delete_clause
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:102:1: delete_clause : 'delete' ;
 */
static void
delete_clause(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:102:14: ( 'delete' )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:103:5: 'delete'
        {
             MATCHT(34, &FOLLOW_34_in_delete_clause385);
            if  (HASEXCEPTION())
            {
                goto ruledelete_clauseEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruledelete_clauseEx; /* Prevent compiler warnings */
    ruledelete_clauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end delete_clause */

/**
 * $ANTLR start copy_clause
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:106:1: copy_clause : 'copy' s= STRING ;
 */
static void
copy_clause(pHLINQParser ctx)
{
    pANTLR3_COMMON_TOKEN    s;

    /* Initialize rule variables
     */

    s       = NULL;

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:106:12: ( 'copy' s= STRING )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:107:5: 'copy' s= STRING
        {
             MATCHT(32, &FOLLOW_32_in_copy_clause401);
            if  (HASEXCEPTION())
            {
                goto rulecopy_clauseEx;
            }


            s = (pANTLR3_COMMON_TOKEN) MATCHT(STRING, &FOLLOW_STRING_in_copy_clause405);
            if  (HASEXCEPTION())
            {
                goto rulecopy_clauseEx;
            }


            {

                		SetActionTarget((s->getText(s))->chars, (SCOPE_TOP(statement))->id);
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulecopy_clauseEx; /* Prevent compiler warnings */
    rulecopy_clauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end copy_clause */

/**
 * $ANTLR start move_clause
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:112:1: move_clause : 'move' s= STRING ;
 */
static void
move_clause(pHLINQParser ctx)
{
    pANTLR3_COMMON_TOKEN    s;

    /* Initialize rule variables
     */

    s       = NULL;

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:112:12: ( 'move' s= STRING )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:113:5: 'move' s= STRING
        {
             MATCHT(38, &FOLLOW_38_in_move_clause422);
            if  (HASEXCEPTION())
            {
                goto rulemove_clauseEx;
            }


            s = (pANTLR3_COMMON_TOKEN) MATCHT(STRING, &FOLLOW_STRING_in_move_clause426);
            if  (HASEXCEPTION())
            {
                goto rulemove_clauseEx;
            }


            {

                		SetActionTarget((s->getText(s))->chars, (SCOPE_TOP(statement))->id);
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulemove_clauseEx; /* Prevent compiler warnings */
    rulemove_clauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end move_clause */

/**
 * $ANTLR start hash_clause
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:118:1: hash_clause : HASH ;
 */
static void
hash_clause(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:118:12: ( HASH )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:119:5: HASH
        {
             MATCHT(HASH, &FOLLOW_HASH_in_hash_clause443);
            if  (HASEXCEPTION())
            {
                goto rulehash_clauseEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulehash_clauseEx; /* Prevent compiler warnings */
    rulehash_clauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end hash_clause */

/**
 * $ANTLR start brute_force_clause
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:122:1: brute_force_clause : 'crack' HASH ;
 */
static void
brute_force_clause(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:123:2: ( 'crack' HASH )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:123:4: 'crack' HASH
        {
             MATCHT(33, &FOLLOW_33_in_brute_force_clause461);
            if  (HASEXCEPTION())
            {
                goto rulebrute_force_clauseEx;
            }


             MATCHT(HASH, &FOLLOW_HASH_in_brute_force_clause463);
            if  (HASEXCEPTION())
            {
                goto rulebrute_force_clauseEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulebrute_force_clauseEx; /* Prevent compiler warnings */
    rulebrute_force_clauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end brute_force_clause */

/**
 * $ANTLR start let_clause
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:126:1: let_clause : 'let' exclusive_or_expression ( ',' exclusive_or_expression )* ;
 */
static void
let_clause(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:126:11: ( 'let' exclusive_or_expression ( ',' exclusive_or_expression )* )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:127:2: 'let' exclusive_or_expression ( ',' exclusive_or_expression )*
        {
             MATCHT(36, &FOLLOW_36_in_let_clause473);
            if  (HASEXCEPTION())
            {
                goto rulelet_clauseEx;
            }


            FOLLOWPUSH(FOLLOW_exclusive_or_expression_in_let_clause475);
            exclusive_or_expression(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulelet_clauseEx;
            }


            // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:127:32: ( ',' exclusive_or_expression )*

            for (;;)
            {
                int alt12=2;
                switch ( LA(1) )
                {
                case 30:
                	{
                		alt12=1;
                	}
                    break;

                }

                switch (alt12)
                {
            	case 1:
            	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:127:33: ',' exclusive_or_expression
            	    {
            	         MATCHT(30, &FOLLOW_30_in_let_clause478);
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulelet_clauseEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_exclusive_or_expression_in_let_clause480);
            	        exclusive_or_expression(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulelet_clauseEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop12;	/* break out of the loop */
            	    break;
                }
            }
            loop12: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulelet_clauseEx; /* Prevent compiler warnings */
    rulelet_clauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end let_clause */

/**
 * $ANTLR start where_clause
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:130:1: where_clause : 'where' boolean_expression ;
 */
static void
where_clause(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:130:13: ( 'where' boolean_expression )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:131:5: 'where' boolean_expression
        {
             MATCHT(44, &FOLLOW_44_in_where_clause495);
            if  (HASEXCEPTION())
            {
                goto rulewhere_clauseEx;
            }


            FOLLOWPUSH(FOLLOW_boolean_expression_in_where_clause497);
            boolean_expression(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulewhere_clauseEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulewhere_clauseEx; /* Prevent compiler warnings */
    rulewhere_clauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end where_clause */

/**
 * $ANTLR start boolean_expression
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:134:1: boolean_expression : conditional_or_expression ;
 */
static void
boolean_expression(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:134:19: ( conditional_or_expression )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:135:2: conditional_or_expression
        {
            FOLLOWPUSH(FOLLOW_conditional_or_expression_in_boolean_expression510);
            conditional_or_expression(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleboolean_expressionEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleboolean_expressionEx; /* Prevent compiler warnings */
    ruleboolean_expressionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end boolean_expression */

/**
 * $ANTLR start conditional_or_expression
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:137:1: conditional_or_expression : conditional_and_expression ( OR conditional_and_expression )* ;
 */
static void
conditional_or_expression(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:137:26: ( conditional_and_expression ( OR conditional_and_expression )* )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:138:2: conditional_and_expression ( OR conditional_and_expression )*
        {
            FOLLOWPUSH(FOLLOW_conditional_and_expression_in_conditional_or_expression518);
            conditional_and_expression(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleconditional_or_expressionEx;
            }


            // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:138:30: ( OR conditional_and_expression )*

            for (;;)
            {
                int alt13=2;
                switch ( LA(1) )
                {
                case OR:
                	{
                		alt13=1;
                	}
                    break;

                }

                switch (alt13)
                {
            	case 1:
            	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:138:31: OR conditional_and_expression
            	    {
            	         MATCHT(OR, &FOLLOW_OR_in_conditional_or_expression522);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleconditional_or_expressionEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_conditional_and_expression_in_conditional_or_expression524);
            	        conditional_and_expression(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleconditional_or_expressionEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop13;	/* break out of the loop */
            	    break;
                }
            }
            loop13: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleconditional_or_expressionEx; /* Prevent compiler warnings */
    ruleconditional_or_expressionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end conditional_or_expression */

/**
 * $ANTLR start conditional_and_expression
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:140:1: conditional_and_expression : exclusive_or_expression ( AND exclusive_or_expression )* ;
 */
static void
conditional_and_expression(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:140:27: ( exclusive_or_expression ( AND exclusive_or_expression )* )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:141:2: exclusive_or_expression ( AND exclusive_or_expression )*
        {
            FOLLOWPUSH(FOLLOW_exclusive_or_expression_in_conditional_and_expression535);
            exclusive_or_expression(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleconditional_and_expressionEx;
            }


            // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:141:28: ( AND exclusive_or_expression )*

            for (;;)
            {
                int alt14=2;
                switch ( LA(1) )
                {
                case AND:
                	{
                		alt14=1;
                	}
                    break;

                }

                switch (alt14)
                {
            	case 1:
            	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:141:29: AND exclusive_or_expression
            	    {
            	         MATCHT(AND, &FOLLOW_AND_in_conditional_and_expression540);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleconditional_and_expressionEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_exclusive_or_expression_in_conditional_and_expression542);
            	        exclusive_or_expression(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleconditional_and_expressionEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop14;	/* break out of the loop */
            	    break;
                }
            }
            loop14: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleconditional_and_expressionEx; /* Prevent compiler warnings */
    ruleconditional_and_expressionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end conditional_and_expression */

/**
 * $ANTLR start exclusive_or_expression
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:143:1: exclusive_or_expression : ID '.' ( ( str_attr ( COND_OP | COND_OP_STR ) STRING ) | ( int_attr ( COND_OP | COND_OP_INT ) INT ) ) ;
 */
static void
exclusive_or_expression(pHLINQParser ctx)
{
    pANTLR3_COMMON_TOKEN    ID3;

    /* Initialize rule variables
     */

    ID3       = NULL;

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:143:24: ( ID '.' ( ( str_attr ( COND_OP | COND_OP_STR ) STRING ) | ( int_attr ( COND_OP | COND_OP_INT ) INT ) ) )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:144:2: ID '.' ( ( str_attr ( COND_OP | COND_OP_STR ) STRING ) | ( int_attr ( COND_OP | COND_OP_INT ) INT ) )
        {
            ID3 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_exclusive_or_expression553);
            if  (HASEXCEPTION())
            {
                goto ruleexclusive_or_expressionEx;
            }


             MATCHT(31, &FOLLOW_31_in_exclusive_or_expression555);
            if  (HASEXCEPTION())
            {
                goto ruleexclusive_or_expressionEx;
            }


            // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:144:9: ( ( str_attr ( COND_OP | COND_OP_STR ) STRING ) | ( int_attr ( COND_OP | COND_OP_INT ) INT ) )
            {
                int alt15=2;
                switch ( LA(1) )
                {
                case HASH:
                case 39:
                	{
                		alt15=1;
                	}
                    break;
                case 37:
                case 40:
                case 43:
                	{
                		alt15=2;
                	}
                    break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 15;
                    EXCEPTION->state        = 0;


                    goto ruleexclusive_or_expressionEx;

                }

                switch (alt15)
                {
            	case 1:
            	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:144:10: ( str_attr ( COND_OP | COND_OP_STR ) STRING )
            	    {
            	        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:144:10: ( str_attr ( COND_OP | COND_OP_STR ) STRING )
            	        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:144:11: str_attr ( COND_OP | COND_OP_STR ) STRING
            	        {
            	            FOLLOWPUSH(FOLLOW_str_attr_in_exclusive_or_expression559);
            	            str_attr(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleexclusive_or_expressionEx;
            	            }


            	            if ( LA(1) == COND_OP || LA(1) == COND_OP_STR )
            	            {
            	                CONSUME();
            	                PERRORRECOVERY=ANTLR3_FALSE;
            	            }
            	            else
            	            {
            	                CONSTRUCTEX();
            	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	                EXCEPTION->expectingSet = NULL;

            	                goto ruleexclusive_or_expressionEx;
            	            }


            	             MATCHT(STRING, &FOLLOW_STRING_in_exclusive_or_expression569);
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleexclusive_or_expressionEx;
            	            }


            	        }


            	    }
            	    break;
            	case 2:
            	    // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:144:54: ( int_attr ( COND_OP | COND_OP_INT ) INT )
            	    {
            	        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:144:54: ( int_attr ( COND_OP | COND_OP_INT ) INT )
            	        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:144:55: int_attr ( COND_OP | COND_OP_INT ) INT
            	        {
            	            FOLLOWPUSH(FOLLOW_int_attr_in_exclusive_or_expression575);
            	            int_attr(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleexclusive_or_expressionEx;
            	            }


            	            if ( ((LA(1) >= COND_OP) && (LA(1) <= COND_OP_INT)) )
            	            {
            	                CONSUME();
            	                PERRORRECOVERY=ANTLR3_FALSE;
            	            }
            	            else
            	            {
            	                CONSTRUCTEX();
            	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	                EXCEPTION->expectingSet = NULL;

            	                goto ruleexclusive_or_expressionEx;
            	            }


            	             MATCHT(INT, &FOLLOW_INT_in_exclusive_or_expression585);
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleexclusive_or_expressionEx;
            	            }


            	        }


            	    }
            	    break;

                }
            }

            {

                		if (!CallAttiribute((ID3->getText(ID3))->chars)) {
                			// TODO: implement error
                		};
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleexclusive_or_expressionEx; /* Prevent compiler warnings */
    ruleexclusive_or_expressionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end exclusive_or_expression */

/**
 * $ANTLR start str_attr
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:152:1: str_attr : ( 'name' | HASH ) ;
 */
static void
str_attr(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:152:9: ( ( 'name' | HASH ) )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:
        {
            if ( LA(1) == HASH || LA(1) == 39 )
            {
                CONSUME();
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = NULL;

                goto rulestr_attrEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulestr_attrEx; /* Prevent compiler warnings */
    rulestr_attrEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end str_attr */

/**
 * $ANTLR start int_attr
 * C:\\hg\\hc\\src\\hlinq\\HLINQ.g:156:1: int_attr : ( 'size' | 'limit' | 'offset' ) ;
 */
static void
int_attr(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:156:9: ( ( 'size' | 'limit' | 'offset' ) )
        // C:\\hg\\hc\\src\\hlinq\\HLINQ.g:
        {
            if ( LA(1) == 37 || LA(1) == 40 || LA(1) == 43 )
            {
                CONSUME();
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = NULL;

                goto ruleint_attrEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleint_attrEx; /* Prevent compiler warnings */
    ruleint_attrEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end int_attr */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
