/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : D:\\hg\\hc\\src\\hlinq\\HLINQ.g
 *     -                            On : 2011-11-17 18:38:17
 *     -                for the parser : HLINQParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

   #include "compiler.h"

/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "HLINQParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pHLINQParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pHLINQParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pHLINQParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pHLINQParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */

/* ruleAttributeScopeFuncDecl(scope)
 */
/* -----------------------------------------------------------------------------
 * Function declarations for creating a HLINQParser_statement scope set
 */
static pHLINQParser_statement_SCOPE   pHLINQParser_statementPush(pHLINQParser ctx);
static void ANTLR3_CDECL statementFree(pHLINQParser_statement_SCOPE scope);
/* ----------------------------------------------------------------------------- */


/* ruleAttributeScopeFuncs(scope)
 */
/* attributeFuncs(scope)
 */

static void ANTLR3_CDECL statementFree(pHLINQParser_statement_SCOPE scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Allocate initial memory for a HLINQParser statement scope variable stack entry and
 *         add it to the top of the stack.
 *
 * \remark
 * By default the structure is freed with ANTLR_FREE(), but you can use the
 * the \@init action to install a pointer to a custom free() routine by
 * adding the code:
 * \code
 *   ctx->pHLINQParser_statementTop->free = myroutine;
 * \endcode
 *
 * With lots of comments of course! The routine should be declared in
 * \@members { } as:
 * \code
 *   void ANTLR3_CDECL myfunc( pHLINQParser_statement_SCOPE ptr).
 * \endcode
 *
 * It should perform any custom freeing stuff that you need (call ANTLR_FREE3, not free()
 * NB: It should not free the pointer it is given, which is the scope stack entry itself
 * and will be freed by the function that calls your custom free routine.
 *
 */
static pHLINQParser_statement_SCOPE
pHLINQParser_statementPush(pHLINQParser ctx)
{
    /* Pointer used to create a new set of attributes
     */
    pHLINQParser_statement_SCOPE      newAttributes;

    /* Allocate the memory for a new structure if we need one.
     */
    if (ctx->pHLINQParser_statementStack->size(ctx->pHLINQParser_statementStack) > ctx->pHLINQParser_statementStack_limit)
    {
        // The current limit value was less than the number of scopes available on the stack so
        // we can just reuse one. Our limit tracks the stack count, so the index of the entry we want
        // is one less than that, or conveniently, the current value of limit.
        //
        newAttributes = (pHLINQParser_statement_SCOPE)ctx->pHLINQParser_statementStack->get(ctx->pHLINQParser_statementStack, ctx->pHLINQParser_statementStack_limit);
    }
    else
    {
        // Need a new allocation
        //
        newAttributes = (pHLINQParser_statement_SCOPE) ANTLR3_MALLOC(sizeof(HLINQParser_statement_SCOPE));
        if  (newAttributes != NULL)
        {
            /* Standard ANTLR3 library implementation
             */
            ctx->pHLINQParser_statementStack->push(ctx->pHLINQParser_statementStack, newAttributes, (void (*)(void *))statementFree);
        }
    }

    // Blank out any previous free pointer, the user might or might install a new one.
    //
    newAttributes->free = NULL;

    // Indicate the position in the available stack that the current level is at
    //
    ctx->pHLINQParser_statementStack_limit++;

	/* Return value is the pointer to the new entry, which may be used locally
	 * without de-referencing via the context.
     */
    return  newAttributes;
}







/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   HLINQParserTokenNames[36+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "COMMENT",
        (pANTLR3_UINT8) "COND_OPERATOR",
        (pANTLR3_UINT8) "ECHAR",
        (pANTLR3_UINT8) "EOL",
        (pANTLR3_UINT8) "EQUAL",
        (pANTLR3_UINT8) "GE",
        (pANTLR3_UINT8) "HASH",
        (pANTLR3_UINT8) "IDENTIFIER",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "IdentifierPart",
        (pANTLR3_UINT8) "IdentifierStart",
        (pANTLR3_UINT8) "LE",
        (pANTLR3_UINT8) "MATCH",
        (pANTLR3_UINT8) "NEWLINE",
        (pANTLR3_UINT8) "NOT",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "STRING_LITERAL",
        (pANTLR3_UINT8) "STRING_LITERAL1",
        (pANTLR3_UINT8) "STRING_LITERAL2",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'.'",
        (pANTLR3_UINT8) "'and'",
        (pANTLR3_UINT8) "'copy'",
        (pANTLR3_UINT8) "'delete'",
        (pANTLR3_UINT8) "'do'",
        (pANTLR3_UINT8) "'for'",
        (pANTLR3_UINT8) "'in'",
        (pANTLR3_UINT8) "'limit'",
        (pANTLR3_UINT8) "'move'",
        (pANTLR3_UINT8) "'name'",
        (pANTLR3_UINT8) "'offset'",
        (pANTLR3_UINT8) "'or'",
        (pANTLR3_UINT8) "'print'",
        (pANTLR3_UINT8) "'recursively'",
        (pANTLR3_UINT8) "'size'",
        (pANTLR3_UINT8) "'where'"
       };


/* ruleAttributeScopeFuncMacro(scope)
 */
/** Function for popping the top value from a pHLINQParser_statementStack
 */
void
pHLINQParser_statementPop(pHLINQParser ctx)
{
    // First see if the user defined a function they want to be called when a
    // scope is popped/freed.
    //
	// If the user supplied the scope entries with a free function,then call it first
	//
    if	(SCOPE_TOP(statement)->free != NULL)
	{
        SCOPE_TOP(statement)->free(SCOPE_TOP(statement));
	}

    // Now we decrement the scope's upper limit bound. We do not actually pop the scope as
    // we want to reuse scope entries if we do continuous push and pops. Most scopes don't
    // next too far so we don't want to keep freeing and allocating them
    //
    ctx->pHLINQParser_statementStack_limit--;
    SCOPE_TOP(statement) = (pHLINQParser_statement_SCOPE)(ctx->pHLINQParser_statementStack->get(ctx->pHLINQParser_statementStack, ctx->pHLINQParser_statementStack_limit - 1));
}



// Forward declare the locally static matching functions we have generated.
//
static 
 void
	prog    (pHLINQParser ctx, apr_pool_t* root);
static 
 void
	statement    (pHLINQParser ctx);
static 
 void
	expr    (pHLINQParser ctx);
static 
 void
	identifier    (pHLINQParser ctx);
static 
 void
	doClause    (pHLINQParser ctx);
static 
 void
	printClause    (pHLINQParser ctx);
static 
 void
	printItem    (pHLINQParser ctx);
static 
 void
	deleteClause    (pHLINQParser ctx);
static 
 void
	copyClause    (pHLINQParser ctx);
static 
 void
	moveClause    (pHLINQParser ctx);
static 
 void
	whereClause    (pHLINQParser ctx);
static 
 void
	boolean_expression    (pHLINQParser ctx);
static 
 void
	exclusive_or_expression    (pHLINQParser ctx);
static 
 void
	conditional_and_expression    (pHLINQParser ctx);
static 
 void
	conditional_or_expression    (pHLINQParser ctx);
static 
 void
	attrCall    (pHLINQParser ctx);
static 
 void
	attrClause    (pHLINQParser ctx);
static void	HLINQParserFree(pHLINQParser ctx);
static void     HLINQParserReset (pHLINQParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "D:\\hg\\hc\\src\\hlinq\\HLINQ.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new HLINQParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pHLINQParser
HLINQParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return HLINQParserNewSSD(instream, NULL);
}

/** \brief Create a new HLINQParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pHLINQParser
HLINQParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pHLINQParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pHLINQParser) ANTLR3_CALLOC(1, sizeof(HLINQParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in HLINQParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our HLINQParser interface
     */
    ctx->prog	= prog;
    ctx->statement	= statement;
    ctx->expr	= expr;
    ctx->identifier	= identifier;
    ctx->doClause	= doClause;
    ctx->printClause	= printClause;
    ctx->printItem	= printItem;
    ctx->deleteClause	= deleteClause;
    ctx->copyClause	= copyClause;
    ctx->moveClause	= moveClause;
    ctx->whereClause	= whereClause;
    ctx->boolean_expression	= boolean_expression;
    ctx->exclusive_or_expression	= exclusive_or_expression;
    ctx->conditional_and_expression	= conditional_and_expression;
    ctx->conditional_or_expression	= conditional_or_expression;
    ctx->attrCall	= attrCall;
    ctx->attrClause	= attrClause;
    ctx->free			= HLINQParserFree;
    ctx->reset			= HLINQParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
    /* ruleAttributeScope(scope)
     */
    ctx->pHLINQParser_statementPush     = pHLINQParser_statementPush;
    ctx->pHLINQParser_statementStack    = antlr3StackNew(0);
    ctx->pHLINQParser_statementStack_limit    = 0;
    ctx->pHLINQParser_statementTop      = NULL;




    /* Install the token table
     */
    PSRSTATE->tokenNames   = HLINQParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
HLINQParserReset (pHLINQParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 HLINQParserFree(pHLINQParser ctx)
 {
    /* Free any scope memory
     */
    /* ruleAttributeScope(scope)
     */
    ctx->pHLINQParser_statementStack->free(ctx->pHLINQParser_statementStack);



	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return HLINQParserTokenNames;
}





/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_statement_in_prog70  */
static	ANTLR3_BITWORD FOLLOW_statement_in_prog70_bits[]	= { ANTLR3_UINT64_LIT(0x0000000020020002) };
static  ANTLR3_BITSET_LIST FOLLOW_statement_in_prog70	= { FOLLOW_statement_in_prog70_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_statement108  */
static	ANTLR3_BITWORD FOLLOW_expr_in_statement108_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_statement108	= { FOLLOW_expr_in_statement108_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_statement110  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_statement110_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_statement110	= { FOLLOW_NEWLINE_in_statement110_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_statement116  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_statement116_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_statement116	= { FOLLOW_NEWLINE_in_statement116_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_29_in_expr132  */
static	ANTLR3_BITWORD FOLLOW_29_in_expr132_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_29_in_expr132	= { FOLLOW_29_in_expr132_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_identifier_in_expr134  */
static	ANTLR3_BITWORD FOLLOW_identifier_in_expr134_bits[]	= { ANTLR3_UINT64_LIT(0x0000000040000000) };
static  ANTLR3_BITSET_LIST FOLLOW_identifier_in_expr134	= { FOLLOW_identifier_in_expr134_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_30_in_expr136  */
static	ANTLR3_BITWORD FOLLOW_30_in_expr136_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_30_in_expr136	= { FOLLOW_30_in_expr136_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_LITERAL_in_expr140  */
static	ANTLR3_BITWORD FOLLOW_STRING_LITERAL_in_expr140_bits[]	= { ANTLR3_UINT64_LIT(0x000000A010000000) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_LITERAL_in_expr140	= { FOLLOW_STRING_LITERAL_in_expr140_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_37_in_expr143  */
static	ANTLR3_BITWORD FOLLOW_37_in_expr143_bits[]	= { ANTLR3_UINT64_LIT(0x0000008010000000) };
static  ANTLR3_BITSET_LIST FOLLOW_37_in_expr143	= { FOLLOW_37_in_expr143_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_whereClause_in_expr148  */
static	ANTLR3_BITWORD FOLLOW_whereClause_in_expr148_bits[]	= { ANTLR3_UINT64_LIT(0x0000000010000000) };
static  ANTLR3_BITSET_LIST FOLLOW_whereClause_in_expr148	= { FOLLOW_whereClause_in_expr148_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_doClause_in_expr152  */
static	ANTLR3_BITWORD FOLLOW_doClause_in_expr152_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_doClause_in_expr152	= { FOLLOW_doClause_in_expr152_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_identifier176  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_identifier176_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_identifier176	= { FOLLOW_IDENTIFIER_in_identifier176_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_28_in_doClause194  */
static	ANTLR3_BITWORD FOLLOW_28_in_doClause194_bits[]	= { ANTLR3_UINT64_LIT(0x000000110C000400) };
static  ANTLR3_BITSET_LIST FOLLOW_28_in_doClause194	= { FOLLOW_28_in_doClause194_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_printClause_in_doClause197  */
static	ANTLR3_BITWORD FOLLOW_printClause_in_doClause197_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_printClause_in_doClause197	= { FOLLOW_printClause_in_doClause197_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_deleteClause_in_doClause201  */
static	ANTLR3_BITWORD FOLLOW_deleteClause_in_doClause201_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_deleteClause_in_doClause201	= { FOLLOW_deleteClause_in_doClause201_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_copyClause_in_doClause205  */
static	ANTLR3_BITWORD FOLLOW_copyClause_in_doClause205_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_copyClause_in_doClause205	= { FOLLOW_copyClause_in_doClause205_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_moveClause_in_doClause209  */
static	ANTLR3_BITWORD FOLLOW_moveClause_in_doClause209_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_moveClause_in_doClause209	= { FOLLOW_moveClause_in_doClause209_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_HASH_in_doClause213  */
static	ANTLR3_BITWORD FOLLOW_HASH_in_doClause213_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_HASH_in_doClause213	= { FOLLOW_HASH_in_doClause213_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_36_in_printClause229  */
static	ANTLR3_BITWORD FOLLOW_36_in_printClause229_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000101800) };
static  ANTLR3_BITSET_LIST FOLLOW_36_in_printClause229	= { FOLLOW_36_in_printClause229_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_printItem_in_printClause231  */
static	ANTLR3_BITWORD FOLLOW_printItem_in_printClause231_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080002) };
static  ANTLR3_BITSET_LIST FOLLOW_printItem_in_printClause231	= { FOLLOW_printItem_in_printClause231_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_printClause234  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_printClause234_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000101800) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_printClause234	= { FOLLOW_PLUS_in_printClause234_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_printItem_in_printClause236  */
static	ANTLR3_BITWORD FOLLOW_printItem_in_printClause236_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080002) };
static  ANTLR3_BITSET_LIST FOLLOW_printItem_in_printClause236	= { FOLLOW_printItem_in_printClause236_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrCall_in_printItem255  */
static	ANTLR3_BITWORD FOLLOW_attrCall_in_printItem255_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_attrCall_in_printItem255	= { FOLLOW_attrCall_in_printItem255_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_LITERAL_in_printItem259  */
static	ANTLR3_BITWORD FOLLOW_STRING_LITERAL_in_printItem259_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_LITERAL_in_printItem259	= { FOLLOW_STRING_LITERAL_in_printItem259_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_printItem263  */
static	ANTLR3_BITWORD FOLLOW_INT_in_printItem263_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_printItem263	= { FOLLOW_INT_in_printItem263_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_27_in_deleteClause276  */
static	ANTLR3_BITWORD FOLLOW_27_in_deleteClause276_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_27_in_deleteClause276	= { FOLLOW_27_in_deleteClause276_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_26_in_copyClause292  */
static	ANTLR3_BITWORD FOLLOW_26_in_copyClause292_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_26_in_copyClause292	= { FOLLOW_26_in_copyClause292_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_LITERAL_in_copyClause296  */
static	ANTLR3_BITWORD FOLLOW_STRING_LITERAL_in_copyClause296_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_LITERAL_in_copyClause296	= { FOLLOW_STRING_LITERAL_in_copyClause296_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_32_in_moveClause313  */
static	ANTLR3_BITWORD FOLLOW_32_in_moveClause313_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_32_in_moveClause313	= { FOLLOW_32_in_moveClause313_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_LITERAL_in_moveClause317  */
static	ANTLR3_BITWORD FOLLOW_STRING_LITERAL_in_moveClause317_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_LITERAL_in_moveClause317	= { FOLLOW_STRING_LITERAL_in_moveClause317_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_39_in_whereClause340  */
static	ANTLR3_BITWORD FOLLOW_39_in_whereClause340_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_39_in_whereClause340	= { FOLLOW_39_in_whereClause340_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_boolean_expression_in_whereClause342  */
static	ANTLR3_BITWORD FOLLOW_boolean_expression_in_whereClause342_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_boolean_expression_in_whereClause342	= { FOLLOW_boolean_expression_in_whereClause342_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_conditional_or_expression_in_boolean_expression355  */
static	ANTLR3_BITWORD FOLLOW_conditional_or_expression_in_boolean_expression355_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_conditional_or_expression_in_boolean_expression355	= { FOLLOW_conditional_or_expression_in_boolean_expression355_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrCall_in_exclusive_or_expression364  */
static	ANTLR3_BITWORD FOLLOW_attrCall_in_exclusive_or_expression364_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_attrCall_in_exclusive_or_expression364	= { FOLLOW_attrCall_in_exclusive_or_expression364_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_COND_OPERATOR_in_exclusive_or_expression366  */
static	ANTLR3_BITWORD FOLLOW_COND_OPERATOR_in_exclusive_or_expression366_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000101000) };
static  ANTLR3_BITSET_LIST FOLLOW_COND_OPERATOR_in_exclusive_or_expression366	= { FOLLOW_COND_OPERATOR_in_exclusive_or_expression366_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_exclusive_or_expression369  */
static	ANTLR3_BITWORD FOLLOW_set_in_exclusive_or_expression369_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_exclusive_or_expression369	= { FOLLOW_set_in_exclusive_or_expression369_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_exclusive_or_expression_in_conditional_and_expression386  */
static	ANTLR3_BITWORD FOLLOW_exclusive_or_expression_in_conditional_and_expression386_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002000002) };
static  ANTLR3_BITSET_LIST FOLLOW_exclusive_or_expression_in_conditional_and_expression386	= { FOLLOW_exclusive_or_expression_in_conditional_and_expression386_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_25_in_conditional_and_expression391  */
static	ANTLR3_BITWORD FOLLOW_25_in_conditional_and_expression391_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_25_in_conditional_and_expression391	= { FOLLOW_25_in_conditional_and_expression391_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_exclusive_or_expression_in_conditional_and_expression395  */
static	ANTLR3_BITWORD FOLLOW_exclusive_or_expression_in_conditional_and_expression395_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002000002) };
static  ANTLR3_BITSET_LIST FOLLOW_exclusive_or_expression_in_conditional_and_expression395	= { FOLLOW_exclusive_or_expression_in_conditional_and_expression395_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_conditional_and_expression_in_conditional_or_expression405  */
static	ANTLR3_BITWORD FOLLOW_conditional_and_expression_in_conditional_or_expression405_bits[]	= { ANTLR3_UINT64_LIT(0x0000000800000002) };
static  ANTLR3_BITSET_LIST FOLLOW_conditional_and_expression_in_conditional_or_expression405	= { FOLLOW_conditional_and_expression_in_conditional_or_expression405_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_35_in_conditional_or_expression409  */
static	ANTLR3_BITWORD FOLLOW_35_in_conditional_or_expression409_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_35_in_conditional_or_expression409	= { FOLLOW_35_in_conditional_or_expression409_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_conditional_and_expression_in_conditional_or_expression413  */
static	ANTLR3_BITWORD FOLLOW_conditional_and_expression_in_conditional_or_expression413_bits[]	= { ANTLR3_UINT64_LIT(0x0000000800000002) };
static  ANTLR3_BITSET_LIST FOLLOW_conditional_and_expression_in_conditional_or_expression413	= { FOLLOW_conditional_and_expression_in_conditional_or_expression413_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_attrCall427  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_attrCall427_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001000000) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_attrCall427	= { FOLLOW_IDENTIFIER_in_attrCall427_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_24_in_attrCall429  */
static	ANTLR3_BITWORD FOLLOW_24_in_attrCall429_bits[]	= { ANTLR3_UINT64_LIT(0x0000004680000400) };
static  ANTLR3_BITSET_LIST FOLLOW_24_in_attrCall429	= { FOLLOW_24_in_attrCall429_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrClause_in_attrCall431  */
static	ANTLR3_BITWORD FOLLOW_attrClause_in_attrCall431_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_attrClause_in_attrCall431	= { FOLLOW_attrClause_in_attrCall431_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start prog
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:33:1: prog[apr_pool_t* root] : ( statement )+ ;
 */
static void
prog(pHLINQParser ctx, apr_pool_t* root)
{
    /* Initialize rule variables
     */

     InitProgram(root); 
    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:35:2: ( ( statement )+ )
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:35:4: ( statement )+
        {
            // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:35:4: ( statement )+
            {
                int cnt1=0;

                for (;;)
                {
                    int alt1=2;
            	switch ( LA(1) )
            	{
            	case NEWLINE:
            	case 29:
            		{
            			alt1=1;
            		}
            	    break;

            	}

            	switch (alt1)
            	{
            	    case 1:
            	        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:35:4: statement
            	        {
            	            FOLLOWPUSH(FOLLOW_statement_in_prog70);
            	            statement(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleprogEx;
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt1 >= 1 )
            		{
            		    goto loop1;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleprogEx;
            	}
            	cnt1++;
                }
                loop1: ;	/* Jump to here if this rule does not match */
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprogEx; /* Prevent compiler warnings */
    ruleprogEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end prog */

/**
 * $ANTLR start statement
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:39:1: statement : ( expr NEWLINE | NEWLINE );
 */
static void
statement(pHLINQParser ctx)
{
    /* Initialize rule variables
     */
    ctx->pHLINQParser_statementTop = pHLINQParser_statementPush(ctx);
     OpenStatement(); 
    {
        {
            //  D:\\hg\\hc\\src\\hlinq\\HLINQ.g:45:5: ( expr NEWLINE | NEWLINE )

            ANTLR3_UINT32 alt2;

            alt2=2;

            switch ( LA(1) )
            {
            case 29:
            	{
            		alt2=1;
            	}
                break;
            case NEWLINE:
            	{
            		alt2=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto rulestatementEx;

            }

            switch (alt2)
            {
        	case 1:
        	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:45:9: expr NEWLINE
        	    {
        	        FOLLOWPUSH(FOLLOW_expr_in_statement108);
        	        expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }


        	         MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_statement110);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:45:26: NEWLINE
        	    {
        	         MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_statement116);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulestatementEx; /* Prevent compiler warnings */
    rulestatementEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CloseStatement((SCOPE_TOP(statement))->identifier); 
                }
            }


    pHLINQParser_statementPop(ctx);

    return ;
}
/* $ANTLR end statement */

/**
 * $ANTLR start expr
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:48:1: expr : 'for' identifier 'in' searchIn= STRING_LITERAL ( 'recursively' )? ( whereClause )? doClause ;
 */
static void
expr(pHLINQParser ctx)
{
    pANTLR3_COMMON_TOKEN    searchIn;

    /* Initialize rule variables
     */

    searchIn       = NULL;

    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:48:5: ( 'for' identifier 'in' searchIn= STRING_LITERAL ( 'recursively' )? ( whereClause )? doClause )
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:49:5: 'for' identifier 'in' searchIn= STRING_LITERAL ( 'recursively' )? ( whereClause )? doClause
        {
             MATCHT(29, &FOLLOW_29_in_expr132);
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }


            FOLLOWPUSH(FOLLOW_identifier_in_expr134);
            identifier(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }


             MATCHT(30, &FOLLOW_30_in_expr136);
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }


            searchIn = (pANTLR3_COMMON_TOKEN) MATCHT(STRING_LITERAL, &FOLLOW_STRING_LITERAL_in_expr140);
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }


            // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:49:51: ( 'recursively' )?
            {
                int alt3=2;
                switch ( LA(1) )
                {
                    case 37:
                    	{
                    		alt3=1;
                    	}
                        break;
                }

                switch (alt3)
                {
            	case 1:
            	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:49:52: 'recursively'
            	    {
            	         MATCHT(37, &FOLLOW_37_in_expr143);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexprEx;
            	        }


            	    }
            	    break;

                }
            }

            // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:49:68: ( whereClause )?
            {
                int alt4=2;
                switch ( LA(1) )
                {
                    case 39:
                    	{
                    		alt4=1;
                    	}
                        break;
                }

                switch (alt4)
                {
            	case 1:
            	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:49:69: whereClause
            	    {
            	        FOLLOWPUSH(FOLLOW_whereClause_in_expr148);
            	        whereClause(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexprEx;
            	        }


            	    }
            	    break;

                }
            }

            FOLLOWPUSH(FOLLOW_doClause_in_expr152);
            doClause(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }


            {

                		SetSearchRoot((searchIn->getText(searchIn))->chars, (SCOPE_TOP(statement))->identifier);
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end expr */

/**
 * $ANTLR start identifier
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:55:1: identifier : IDENTIFIER ;
 */
static void
identifier(pHLINQParser ctx)
{
    pANTLR3_COMMON_TOKEN    IDENTIFIER1;

    /* Initialize rule variables
     */

    IDENTIFIER1       = NULL;

    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:56:2: ( IDENTIFIER )
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:56:4: IDENTIFIER
        {
            IDENTIFIER1 = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_identifier176);
            if  (HASEXCEPTION())
            {
                goto ruleidentifierEx;
            }


            {

                		(SCOPE_TOP(statement))->identifier= (const char*)(IDENTIFIER1->getText(IDENTIFIER1))->chars;
                		CreateStatementContext((SCOPE_TOP(statement))->identifier);
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleidentifierEx; /* Prevent compiler warnings */
    ruleidentifierEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end identifier */

/**
 * $ANTLR start doClause
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:62:1: doClause : 'do' ( printClause | deleteClause | copyClause | moveClause | HASH ) ;
 */
static void
doClause(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:62:9: ( 'do' ( printClause | deleteClause | copyClause | moveClause | HASH ) )
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:63:5: 'do' ( printClause | deleteClause | copyClause | moveClause | HASH )
        {
             MATCHT(28, &FOLLOW_28_in_doClause194);
            if  (HASEXCEPTION())
            {
                goto ruledoClauseEx;
            }


            // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:63:10: ( printClause | deleteClause | copyClause | moveClause | HASH )
            {
                int alt5=5;
                switch ( LA(1) )
                {
                case 36:
                	{
                		alt5=1;
                	}
                    break;
                case 27:
                	{
                		alt5=2;
                	}
                    break;
                case 26:
                	{
                		alt5=3;
                	}
                    break;
                case 32:
                	{
                		alt5=4;
                	}
                    break;
                case HASH:
                	{
                		alt5=5;
                	}
                    break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 5;
                    EXCEPTION->state        = 0;


                    goto ruledoClauseEx;

                }

                switch (alt5)
                {
            	case 1:
            	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:63:11: printClause
            	    {
            	        FOLLOWPUSH(FOLLOW_printClause_in_doClause197);
            	        printClause(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledoClauseEx;
            	        }


            	    }
            	    break;
            	case 2:
            	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:63:25: deleteClause
            	    {
            	        FOLLOWPUSH(FOLLOW_deleteClause_in_doClause201);
            	        deleteClause(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledoClauseEx;
            	        }


            	    }
            	    break;
            	case 3:
            	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:63:40: copyClause
            	    {
            	        FOLLOWPUSH(FOLLOW_copyClause_in_doClause205);
            	        copyClause(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledoClauseEx;
            	        }


            	    }
            	    break;
            	case 4:
            	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:63:53: moveClause
            	    {
            	        FOLLOWPUSH(FOLLOW_moveClause_in_doClause209);
            	        moveClause(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledoClauseEx;
            	        }


            	    }
            	    break;
            	case 5:
            	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:63:66: HASH
            	    {
            	         MATCHT(HASH, &FOLLOW_HASH_in_doClause213);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledoClauseEx;
            	        }


            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruledoClauseEx; /* Prevent compiler warnings */
    ruledoClauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end doClause */

/**
 * $ANTLR start printClause
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:65:1: printClause : 'print' printItem ( PLUS printItem )* ;
 */
static void
printClause(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:65:12: ( 'print' printItem ( PLUS printItem )* )
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:66:5: 'print' printItem ( PLUS printItem )*
        {
             MATCHT(36, &FOLLOW_36_in_printClause229);
            if  (HASEXCEPTION())
            {
                goto ruleprintClauseEx;
            }


            FOLLOWPUSH(FOLLOW_printItem_in_printClause231);
            printItem(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleprintClauseEx;
            }


            // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:66:23: ( PLUS printItem )*

            for (;;)
            {
                int alt6=2;
                switch ( LA(1) )
                {
                case PLUS:
                	{
                		alt6=1;
                	}
                    break;

                }

                switch (alt6)
                {
            	case 1:
            	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:66:24: PLUS printItem
            	    {
            	         MATCHT(PLUS, &FOLLOW_PLUS_in_printClause234);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleprintClauseEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_printItem_in_printClause236);
            	        printItem(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleprintClauseEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop6;	/* break out of the loop */
            	    break;
                }
            }
            loop6: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprintClauseEx; /* Prevent compiler warnings */
    ruleprintClauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end printClause */

/**
 * $ANTLR start printItem
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:69:1: printItem : ( attrCall | STRING_LITERAL | INT );
 */
static void
printItem(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        {
            //  D:\\hg\\hc\\src\\hlinq\\HLINQ.g:69:10: ( attrCall | STRING_LITERAL | INT )

            ANTLR3_UINT32 alt7;

            alt7=3;

            switch ( LA(1) )
            {
            case IDENTIFIER:
            	{
            		alt7=1;
            	}
                break;
            case STRING_LITERAL:
            	{
            		alt7=2;
            	}
                break;
            case INT:
            	{
            		alt7=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 7;
                EXCEPTION->state        = 0;


                goto ruleprintItemEx;

            }

            switch (alt7)
            {
        	case 1:
        	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:70:2: attrCall
        	    {
        	        FOLLOWPUSH(FOLLOW_attrCall_in_printItem255);
        	        attrCall(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleprintItemEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:70:13: STRING_LITERAL
        	    {
        	         MATCHT(STRING_LITERAL, &FOLLOW_STRING_LITERAL_in_printItem259);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleprintItemEx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:70:30: INT
        	    {
        	         MATCHT(INT, &FOLLOW_INT_in_printItem263);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleprintItemEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleprintItemEx; /* Prevent compiler warnings */
    ruleprintItemEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end printItem */

/**
 * $ANTLR start deleteClause
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:73:1: deleteClause : 'delete' ;
 */
static void
deleteClause(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:73:13: ( 'delete' )
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:74:5: 'delete'
        {
             MATCHT(27, &FOLLOW_27_in_deleteClause276);
            if  (HASEXCEPTION())
            {
                goto ruledeleteClauseEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruledeleteClauseEx; /* Prevent compiler warnings */
    ruledeleteClauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end deleteClause */

/**
 * $ANTLR start copyClause
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:77:1: copyClause : 'copy' s= STRING_LITERAL ;
 */
static void
copyClause(pHLINQParser ctx)
{
    pANTLR3_COMMON_TOKEN    s;

    /* Initialize rule variables
     */

    s       = NULL;

    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:77:11: ( 'copy' s= STRING_LITERAL )
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:78:5: 'copy' s= STRING_LITERAL
        {
             MATCHT(26, &FOLLOW_26_in_copyClause292);
            if  (HASEXCEPTION())
            {
                goto rulecopyClauseEx;
            }


            s = (pANTLR3_COMMON_TOKEN) MATCHT(STRING_LITERAL, &FOLLOW_STRING_LITERAL_in_copyClause296);
            if  (HASEXCEPTION())
            {
                goto rulecopyClauseEx;
            }


            {

                		SetActionTarget((s->getText(s))->chars, (SCOPE_TOP(statement))->identifier);
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulecopyClauseEx; /* Prevent compiler warnings */
    rulecopyClauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end copyClause */

/**
 * $ANTLR start moveClause
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:83:1: moveClause : 'move' s= STRING_LITERAL ;
 */
static void
moveClause(pHLINQParser ctx)
{
    pANTLR3_COMMON_TOKEN    s;

    /* Initialize rule variables
     */

    s       = NULL;

    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:83:11: ( 'move' s= STRING_LITERAL )
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:84:5: 'move' s= STRING_LITERAL
        {
             MATCHT(32, &FOLLOW_32_in_moveClause313);
            if  (HASEXCEPTION())
            {
                goto rulemoveClauseEx;
            }


            s = (pANTLR3_COMMON_TOKEN) MATCHT(STRING_LITERAL, &FOLLOW_STRING_LITERAL_in_moveClause317);
            if  (HASEXCEPTION())
            {
                goto rulemoveClauseEx;
            }


            {

                		SetActionTarget((s->getText(s))->chars, (SCOPE_TOP(statement))->identifier);
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulemoveClauseEx; /* Prevent compiler warnings */
    rulemoveClauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end moveClause */

/**
 * $ANTLR start whereClause
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:90:1: whereClause : 'where' boolean_expression ;
 */
static void
whereClause(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:90:12: ( 'where' boolean_expression )
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:91:5: 'where' boolean_expression
        {
             MATCHT(39, &FOLLOW_39_in_whereClause340);
            if  (HASEXCEPTION())
            {
                goto rulewhereClauseEx;
            }


            FOLLOWPUSH(FOLLOW_boolean_expression_in_whereClause342);
            boolean_expression(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulewhereClauseEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulewhereClauseEx; /* Prevent compiler warnings */
    rulewhereClauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end whereClause */

/**
 * $ANTLR start boolean_expression
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:94:1: boolean_expression : conditional_or_expression ;
 */
static void
boolean_expression(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:94:19: ( conditional_or_expression )
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:95:2: conditional_or_expression
        {
            FOLLOWPUSH(FOLLOW_conditional_or_expression_in_boolean_expression355);
            conditional_or_expression(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleboolean_expressionEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleboolean_expressionEx; /* Prevent compiler warnings */
    ruleboolean_expressionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end boolean_expression */

/**
 * $ANTLR start exclusive_or_expression
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:98:1: exclusive_or_expression : attrCall COND_OPERATOR ( STRING_LITERAL | INT ) ;
 */
static void
exclusive_or_expression(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:98:24: ( attrCall COND_OPERATOR ( STRING_LITERAL | INT ) )
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:99:2: attrCall COND_OPERATOR ( STRING_LITERAL | INT )
        {
            FOLLOWPUSH(FOLLOW_attrCall_in_exclusive_or_expression364);
            attrCall(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleexclusive_or_expressionEx;
            }


             MATCHT(COND_OPERATOR, &FOLLOW_COND_OPERATOR_in_exclusive_or_expression366);
            if  (HASEXCEPTION())
            {
                goto ruleexclusive_or_expressionEx;
            }


            if ( LA(1) == INT || LA(1) == STRING_LITERAL )
            {
                CONSUME();
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = NULL;

                goto ruleexclusive_or_expressionEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleexclusive_or_expressionEx; /* Prevent compiler warnings */
    ruleexclusive_or_expressionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end exclusive_or_expression */

/**
 * $ANTLR start conditional_and_expression
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:101:1: conditional_and_expression : exclusive_or_expression ( 'and' exclusive_or_expression )* ;
 */
static void
conditional_and_expression(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:101:27: ( exclusive_or_expression ( 'and' exclusive_or_expression )* )
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:102:2: exclusive_or_expression ( 'and' exclusive_or_expression )*
        {
            FOLLOWPUSH(FOLLOW_exclusive_or_expression_in_conditional_and_expression386);
            exclusive_or_expression(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleconditional_and_expressionEx;
            }


            // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:102:28: ( 'and' exclusive_or_expression )*

            for (;;)
            {
                int alt8=2;
                switch ( LA(1) )
                {
                case 25:
                	{
                		alt8=1;
                	}
                    break;

                }

                switch (alt8)
                {
            	case 1:
            	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:102:29: 'and' exclusive_or_expression
            	    {
            	         MATCHT(25, &FOLLOW_25_in_conditional_and_expression391);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleconditional_and_expressionEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_exclusive_or_expression_in_conditional_and_expression395);
            	        exclusive_or_expression(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleconditional_and_expressionEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop8;	/* break out of the loop */
            	    break;
                }
            }
            loop8: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleconditional_and_expressionEx; /* Prevent compiler warnings */
    ruleconditional_and_expressionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end conditional_and_expression */

/**
 * $ANTLR start conditional_or_expression
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:103:1: conditional_or_expression : conditional_and_expression ( 'or' conditional_and_expression )* ;
 */
static void
conditional_or_expression(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:103:26: ( conditional_and_expression ( 'or' conditional_and_expression )* )
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:104:2: conditional_and_expression ( 'or' conditional_and_expression )*
        {
            FOLLOWPUSH(FOLLOW_conditional_and_expression_in_conditional_or_expression405);
            conditional_and_expression(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleconditional_or_expressionEx;
            }


            // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:104:30: ( 'or' conditional_and_expression )*

            for (;;)
            {
                int alt9=2;
                switch ( LA(1) )
                {
                case 35:
                	{
                		alt9=1;
                	}
                    break;

                }

                switch (alt9)
                {
            	case 1:
            	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:104:31: 'or' conditional_and_expression
            	    {
            	         MATCHT(35, &FOLLOW_35_in_conditional_or_expression409);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleconditional_or_expressionEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_conditional_and_expression_in_conditional_or_expression413);
            	        conditional_and_expression(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleconditional_or_expressionEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop9;	/* break out of the loop */
            	    break;
                }
            }
            loop9: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleconditional_or_expressionEx; /* Prevent compiler warnings */
    ruleconditional_or_expressionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end conditional_or_expression */

/**
 * $ANTLR start attrCall
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:106:1: attrCall : IDENTIFIER '.' attrClause ;
 */
static void
attrCall(pHLINQParser ctx)
{
    pANTLR3_COMMON_TOKEN    IDENTIFIER2;

    /* Initialize rule variables
     */

    IDENTIFIER2       = NULL;

    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:106:9: ( IDENTIFIER '.' attrClause )
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:107:5: IDENTIFIER '.' attrClause
        {
            IDENTIFIER2 = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_attrCall427);
            if  (HASEXCEPTION())
            {
                goto ruleattrCallEx;
            }


             MATCHT(24, &FOLLOW_24_in_attrCall429);
            if  (HASEXCEPTION())
            {
                goto ruleattrCallEx;
            }


            FOLLOWPUSH(FOLLOW_attrClause_in_attrCall431);
            attrClause(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleattrCallEx;
            }


            {

                    	CallAttiribute((IDENTIFIER2->getText(IDENTIFIER2))->chars);
                    
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleattrCallEx; /* Prevent compiler warnings */
    ruleattrCallEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end attrCall */

/**
 * $ANTLR start attrClause
 * D:\\hg\\hc\\src\\hlinq\\HLINQ.g:113:1: attrClause : ( 'name' | 'size' | 'limit' | 'offset' | HASH ) ;
 */
static void
attrClause(pHLINQParser ctx)
{
    /* Initialize rule variables
     */

    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:113:11: ( ( 'name' | 'size' | 'limit' | 'offset' | HASH ) )
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:
        {
            if ( LA(1) == HASH || LA(1) == 31 || ((LA(1) >= 33) && (LA(1) <= 34)) || LA(1) == 38 )
            {
                CONSUME();
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = NULL;

                goto ruleattrClauseEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleattrClauseEx; /* Prevent compiler warnings */
    ruleattrClauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end attrClause */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
