/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : C:\\hg\\hc\\src\\hlinq\\HLINQ.g
 *     -                            On : 2012-08-21 15:06:32
 *     -                 for the lexer : HLINQLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
HLINQLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pHLINQLexer, which is returned from a call to HLINQLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pHLINQLexer are  as follows:
 *
 *  - 
 void
      pHLINQLexer->NAME_ATTR(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->PATH_ATTR(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->DICT_ATTR(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->SIZE_ATTR(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->LIMIT_ATTR(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->OFFSET_ATTR(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->MIN_ATTR(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->MAX_ATTR(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->CRACK(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->WHERE(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->OR(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->AND(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->NOT_OP(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->FOR(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->FROM(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->DO(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->FIND(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->WITHSUBS(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->VALIDATE(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->LET(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->DIR(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->FILE(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->HASH(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->STR(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->SET(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->MD5(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->SHA1(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->SHA256(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->SHA384(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->SHA512(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->MD4(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->CRC32(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->WHIRLPOOL(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->STRING1(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->STRING2(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->STRING(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->ID(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->ID_START(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->ID_PART(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->INT(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->ASSIGN_OP(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->NEWLINE(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->WS(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->DOT(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->COMMA(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->OPEN_BRACE(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->CLOSE_BRACE(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->COMMENT(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->EOL(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->LF(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->CR(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->PLUS(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->EQUAL(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->NOTEQUAL(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->ASSIGN(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->NOT(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->GE(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->LE(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->MATCH(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->NOTMATCH(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->LEASSIGN(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->GEASSIGN(pHLINQLexer)
 *  - 
 void
      pHLINQLexer->Tokens(pHLINQLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_HLINQLexer_H
#define _HLINQLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct HLINQLexer_Ctx_struct HLINQLexer, * pHLINQLexer;



	#define	ANTLR3_INLINE_INPUT_ASCII
	#include "compiler.h"
#ifdef GTEST
  #include "displayError.h"
#endif


#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
HLINQLexer

 */
struct HLINQLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mNAME_ATTR)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mPATH_ATTR)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mDICT_ATTR)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mSIZE_ATTR)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mLIMIT_ATTR)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mOFFSET_ATTR)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mMIN_ATTR)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mMAX_ATTR)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mCRACK)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mWHERE)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mOR)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mAND)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mNOT_OP)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mFOR)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mFROM)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mDO)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mFIND)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mWITHSUBS)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mVALIDATE)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mLET)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mDIR)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mFILE)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mHASH)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mSTR)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mSET)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mMD5)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mSHA1)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mSHA256)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mSHA384)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mSHA512)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mMD4)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mCRC32)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mWHIRLPOOL)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mSTRING1)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mSTRING2)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mSTRING)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mID)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mID_START)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mID_PART)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mINT)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mASSIGN_OP)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mNEWLINE)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mDOT)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mCOMMA)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mOPEN_BRACE)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mCLOSE_BRACE)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mCOMMENT)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mEOL)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mLF)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mCR)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mPLUS)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mEQUAL)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mNOTEQUAL)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mASSIGN)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mNOT)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mGE)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mLE)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mMATCH)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mNOTMATCH)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mLEASSIGN)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mGEASSIGN)	(struct HLINQLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct HLINQLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct HLINQLexer_Ctx_struct * ctx);
    void	    (*free)   (struct HLINQLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pHLINQLexer HLINQLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pHLINQLexer HLINQLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define AND      4
#define ASSIGN      5
#define ASSIGN_OP      6
#define ATTR_REF      7
#define BRUTE_FORCE      8
#define CLOSE_BRACE      9
#define COMMA      10
#define COMMENT      11
#define CR      12
#define CRACK      13
#define CRC32      14
#define DICT_ATTR      15
#define DIR      16
#define DO      17
#define DOT      18
#define EOL      19
#define EQUAL      20
#define FILE      21
#define FIND      22
#define FOR      23
#define FROM      24
#define GE      25
#define GEASSIGN      26
#define HASH      27
#define HASH_DIR      28
#define HASH_FILE      29
#define HASH_STR      30
#define ID      31
#define ID_PART      32
#define ID_START      33
#define INT      34
#define LE      35
#define LEASSIGN      36
#define LET      37
#define LF      38
#define LIMIT_ATTR      39
#define MATCH      40
#define MAX_ATTR      41
#define MD4      42
#define MD5      43
#define MIN_ATTR      44
#define NAME_ATTR      45
#define NEWLINE      46
#define NOT      47
#define NOTEQUAL      48
#define NOTMATCH      49
#define NOT_OP      50
#define OFFSET_ATTR      51
#define OPEN_BRACE      52
#define OR      53
#define PATH_ATTR      54
#define PLUS      55
#define SET      56
#define SHA1      57
#define SHA256      58
#define SHA384      59
#define SHA512      60
#define SIZE_ATTR      61
#define STR      62
#define STRING      63
#define STRING1      64
#define STRING2      65
#define VALIDATE      66
#define VAR_DEF      67
#define WHERE      68
#define WHIRLPOOL      69
#define WITHSUBS      70
#define WS      71
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for HLINQLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
