/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : D:\\hg\\hc\\src\\hlinq\\HLINQ.g
 *     -                            On : 2011-11-14 23:05:10
 *     -                 for the lexer : HLINQLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

#define	ANTLR3_INLINE_INPUT_ASCII

/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "HLINQLexer.h"
/* ----------------------------------------- */


/** String literals used by HLINQLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x63, 0x6F, 0x70, 0x79,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x64, 0x65, 0x6C, 0x65, 0x74, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x64, 0x6F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x66, 0x6F, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x69, 0x6E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x6D, 0x6F, 0x76, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x70, 0x72, 0x69, 0x6E, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x6C, 0x79,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x77, 0x68, 0x65, 0x72, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x6D, 0x64, 0x35,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x4D, 0x44, 0x35,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x73, 0x68, 0x61, 0x31,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_13[]  = { 0x53, 0x48, 0x41, 0x31,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pHLINQLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pHLINQLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pHLINQLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pHLINQLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mT__13    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mT__14    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mT__15    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mT__16    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mT__17    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mT__18    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mT__19    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mT__20    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mT__21    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mT__22    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mT__23    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mT__24    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mSTRING_LITERAL    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mSTRING_GUTS    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mEscapeSequence    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mOctalEscape    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mID    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mHASH    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mINT    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mNEWLINE    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (pHLINQLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pHLINQLexer ctx);
static void	HLINQLexerFree(pHLINQLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
HLINQLexerFree  (pHLINQLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
HLINQLexerReset (pHLINQLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "D:\\hg\\hc\\src\\hlinq\\HLINQ.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called HLINQLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pHLINQLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pHLINQLexer HLINQLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return HLINQLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called HLINQLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pHLINQLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pHLINQLexer HLINQLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pHLINQLexer ctx; // Context structure we will build and return

    ctx = (pHLINQLexer) ANTLR3_CALLOC(1, sizeof(HLINQLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in HLINQLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our HLINQLexer interface
     */
    ctx->mT__13	= mT__13;
    ctx->mT__14	= mT__14;
    ctx->mT__15	= mT__15;
    ctx->mT__16	= mT__16;
    ctx->mT__17	= mT__17;
    ctx->mT__18	= mT__18;
    ctx->mT__19	= mT__19;
    ctx->mT__20	= mT__20;
    ctx->mT__21	= mT__21;
    ctx->mT__22	= mT__22;
    ctx->mT__23	= mT__23;
    ctx->mT__24	= mT__24;
    ctx->mSTRING_LITERAL	= mSTRING_LITERAL;
    ctx->mSTRING_GUTS	= mSTRING_GUTS;
    ctx->mEscapeSequence	= mEscapeSequence;
    ctx->mOctalEscape	= mOctalEscape;
    ctx->mID	= mID;
    ctx->mHASH	= mHASH;
    ctx->mINT	= mINT;
    ctx->mNEWLINE	= mNEWLINE;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= HLINQLexerFree;
    ctx->reset          = HLINQLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 11:7: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__13
 *
 * Looks to match the characters the constitute the token T__13
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__13(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__13;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:11:7: ( '+' )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:11:9: '+'
    {
        MATCHC('+');
        if  (HASEXCEPTION())
        {
            goto ruleT__13Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__13Ex; /* Prevent compiler warnings */
    ruleT__13Ex: ;

}
// $ANTLR end T__13

//   Comes from: 12:7: ( '.' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__14
 *
 * Looks to match the characters the constitute the token T__14
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__14(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__14;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:12:7: ( '.' )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:12:9: '.'
    {
        MATCHC('.');
        if  (HASEXCEPTION())
        {
            goto ruleT__14Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__14Ex; /* Prevent compiler warnings */
    ruleT__14Ex: ;

}
// $ANTLR end T__14

//   Comes from: 13:7: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__15
 *
 * Looks to match the characters the constitute the token T__15
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__15(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__15;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:13:7: ( '=' )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:13:9: '='
    {
        MATCHC('=');
        if  (HASEXCEPTION())
        {
            goto ruleT__15Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__15Ex; /* Prevent compiler warnings */
    ruleT__15Ex: ;

}
// $ANTLR end T__15

//   Comes from: 14:7: ( 'copy' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__16
 *
 * Looks to match the characters the constitute the token T__16
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__16(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__16;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:14:7: ( 'copy' )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:14:9: 'copy'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleT__16Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__16Ex; /* Prevent compiler warnings */
    ruleT__16Ex: ;

}
// $ANTLR end T__16

//   Comes from: 15:7: ( 'delete' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__17
 *
 * Looks to match the characters the constitute the token T__17
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__17(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__17;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:15:7: ( 'delete' )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:15:9: 'delete'
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleT__17Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__17Ex; /* Prevent compiler warnings */
    ruleT__17Ex: ;

}
// $ANTLR end T__17

//   Comes from: 16:7: ( 'do' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__18
 *
 * Looks to match the characters the constitute the token T__18
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__18(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__18;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:16:7: ( 'do' )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:16:9: 'do'
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleT__18Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__18Ex; /* Prevent compiler warnings */
    ruleT__18Ex: ;

}
// $ANTLR end T__18

//   Comes from: 17:7: ( 'for' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__19
 *
 * Looks to match the characters the constitute the token T__19
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__19(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__19;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:17:7: ( 'for' )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:17:9: 'for'
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleT__19Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__19Ex; /* Prevent compiler warnings */
    ruleT__19Ex: ;

}
// $ANTLR end T__19

//   Comes from: 18:7: ( 'in' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__20
 *
 * Looks to match the characters the constitute the token T__20
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__20(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__20;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:18:7: ( 'in' )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:18:9: 'in'
    {
        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto ruleT__20Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__20Ex; /* Prevent compiler warnings */
    ruleT__20Ex: ;

}
// $ANTLR end T__20

//   Comes from: 19:7: ( 'move' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__21
 *
 * Looks to match the characters the constitute the token T__21
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__21(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__21;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:19:7: ( 'move' )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:19:9: 'move'
    {
        MATCHS(lit_6);
        if  (HASEXCEPTION())
        {
            goto ruleT__21Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__21Ex; /* Prevent compiler warnings */
    ruleT__21Ex: ;

}
// $ANTLR end T__21

//   Comes from: 20:7: ( 'print' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__22
 *
 * Looks to match the characters the constitute the token T__22
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__22(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__22;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:20:7: ( 'print' )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:20:9: 'print'
    {
        MATCHS(lit_7);
        if  (HASEXCEPTION())
        {
            goto ruleT__22Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__22Ex; /* Prevent compiler warnings */
    ruleT__22Ex: ;

}
// $ANTLR end T__22

//   Comes from: 21:7: ( 'recursively' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__23
 *
 * Looks to match the characters the constitute the token T__23
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__23(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__23;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:21:7: ( 'recursively' )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:21:9: 'recursively'
    {
        MATCHS(lit_8);
        if  (HASEXCEPTION())
        {
            goto ruleT__23Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__23Ex; /* Prevent compiler warnings */
    ruleT__23Ex: ;

}
// $ANTLR end T__23

//   Comes from: 22:7: ( 'where' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__24
 *
 * Looks to match the characters the constitute the token T__24
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__24(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__24;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:22:7: ( 'where' )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:22:9: 'where'
    {
        MATCHS(lit_9);
        if  (HASEXCEPTION())
        {
            goto ruleT__24Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__24Ex; /* Prevent compiler warnings */
    ruleT__24Ex: ;

}
// $ANTLR end T__24

//   Comes from: 51:5: ( '\"' STRING_GUTS '\"' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING_LITERAL
 *
 * Looks to match the characters the constitute the token STRING_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING_LITERAL(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = STRING_LITERAL;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:51:5: ( '\"' STRING_GUTS '\"' )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:51:8: '\"' STRING_GUTS '\"'
    {
        MATCHC('"');
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_LITERALEx;
        }


        /* 51:8: '\"' STRING_GUTS '\"' */
        mSTRING_GUTS(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_LITERALEx;
        }



        MATCHC('"');
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_LITERALEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSTRING_LITERALEx; /* Prevent compiler warnings */
    ruleSTRING_LITERALEx: ;

}
// $ANTLR end STRING_LITERAL

//   Comes from: 56:13: ( ( EscapeSequence |~ ( '\\\\' | '\"' ) )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING_GUTS
 *
 * Looks to match the characters the constitute the token STRING_GUTS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING_GUTS(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:56:13: ( ( EscapeSequence |~ ( '\\\\' | '\"' ) )* )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:56:15: ( EscapeSequence |~ ( '\\\\' | '\"' ) )*
    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:56:15: ( EscapeSequence |~ ( '\\\\' | '\"' ) )*

        for (;;)
        {
            int alt1=3;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA1_0 = LA(1);
                if ( (LA1_0 == '\\'))
                {
                    alt1=1;
                }
                else if ( (((LA1_0 >= 0x0000) && (LA1_0 <= '!')) || ((LA1_0 >= '#') && (LA1_0 <= '[')) || ((LA1_0 >= ']') && (LA1_0 <= 0xFFFF))))
                {
                    alt1=2;
                }

            }
            switch (alt1)
            {
        	case 1:
        	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:56:17: EscapeSequence
        	    {
        	        /* 56:17: EscapeSequence */
        	        mEscapeSequence(ctx );
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleSTRING_GUTSEx;
        	        }



        	    }
        	    break;
        	case 2:
        	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:56:34: ~ ( '\\\\' | '\"' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '!')) || ((LA(1) >= '#') && (LA(1) <= '[')) || ((LA(1) >= ']') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleSTRING_GUTSEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop1;	/* break out of the loop */
        	    break;
            }
        }
        loop1: ; /* Jump out to here if this rule does not match */


    }


    // This is where rules clean up and exit
    //
    goto ruleSTRING_GUTSEx; /* Prevent compiler warnings */
    ruleSTRING_GUTSEx: ;

}
// $ANTLR end STRING_GUTS

//   Comes from: 60:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) | OctalEscape )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EscapeSequence
 *
 * Looks to match the characters the constitute the token EscapeSequence
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEscapeSequence(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;


    {
        //  D:\\hg\\hc\\src\\hlinq\\HLINQ.g:60:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) | OctalEscape )

        ANTLR3_UINT32 alt2;

        alt2=2;

        switch ( LA(1) )
        {
        case '\\':
        	{
        		switch ( LA(2) )
        		{
        		case '"':
        		case '\'':
        		case '\\':
        		case 'b':
        		case 'f':
        		case 'n':
        		case 'r':
        		case 't':
        			{
        				alt2=1;
        			}
        		    break;
        		case '0':
        		case '1':
        		case '2':
        		case '3':
        		case '4':
        		case '5':
        		case '6':
        		case '7':
        			{
        				alt2=2;
        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 2;
        		    EXCEPTION->state        = 1;


        		    goto ruleEscapeSequenceEx;

        		}

        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 2;
            EXCEPTION->state        = 0;


            goto ruleEscapeSequenceEx;

        }

        switch (alt2)
        {
    	case 1:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:60:9: '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' )
    	    {
    	        MATCHC('\\');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleEscapeSequenceEx;
    	        }


    	        if ( LA(1) == '"' || LA(1) == '\'' || LA(1) == '\\' || LA(1) == 'b' || LA(1) == 'f' || LA(1) == 'n' || LA(1) == 'r' || LA(1) == 't' )
    	        {
    	            CONSUME();
    	        }
    	        else
    	        {
    	            CONSTRUCTEX();
    	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	            LRECOVER();
    	            goto ruleEscapeSequenceEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:61:9: OctalEscape
    	    {
    	        /* 61:9: OctalEscape */
    	        mOctalEscape(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleEscapeSequenceEx;
    	        }



    	    }
    	    break;

        }
    }

    // This is where rules clean up and exit
    //
    goto ruleEscapeSequenceEx; /* Prevent compiler warnings */
    ruleEscapeSequenceEx: ;

}
// $ANTLR end EscapeSequence

//   Comes from: 66:5: ( '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OctalEscape
 *
 * Looks to match the characters the constitute the token OctalEscape
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOctalEscape(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;


    {
        //  D:\\hg\\hc\\src\\hlinq\\HLINQ.g:66:5: ( '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) )

        ANTLR3_UINT32 alt3;

        alt3=3;

        switch ( LA(1) )
        {
        case '\\':
        	{
        		switch ( LA(2) )
        		{
        		case '0':
        		case '1':
        		case '2':
        		case '3':
        			{
        				switch ( LA(3) )
        				{
        				case '0':
        				case '1':
        				case '2':
        				case '3':
        				case '4':
        				case '5':
        				case '6':
        				case '7':
        					{
        						switch ( LA(4) )
        						{
        						case '0':
        						case '1':
        						case '2':
        						case '3':
        						case '4':
        						case '5':
        						case '6':
        						case '7':
        							{
        								alt3=1;
        							}
        						    break;

        						default:
        						    alt3=2;
        						}

        					}
        				    break;

        				default:
        				    alt3=3;
        				}

        			}
        		    break;
        		case '4':
        		case '5':
        		case '6':
        		case '7':
        			{
        				switch ( LA(3) )
        				{
        				case '0':
        				case '1':
        				case '2':
        				case '3':
        				case '4':
        				case '5':
        				case '6':
        				case '7':
        					{
        						alt3=2;
        					}
        				    break;

        				default:
        				    alt3=3;
        				}

        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 3;
        		    EXCEPTION->state        = 1;


        		    goto ruleOctalEscapeEx;

        		}

        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 3;
            EXCEPTION->state        = 0;


            goto ruleOctalEscapeEx;

        }

        switch (alt3)
        {
    	case 1:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:66:9: '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' )
    	    {
    	        MATCHC('\\');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleOctalEscapeEx;
    	        }


    	        if ( ((LA(1) >= '0') && (LA(1) <= '3')) )
    	        {
    	            CONSUME();
    	        }
    	        else
    	        {
    	            CONSTRUCTEX();
    	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	            LRECOVER();
    	            goto ruleOctalEscapeEx;
    	        }


    	        if ( ((LA(1) >= '0') && (LA(1) <= '7')) )
    	        {
    	            CONSUME();
    	        }
    	        else
    	        {
    	            CONSTRUCTEX();
    	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	            LRECOVER();
    	            goto ruleOctalEscapeEx;
    	        }


    	        if ( ((LA(1) >= '0') && (LA(1) <= '7')) )
    	        {
    	            CONSUME();
    	        }
    	        else
    	        {
    	            CONSTRUCTEX();
    	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	            LRECOVER();
    	            goto ruleOctalEscapeEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:67:9: '\\\\' ( '0' .. '7' ) ( '0' .. '7' )
    	    {
    	        MATCHC('\\');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleOctalEscapeEx;
    	        }


    	        if ( ((LA(1) >= '0') && (LA(1) <= '7')) )
    	        {
    	            CONSUME();
    	        }
    	        else
    	        {
    	            CONSTRUCTEX();
    	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	            LRECOVER();
    	            goto ruleOctalEscapeEx;
    	        }


    	        if ( ((LA(1) >= '0') && (LA(1) <= '7')) )
    	        {
    	            CONSUME();
    	        }
    	        else
    	        {
    	            CONSTRUCTEX();
    	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	            LRECOVER();
    	            goto ruleOctalEscapeEx;
    	        }


    	    }
    	    break;
    	case 3:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:68:9: '\\\\' ( '0' .. '7' )
    	    {
    	        MATCHC('\\');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleOctalEscapeEx;
    	        }


    	        if ( ((LA(1) >= '0') && (LA(1) <= '7')) )
    	        {
    	            CONSUME();
    	        }
    	        else
    	        {
    	            CONSTRUCTEX();
    	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	            LRECOVER();
    	            goto ruleOctalEscapeEx;
    	        }


    	    }
    	    break;

        }
    }

    // This is where rules clean up and exit
    //
    goto ruleOctalEscapeEx; /* Prevent compiler warnings */
    ruleOctalEscapeEx: ;

}
// $ANTLR end OctalEscape

//   Comes from: 70:5: ( ( 'a' .. 'z' | 'A' .. 'Z' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ID
 *
 * Looks to match the characters the constitute the token ID
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mID(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ID;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:70:5: ( ( 'a' .. 'z' | 'A' .. 'Z' )+ )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:70:9: ( 'a' .. 'z' | 'A' .. 'Z' )+
    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:70:9: ( 'a' .. 'z' | 'A' .. 'Z' )+
        {
            int cnt4=0;

            for (;;)
            {
                int alt4=2;
        	switch ( LA(1) )
        	{
        	case 'A':
        	case 'B':
        	case 'C':
        	case 'D':
        	case 'E':
        	case 'F':
        	case 'G':
        	case 'H':
        	case 'I':
        	case 'J':
        	case 'K':
        	case 'L':
        	case 'M':
        	case 'N':
        	case 'O':
        	case 'P':
        	case 'Q':
        	case 'R':
        	case 'S':
        	case 'T':
        	case 'U':
        	case 'V':
        	case 'W':
        	case 'X':
        	case 'Y':
        	case 'Z':
        	case 'a':
        	case 'b':
        	case 'c':
        	case 'd':
        	case 'e':
        	case 'f':
        	case 'g':
        	case 'h':
        	case 'i':
        	case 'j':
        	case 'k':
        	case 'l':
        	case 'm':
        	case 'n':
        	case 'o':
        	case 'p':
        	case 'q':
        	case 'r':
        	case 's':
        	case 't':
        	case 'u':
        	case 'v':
        	case 'w':
        	case 'x':
        	case 'y':
        	case 'z':
        		{
        			alt4=1;
        		}
        	    break;

        	}

        	switch (alt4)
        	{
        	    case 1:
        	        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:
        	        {
        	            if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleIDEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt4 >= 1 )
        		{
        		    goto loop4;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleIDEx;
        	}
        	cnt4++;
            }
            loop4: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIDEx; /* Prevent compiler warnings */
    ruleIDEx: ;

}
// $ANTLR end ID

//   Comes from: 71:7: ( ( 'md5' | 'MD5' | 'sha1' | 'SHA1' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start HASH
 *
 * Looks to match the characters the constitute the token HASH
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mHASH(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = HASH;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:71:7: ( ( 'md5' | 'MD5' | 'sha1' | 'SHA1' ) )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:71:11: ( 'md5' | 'MD5' | 'sha1' | 'SHA1' )
    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:71:11: ( 'md5' | 'MD5' | 'sha1' | 'SHA1' )
        {
            int alt5=4;
            switch ( LA(1) )
            {
            case 'm':
            	{
            		alt5=1;
            	}
                break;
            case 'M':
            	{
            		alt5=2;
            	}
                break;
            case 's':
            	{
            		alt5=3;
            	}
                break;
            case 'S':
            	{
            		alt5=4;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 5;
                EXCEPTION->state        = 0;


                goto ruleHASHEx;

            }

            switch (alt5)
            {
        	case 1:
        	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:71:12: 'md5'
        	    {
        	        MATCHS(lit_10);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleHASHEx;
        	        }




        	    }
        	    break;
        	case 2:
        	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:71:18: 'MD5'
        	    {
        	        MATCHS(lit_11);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleHASHEx;
        	        }




        	    }
        	    break;
        	case 3:
        	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:71:24: 'sha1'
        	    {
        	        MATCHS(lit_12);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleHASHEx;
        	        }




        	    }
        	    break;
        	case 4:
        	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:71:31: 'SHA1'
        	    {
        	        MATCHS(lit_13);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleHASHEx;
        	        }




        	    }
        	    break;

            }
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleHASHEx; /* Prevent compiler warnings */
    ruleHASHEx: ;

}
// $ANTLR end HASH

//   Comes from: 72:5: ( ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INT
 *
 * Looks to match the characters the constitute the token INT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINT(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INT;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:72:5: ( ( '0' .. '9' )+ )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:72:9: ( '0' .. '9' )+
    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:72:9: ( '0' .. '9' )+
        {
            int cnt6=0;

            for (;;)
            {
                int alt6=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt6=1;
        		}
        	    break;

        	}

        	switch (alt6)
        	{
        	    case 1:
        	        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleINTEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt6 >= 1 )
        		{
        		    goto loop6;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleINTEx;
        	}
        	cnt6++;
            }
            loop6: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleINTEx; /* Prevent compiler warnings */
    ruleINTEx: ;

}
// $ANTLR end INT

//   Comes from: 73:8: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NEWLINE
 *
 * Looks to match the characters the constitute the token NEWLINE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNEWLINE(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NEWLINE;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:73:8: ( ';' )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:73:10: ';'
    {
        MATCHC(';');
        if  (HASEXCEPTION())
        {
            goto ruleNEWLINEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNEWLINEEx; /* Prevent compiler warnings */
    ruleNEWLINEEx: ;

}
// $ANTLR end NEWLINE

//   Comes from: 74:5: ( ( ' ' | '\\t' | '\\n' | '\\r' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pHLINQLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:74:5: ( ( ' ' | '\\t' | '\\n' | '\\r' )+ )
    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:74:9: ( ' ' | '\\t' | '\\n' | '\\r' )+
    {
        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:74:9: ( ' ' | '\\t' | '\\n' | '\\r' )+
        {
            int cnt7=0;

            for (;;)
            {
                int alt7=2;
        	switch ( LA(1) )
        	{
        	case '\t':
        	case '\n':
        	case '\r':
        	case ' ':
        		{
        			alt7=1;
        		}
        	    break;

        	}

        	switch (alt7)
        	{
        	    case 1:
        	        // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:
        	        {
        	            if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt7 >= 1 )
        		{
        		    goto loop7;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt7++;
            }
            loop7: ;	/* Jump to here if this rule does not match */
        }

        {
            LEXSTATE->channel=HIDDEN;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pHLINQLexer ctx)
{
    {
        //  D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:8: ( T__13 | T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | STRING_LITERAL | ID | HASH | INT | NEWLINE | WS )

        ANTLR3_UINT32 alt8;

        alt8=18;

        switch ( LA(1) )
        {
        case '+':
        	{
        		alt8=1;
        	}
            break;
        case '.':
        	{
        		alt8=2;
        	}
            break;
        case '=':
        	{
        		alt8=3;
        	}
            break;
        case 'c':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'p':
        					{
        						switch ( LA(4) )
        						{
        						case 'y':
        							{
        								switch ( LA(5) )
        								{
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt8=14;
        									}
        								    break;

        								default:
        								    alt8=4;
        								}

        							}
        						    break;

        						default:
        						    alt8=14;
        						}

        					}
        				    break;

        				default:
        				    alt8=14;
        				}

        			}
        		    break;

        		default:
        		    alt8=14;
        		}

        	}
            break;
        case 'd':
        	{
        		switch ( LA(2) )
        		{
        		case 'e':
        			{
        				switch ( LA(3) )
        				{
        				case 'l':
        					{
        						switch ( LA(4) )
        						{
        						case 'e':
        							{
        								switch ( LA(5) )
        								{
        								case 't':
        									{
        										switch ( LA(6) )
        										{
        										case 'e':
        											{
        												switch ( LA(7) )
        												{
        												case 'A':
        												case 'B':
        												case 'C':
        												case 'D':
        												case 'E':
        												case 'F':
        												case 'G':
        												case 'H':
        												case 'I':
        												case 'J':
        												case 'K':
        												case 'L':
        												case 'M':
        												case 'N':
        												case 'O':
        												case 'P':
        												case 'Q':
        												case 'R':
        												case 'S':
        												case 'T':
        												case 'U':
        												case 'V':
        												case 'W':
        												case 'X':
        												case 'Y':
        												case 'Z':
        												case 'a':
        												case 'b':
        												case 'c':
        												case 'd':
        												case 'e':
        												case 'f':
        												case 'g':
        												case 'h':
        												case 'i':
        												case 'j':
        												case 'k':
        												case 'l':
        												case 'm':
        												case 'n':
        												case 'o':
        												case 'p':
        												case 'q':
        												case 'r':
        												case 's':
        												case 't':
        												case 'u':
        												case 'v':
        												case 'w':
        												case 'x':
        												case 'y':
        												case 'z':
        													{
        														alt8=14;
        													}
        												    break;

        												default:
        												    alt8=5;
        												}

        											}
        										    break;

        										default:
        										    alt8=14;
        										}

        									}
        								    break;

        								default:
        								    alt8=14;
        								}

        							}
        						    break;

        						default:
        						    alt8=14;
        						}

        					}
        				    break;

        				default:
        				    alt8=14;
        				}

        			}
        		    break;
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'A':
        				case 'B':
        				case 'C':
        				case 'D':
        				case 'E':
        				case 'F':
        				case 'G':
        				case 'H':
        				case 'I':
        				case 'J':
        				case 'K':
        				case 'L':
        				case 'M':
        				case 'N':
        				case 'O':
        				case 'P':
        				case 'Q':
        				case 'R':
        				case 'S':
        				case 'T':
        				case 'U':
        				case 'V':
        				case 'W':
        				case 'X':
        				case 'Y':
        				case 'Z':
        				case 'a':
        				case 'b':
        				case 'c':
        				case 'd':
        				case 'e':
        				case 'f':
        				case 'g':
        				case 'h':
        				case 'i':
        				case 'j':
        				case 'k':
        				case 'l':
        				case 'm':
        				case 'n':
        				case 'o':
        				case 'p':
        				case 'q':
        				case 'r':
        				case 's':
        				case 't':
        				case 'u':
        				case 'v':
        				case 'w':
        				case 'x':
        				case 'y':
        				case 'z':
        					{
        						alt8=14;
        					}
        				    break;

        				default:
        				    alt8=6;
        				}

        			}
        		    break;

        		default:
        		    alt8=14;
        		}

        	}
            break;
        case 'f':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'r':
        					{
        						switch ( LA(4) )
        						{
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'U':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case 'a':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt8=14;
        							}
        						    break;

        						default:
        						    alt8=7;
        						}

        					}
        				    break;

        				default:
        				    alt8=14;
        				}

        			}
        		    break;

        		default:
        		    alt8=14;
        		}

        	}
            break;
        case 'i':
        	{
        		switch ( LA(2) )
        		{
        		case 'n':
        			{
        				switch ( LA(3) )
        				{
        				case 'A':
        				case 'B':
        				case 'C':
        				case 'D':
        				case 'E':
        				case 'F':
        				case 'G':
        				case 'H':
        				case 'I':
        				case 'J':
        				case 'K':
        				case 'L':
        				case 'M':
        				case 'N':
        				case 'O':
        				case 'P':
        				case 'Q':
        				case 'R':
        				case 'S':
        				case 'T':
        				case 'U':
        				case 'V':
        				case 'W':
        				case 'X':
        				case 'Y':
        				case 'Z':
        				case 'a':
        				case 'b':
        				case 'c':
        				case 'd':
        				case 'e':
        				case 'f':
        				case 'g':
        				case 'h':
        				case 'i':
        				case 'j':
        				case 'k':
        				case 'l':
        				case 'm':
        				case 'n':
        				case 'o':
        				case 'p':
        				case 'q':
        				case 'r':
        				case 's':
        				case 't':
        				case 'u':
        				case 'v':
        				case 'w':
        				case 'x':
        				case 'y':
        				case 'z':
        					{
        						alt8=14;
        					}
        				    break;

        				default:
        				    alt8=8;
        				}

        			}
        		    break;

        		default:
        		    alt8=14;
        		}

        	}
            break;
        case 'm':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'v':
        					{
        						switch ( LA(4) )
        						{
        						case 'e':
        							{
        								switch ( LA(5) )
        								{
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt8=14;
        									}
        								    break;

        								default:
        								    alt8=9;
        								}

        							}
        						    break;

        						default:
        						    alt8=14;
        						}

        					}
        				    break;

        				default:
        				    alt8=14;
        				}

        			}
        		    break;
        		case 'd':
        			{
        				switch ( LA(3) )
        				{
        				case '5':
        					{
        						alt8=15;
        					}
        				    break;

        				default:
        				    alt8=14;
        				}

        			}
        		    break;

        		default:
        		    alt8=14;
        		}

        	}
            break;
        case 'p':
        	{
        		switch ( LA(2) )
        		{
        		case 'r':
        			{
        				switch ( LA(3) )
        				{
        				case 'i':
        					{
        						switch ( LA(4) )
        						{
        						case 'n':
        							{
        								switch ( LA(5) )
        								{
        								case 't':
        									{
        										switch ( LA(6) )
        										{
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt8=14;
        											}
        										    break;

        										default:
        										    alt8=10;
        										}

        									}
        								    break;

        								default:
        								    alt8=14;
        								}

        							}
        						    break;

        						default:
        						    alt8=14;
        						}

        					}
        				    break;

        				default:
        				    alt8=14;
        				}

        			}
        		    break;

        		default:
        		    alt8=14;
        		}

        	}
            break;
        case 'r':
        	{
        		switch ( LA(2) )
        		{
        		case 'e':
        			{
        				switch ( LA(3) )
        				{
        				case 'c':
        					{
        						switch ( LA(4) )
        						{
        						case 'u':
        							{
        								switch ( LA(5) )
        								{
        								case 'r':
        									{
        										switch ( LA(6) )
        										{
        										case 's':
        											{
        												switch ( LA(7) )
        												{
        												case 'i':
        													{
        														switch ( LA(8) )
        														{
        														case 'v':
        															{
        																switch ( LA(9) )
        																{
        																case 'e':
        																	{
        																		switch ( LA(10) )
        																		{
        																		case 'l':
        																			{
        																				switch ( LA(11) )
        																				{
        																				case 'y':
        																					{
        																						switch ( LA(12) )
        																						{
        																						case 'A':
        																						case 'B':
        																						case 'C':
        																						case 'D':
        																						case 'E':
        																						case 'F':
        																						case 'G':
        																						case 'H':
        																						case 'I':
        																						case 'J':
        																						case 'K':
        																						case 'L':
        																						case 'M':
        																						case 'N':
        																						case 'O':
        																						case 'P':
        																						case 'Q':
        																						case 'R':
        																						case 'S':
        																						case 'T':
        																						case 'U':
        																						case 'V':
        																						case 'W':
        																						case 'X':
        																						case 'Y':
        																						case 'Z':
        																						case 'a':
        																						case 'b':
        																						case 'c':
        																						case 'd':
        																						case 'e':
        																						case 'f':
        																						case 'g':
        																						case 'h':
        																						case 'i':
        																						case 'j':
        																						case 'k':
        																						case 'l':
        																						case 'm':
        																						case 'n':
        																						case 'o':
        																						case 'p':
        																						case 'q':
        																						case 'r':
        																						case 's':
        																						case 't':
        																						case 'u':
        																						case 'v':
        																						case 'w':
        																						case 'x':
        																						case 'y':
        																						case 'z':
        																							{
        																								alt8=14;
        																							}
        																						    break;

        																						default:
        																						    alt8=11;
        																						}

        																					}
        																				    break;

        																				default:
        																				    alt8=14;
        																				}

        																			}
        																		    break;

        																		default:
        																		    alt8=14;
        																		}

        																	}
        																    break;

        																default:
        																    alt8=14;
        																}

        															}
        														    break;

        														default:
        														    alt8=14;
        														}

        													}
        												    break;

        												default:
        												    alt8=14;
        												}

        											}
        										    break;

        										default:
        										    alt8=14;
        										}

        									}
        								    break;

        								default:
        								    alt8=14;
        								}

        							}
        						    break;

        						default:
        						    alt8=14;
        						}

        					}
        				    break;

        				default:
        				    alt8=14;
        				}

        			}
        		    break;

        		default:
        		    alt8=14;
        		}

        	}
            break;
        case 'w':
        	{
        		switch ( LA(2) )
        		{
        		case 'h':
        			{
        				switch ( LA(3) )
        				{
        				case 'e':
        					{
        						switch ( LA(4) )
        						{
        						case 'r':
        							{
        								switch ( LA(5) )
        								{
        								case 'e':
        									{
        										switch ( LA(6) )
        										{
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt8=14;
        											}
        										    break;

        										default:
        										    alt8=12;
        										}

        									}
        								    break;

        								default:
        								    alt8=14;
        								}

        							}
        						    break;

        						default:
        						    alt8=14;
        						}

        					}
        				    break;

        				default:
        				    alt8=14;
        				}

        			}
        		    break;

        		default:
        		    alt8=14;
        		}

        	}
            break;
        case '"':
        	{
        		alt8=13;
        	}
            break;
        case 'M':
        	{
        		switch ( LA(2) )
        		{
        		case 'D':
        			{
        				switch ( LA(3) )
        				{
        				case '5':
        					{
        						alt8=15;
        					}
        				    break;

        				default:
        				    alt8=14;
        				}

        			}
        		    break;

        		default:
        		    alt8=14;
        		}

        	}
            break;
        case 's':
        	{
        		switch ( LA(2) )
        		{
        		case 'h':
        			{
        				switch ( LA(3) )
        				{
        				case 'a':
        					{
        						switch ( LA(4) )
        						{
        						case '1':
        							{
        								alt8=15;
        							}
        						    break;

        						default:
        						    alt8=14;
        						}

        					}
        				    break;

        				default:
        				    alt8=14;
        				}

        			}
        		    break;

        		default:
        		    alt8=14;
        		}

        	}
            break;
        case 'S':
        	{
        		switch ( LA(2) )
        		{
        		case 'H':
        			{
        				switch ( LA(3) )
        				{
        				case 'A':
        					{
        						switch ( LA(4) )
        						{
        						case '1':
        							{
        								alt8=15;
        							}
        						    break;

        						default:
        						    alt8=14;
        						}

        					}
        				    break;

        				default:
        				    alt8=14;
        				}

        			}
        		    break;

        		default:
        		    alt8=14;
        		}

        	}
            break;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case 'a':
        case 'b':
        case 'e':
        case 'g':
        case 'h':
        case 'j':
        case 'k':
        case 'l':
        case 'n':
        case 'o':
        case 'q':
        case 't':
        case 'u':
        case 'v':
        case 'x':
        case 'y':
        case 'z':
        	{
        		alt8=14;
        	}
            break;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt8=16;
        	}
            break;
        case ';':
        	{
        		alt8=17;
        	}
            break;
        case '\t':
        case '\n':
        case '\r':
        case ' ':
        	{
        		alt8=18;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 8;
            EXCEPTION->state        = 0;


            goto ruleTokensEx;

        }

        switch (alt8)
        {
    	case 1:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:10: T__13
    	    {
    	        /* 1:10: T__13 */
    	        mT__13(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:16: T__14
    	    {
    	        /* 1:16: T__14 */
    	        mT__14(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:22: T__15
    	    {
    	        /* 1:22: T__15 */
    	        mT__15(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:28: T__16
    	    {
    	        /* 1:28: T__16 */
    	        mT__16(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:34: T__17
    	    {
    	        /* 1:34: T__17 */
    	        mT__17(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:40: T__18
    	    {
    	        /* 1:40: T__18 */
    	        mT__18(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:46: T__19
    	    {
    	        /* 1:46: T__19 */
    	        mT__19(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:52: T__20
    	    {
    	        /* 1:52: T__20 */
    	        mT__20(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:58: T__21
    	    {
    	        /* 1:58: T__21 */
    	        mT__21(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:64: T__22
    	    {
    	        /* 1:64: T__22 */
    	        mT__22(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:70: T__23
    	    {
    	        /* 1:70: T__23 */
    	        mT__23(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:76: T__24
    	    {
    	        /* 1:76: T__24 */
    	        mT__24(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:82: STRING_LITERAL
    	    {
    	        /* 1:82: STRING_LITERAL */
    	        mSTRING_LITERAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:97: ID
    	    {
    	        /* 1:97: ID */
    	        mID(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:100: HASH
    	    {
    	        /* 1:100: HASH */
    	        mHASH(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:105: INT
    	    {
    	        /* 1:105: INT */
    	        mINT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:109: NEWLINE
    	    {
    	        /* 1:109: NEWLINE */
    	        mNEWLINE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // D:\\hg\\hc\\src\\hlinq\\HLINQ.g:1:117: WS
    	    {
    	        /* 1:117: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
