stages:
  - build
  - test
  
job_build:
  stage: build
  script:
    - build.bat
  cache:
     paths:
      - src/x64/Release/
  artifacts:
     paths:
       - src/x64/Release/*.exe

job_test:
  stage: test
  script:
    - src\x64\Release\_tst.exe