types:
  - build

build:
  type: build
  script:
    - 'C:\Multi-Runner\nuget.exe restore src/linq2hash.sln' # restore Nuget dependencies
    - 'xcopy C:\code\linq2hash\External External /S /Y'
    - ./build.bat
  artifacts:
     name: "%CI_BUILD_REF_NAME%_%CI_BUILD_ID%"
     expire_in: 1 week
     reports:
       junit: ./src/x64/Release/_tst.xml
     paths:
       - ./src/x64/Release/*.exe
       - ./src/Release/*.exe