# version format
version: 5.0.{build}.0

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

# environment variables
environment:
  Major: 5
  Minor: 0
  Build: $(APPVEYOR_BUILD_NUMBER)
  Revision: 0
  NSIS_ROOT: C:\Program Files (x86)\NSIS
  WINDDK: C:\Program Files (x86)\Windows Kits\8.1
  VS160COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\
  VisualStudioVersion: 16.0
  MultiProcessorCompilation: true
  # SignTool renamed so as to disable signing
  SignTool_: C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe
  # this is how to set encrypted variable. Go to "Encrypt data" page in account menu to encrypt data.
  CertPassword:
    secure: 5n0HdCq2h73RfJa+kz2bHA==
  PfxUri:
    secure: 96Uy0sDkAp6sTkaD5MptudqaMXrjJkaBQhghxNHvaP9vHbUOcF1R9h9k3LXG6Znw3T/ZU+090sYOayq7AFv1hOLFxAT15mZ5PdQg3X6lYRr7xrDrNTtAqmeYrKD+So90
  NsisUri: https://docs.google.com/uc?authuser=0&id=0B1S8jEQ5nWZXbzBsUTJ6Rjh1U3M&export=download
  AprUri: https://onedrive.live.com/download.aspx?cid=7AED9860EB60149D&authKey=%21ACwvZk2I6%5FH7RdM&resid=7AED9860EB60149D%219172&canary=aPJop93QcphvESZVJCh7hLZqIEOmvto9OVyZiSGV5sY%3D7&ithint=%2Erar
  OpenSslUri: https://docs.google.com/uc?authuser=0&id=0B1S8jEQ5nWZXbXlvMkhTSUFrRkE&export=download
  LibIntlUri: https://docs.google.com/uc?authuser=0&id=0B1S8jEQ5nWZXdkk3cUlfOTUzbnc&export=download

build_cloud: EGOROFF
image: Windows
  
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

install:
  - cmd: nuget restore src\linq2hash.sln -verbosity detailed

platform: Any CPU

configuration: Release

before_build:
  - xcopy C:\code\linq2hash\External External /S /Y
  - cd "/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build"
  - vcvars64.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - set PROJECT_BASE_PATH=%APPVEYOR_BUILD_FOLDER%\src
  - set BINPLACE_PLACEFILE=%APPVEYOR_BUILD_FOLDER%\binplace.txt
  - set HC_TEST_DIR=%APPVEYOR_BUILD_FOLDER%\_tst.net
  - set

build:
    project: src\hc.xml
    verbosity: normal
    parallel: false

test: off

after_build:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path src\x64\Release\_tst.xml))

artifacts:
  - path: src\Install\$(configuration)\*.exe
  - path: src\hc.*.zip

