"C:\Program Files\NSIS\makensis.exe"  /NOTIFYHWND 131948 /DConfiguration=Debug /DArch=x86 /DPRODUCT_VERSION=%1 "mainMd4.nsi"
"C:\Program Files\NSIS\makensis.exe"  /NOTIFYHWND 131948 /DConfiguration=Debug /DArch=x86 /DPRODUCT_VERSION=%1 "mainMd5.nsi"
"C:\Program Files\NSIS\makensis.exe"  /NOTIFYHWND 131948 /DConfiguration=Debug /DArch=x86 /DPRODUCT_VERSION=%1 "mainSha1.nsi"
"C:\Program Files\NSIS\makensis.exe"  /NOTIFYHWND 131948 /DConfiguration=Debug /DArch=x86 /DPRODUCT_VERSION=%1 "mainSha256.nsi"
"C:\Program Files\NSIS\makensis.exe"  /NOTIFYHWND 131948 /DConfiguration=Debug /DArch=x86 /DPRODUCT_VERSION=%1 "mainSha384.nsi"
"C:\Program Files\NSIS\makensis.exe"  /NOTIFYHWND 131948 /DConfiguration=Debug /DArch=x86 /DPRODUCT_VERSION=%1 "mainSha512.nsi"
"C:\Program Files\NSIS\makensis.exe"  /NOTIFYHWND 131948 /DConfiguration=Debug /DArch=x86 /DPRODUCT_VERSION=%1 "mainWhirlpool.nsi"

"C:\Program Files\NSIS\makensis.exe"  /NOTIFYHWND 131948 /DConfiguration=Debug /DArch=x64 /DPRODUCT_VERSION=%1 "mainMd4.nsi"
"C:\Program Files\NSIS\makensis.exe"  /NOTIFYHWND 131948 /DConfiguration=Debug /DArch=x64 /DPRODUCT_VERSION=%1 "mainMd5.nsi"
"C:\Program Files\NSIS\makensis.exe"  /NOTIFYHWND 131948 /DConfiguration=Debug /DArch=x64 /DPRODUCT_VERSION=%1 "mainSha1.nsi"
"C:\Program Files\NSIS\makensis.exe"  /NOTIFYHWND 131948 /DConfiguration=Debug /DArch=x64 /DPRODUCT_VERSION=%1 "mainSha256.nsi"
"C:\Program Files\NSIS\makensis.exe"  /NOTIFYHWND 131948 /DConfiguration=Debug /DArch=x64 /DPRODUCT_VERSION=%1 "mainSha384.nsi"
"C:\Program Files\NSIS\makensis.exe"  /NOTIFYHWND 131948 /DConfiguration=Debug /DArch=x64 /DPRODUCT_VERSION=%1 "mainSha512.nsi"
"C:\Program Files\NSIS\makensis.exe"  /NOTIFYHWND 131948 /DConfiguration=Debug /DArch=x64 /DPRODUCT_VERSION=%1 "mainWhirlpool.nsi"