LangString PROGRAM_NAME ${LANG_ENGLISH} "Hash LINQ"
LangString PROGRAM_NAME ${LANG_RUSSIAN} "Hash LINQ"
LangString PROGRAM_SITE ${LANG_ENGLISH} "Hash LINQ site"
LangString PROGRAM_SITE ${LANG_RUSSIAN} "Сайт Hash LINQ"