LangString PROGRAM_NAME ${LANG_ENGLISH} "Hash calculators"
LangString PROGRAM_NAME ${LANG_RUSSIAN} "Хэш калькуляторы"
LangString PROGRAM_SITE ${LANG_ENGLISH} "Hash calculators site"
LangString PROGRAM_SITE ${LANG_RUSSIAN} "Сайт хэш калькуляторов"
LangString README_FILE_MD4 ${LANG_ENGLISH} "Readme.md4.en.txt"
LangString README_FILE_MD4 ${LANG_RUSSIAN} "Readme.md4.ru.txt"
LangString README_FILE_MD5 ${LANG_ENGLISH} "Readme.md5.en.txt"
LangString README_FILE_MD5 ${LANG_RUSSIAN} "Readme.md5.ru.txt"
LangString README_FILE_SHA1 ${LANG_ENGLISH} "Readme.sha1.en.txt"
LangString README_FILE_SHA1 ${LANG_RUSSIAN} "Readme.sha1.ru.txt"