; Script generated by the HM NIS Edit Script Wizard.

!define LowCaseName "hc"
!define LangStrFileSuffix "HLINQ"

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "Hash Calculator"

!include "mainTemplate.nsi"