/*!
 * \brief   The file contains Hash LINQ implementation
 * \author  \verbatim
            Created by: Alexander Egorov
            \endverbatim
 * \date    \verbatim
            Creation date: 2011-11-14
            \endverbatim
 * Copyright: (c) Alexander Egorov 2011
 */

#include "targetver.h"
#include "hlinq.h"

#ifdef WIN32
#include "..\srclib\DebugHelplers.h"
#endif

#define ERROR_BUFFER_SIZE 2 * BINARY_THOUSAND
#define LINE_FEED '\n'

#define HLP_OPT_BEGIN "  -%c [ --%s ] "
#define HLP_OPT_END "\t\t%s" NEW_LINE NEW_LINE
#define HLP_ARG HLP_OPT_BEGIN "arg" HLP_OPT_END
#define HLP_NO_ARG HLP_OPT_BEGIN HLP_OPT_END

#define PATH_ELT_SEPARATOR '\\'
#define NUMBER_PARAM_FMT_STRING "%lu"
#define BIG_NUMBER_PARAM_FMT_STRING "%llu"

#define INVALID_DIGIT_PARAMETER "Invalid parameter --%s %s. Must be number" NEW_LINE
#define INCOMPATIBLE_OPTIONS_HEAD "Incompatible options: "

#define OPT_HELP '?'
#define OPT_FILE 'f'
#define OPT_QUERY 'q'
#define OPT_VALIDATE 'v'
#define OPT_TIME 't'

#define MAX_LINE_SIZE 32 * BINARY_THOUSAND - 1

static struct apr_getopt_option_t options[] = {
    {"file", OPT_FILE, TRUE, "full path to query source file"},
    {"query", OPT_QUERY, TRUE, "query text"},
    {"validate", OPT_VALIDATE, FALSE, "only validate syntax. Do not run actions"},
    {"time", OPT_TIME, FALSE, "show calculation time (false by default)"},
    {"help", OPT_HELP, FALSE, "show help message"}
};

int main(int argc, const char* const argv[])
{
    apr_pool_t* pool = NULL;
    apr_getopt_t* opt = NULL;
    int c = 0;
    const char* optarg = NULL;
    apr_status_t status = APR_SUCCESS;
    const char* file = NULL;
    const char* query = NULL;
    BOOL onlyValidate = FALSE;
    BOOL isPrintCalcTime = FALSE;

    pANTLR3_INPUT_STREAM input;
    pHLINQLexer lxr;
    pANTLR3_COMMON_TOKEN_STREAM tstream;
    pHLINQParser psr;
    pANTLR3_COMMON_TREE_NODE_STREAM nodes;
    pHLINQWalker		    treePsr;

    HLINQParser_prog_return	    ast;

#ifdef WIN32
#ifndef _DEBUG  // only Release configuration dump generating
    SetUnhandledExceptionFilter(TopLevelFilter);
#endif
#endif

    setlocale(LC_ALL, ".ACP");
    setlocale(LC_NUMERIC, "C");

    status = apr_app_initialize(&argc, &argv, NULL);
    if (status != APR_SUCCESS) {
        CrtPrintf("Couldn't initialize APR");
        NewLine();
        PrintError(status);
        return EXIT_FAILURE;
    }
    atexit(apr_terminate);
    apr_pool_create(&pool, NULL);
    apr_getopt_init(&opt, pool, argc, argv);

    while ((status = apr_getopt_long(opt, options, &c, &optarg)) == APR_SUCCESS) {
        switch (c) {
            case OPT_HELP:
                PrintUsage();
                goto cleanup;
            case OPT_FILE:
                file = apr_pstrdup(pool, optarg);
                break;
            case OPT_QUERY:
                query = apr_pstrdup(pool, optarg);
                break;
            case OPT_VALIDATE:
                onlyValidate = TRUE;
                break;
            case OPT_TIME:
                isPrintCalcTime = TRUE;
                break;
        }
    }

    if ((status != APR_EOF) || (argc < 2)) {
        PrintUsage();
        goto cleanup;
    }

    if (file == NULL && query == NULL) {
        PrintCopyright();
        CrtPrintf("file or query must be specified" NEW_LINE);
        goto cleanup;
    }

    input   = query == NULL 
        ? antlr3FileStreamNew(file, ANTLR3_ENC_UTF8) 
        : antlr3StringStreamNew(query, ANTLR3_ENC_UTF8, strlen(query), "");

    if (input == NULL) {
        PrintCopyright();
        CrtPrintf("Unable to open file %s" NEW_LINE, file);
        goto cleanup;
    }

    lxr     = HLINQLexerNew(input);     // HLINQLexerNew is generated by ANTLR
    tstream = antlr3CommonTokenStreamSourceNew(ANTLR3_SIZE_HINT, TOKENSOURCE(lxr));
    psr     = HLINQParserNew(tstream);  // HLINQParserNew is generated by ANTLR3
    ast = psr->prog(psr);

    if (psr->pParser->rec->state->errorCount > 0) {
		CrtPrintf("%d syntax error(s) found. Query aborted." NEW_LINE, psr->pParser->rec->state->errorCount);
    } else if (ast.tree != NULL) {
        nodes	= antlr3CommonTreeNodeStreamNewTree(ast.tree, ANTLR3_SIZE_HINT); // sIZE HINT WILL SOON BE DEPRECATED!!

		// Tree parsers are given a common tree node stream (or your override)
		//
		treePsr	= HLINQWalkerNew(nodes);

        treePsr->prog(treePsr, pool, onlyValidate, isPrintCalcTime);
		nodes->free(nodes); nodes = NULL;
		treePsr ->free  (treePsr);	    treePsr	= NULL;
    }

    psr->free(psr);
    psr = NULL;
    tstream->free(tstream);
    tstream = NULL;
    lxr->free(lxr);
    lxr = NULL;
    input->close(input);
    input = NULL;
cleanup:
    apr_pool_destroy(pool);
    return EXIT_SUCCESS;
}

void PrintUsage(void)
{
    int i = 0;
    PrintCopyright();
    CrtPrintf("usage: " PROGRAM_NAME " [OPTION] ..." NEW_LINE NEW_LINE "Options:" NEW_LINE NEW_LINE);
    for (; i < sizeof(options) / sizeof(apr_getopt_option_t); ++i) {
        CrtPrintf(options[i].has_arg ? HLP_ARG : HLP_NO_ARG,
                  (char)options[i].optch, options[i].name, options[i].description);
    }
}

void PrintCopyright(void)
{
    CrtPrintf(COPYRIGHT_FMT, APP_NAME);
}