#ifndef L2H_C_H_
#define L2H_C_H_

/*
 * translate-c root for the l2h Zig port.
 *
 * l2h.tab.h is generated by bison; its %code requires block pulls in
 * <stdarg.h>, <stdio.h> and frontend.h, so translate-c sees the YYSTYPE/YYLTYPE
 * types, every token constant (FROM, SELECT, REL_OP, ...) and the extern
 * declarations of the fend_on_* callbacks the parser invokes.
 *
 * l2h.flex.h is generated by flex and exposes the lexer entry points.
 */

#include "l2h.tab.h"
#include "l2h.flex.h"

/* Location-tracking externs defined in the generated lexer. */
extern int yylineno;
extern int yycolumn;

#endif /* L2H_C_H_ */
