//! Command line interface for the `l2h` executable.
//!
//! Yazap mirrors the hand-rolled argv layout: `-q/--query`, `-f/--file`, and
//! no options means read the query from standard input. Help is generated by
//! yazap (`l2h -h`).

const std = @import("std");
const builtin = @import("builtin");
const yazap = @import("yazap");
const build_options = @import("build_options");
const lib = @import("lib");

const App = yazap.App;
const Arg = yazap.Arg;
const ArgMatches = yazap.ArgMatches;
const YazapStdoutRedirect = lib.YazapStdoutRedirect;

pub const PROGRAM_NAME = "l2h";

pub const opt_query = "query";
pub const opt_file = "file";

/// Where the query text comes from after successful parse.
pub const Input = union(enum) {
    query: []const u8,
    file: []const u8,
    stdin,
};

pub const Outcome = union(enum) {
    ok: Input,
    invalid_options,
};

fn productVersion() []const u8 {
    return build_options.version;
}

fn appName() []const u8 {
    return "Hash Query";
}

/// Architecture suffix for the help/copyright banner (same mapping as `hc`).
fn archSuffix() []const u8 {
    return switch (builtin.cpu.arch) {
        .x86_64 => "x64",
        .aarch64 => "arm64",
        .x86 => "x86",
        else => "native",
    };
}

fn valueOption(
    name: []const u8,
    short_name: u8,
    description: []const u8,
    placeholder: []const u8,
) Arg {
    var a = Arg.singleValueOption(name, short_name, description);
    a.setProperty(.allow_empty_value);
    a.setValuePlaceholder(placeholder);
    return a;
}

fn createApp(allocator: std.mem.Allocator) !*App {
    const app = try allocator.create(App);
    errdefer allocator.destroy(app);

    const descr = try std.fmt.allocPrint(
        allocator,
        "{s} {s} {s}\nCopyright (C) 2009-2026 Alexander Egorov. All rights reserved.",
        .{ appName(), productVersion(), archSuffix() },
    );
    app.* = App.init(allocator, PROGRAM_NAME, descr);

    var root = app.rootCommand();
    // Do not set help_on_empty_args: empty argv means stdin, not help.
    try root.addArg(valueOption(
        opt_query,
        'q',
        "query text from the command line",
        "query",
    ));
    try root.addArg(valueOption(
        opt_file,
        'f',
        "query from a file",
        "file",
    ));

    return app;
}

/// Short names of options that take a value.
const value_option_short = [_]u8{ 'q', 'f' };

/// Long names of options that take a value.
const value_option_long = [_][]const u8{ "query", "file" };

/// True when `tok` is a bare value-expecting option token with no attached
/// value (e.g. `-q` or `--query` but not `-q=x` or `-qx`).
fn isBareValueOption(tok: []const u8) bool {
    if (tok.len == 2 and tok[0] == '-') {
        for (value_option_short) |c| if (tok[1] == c) return true;
        return false;
    }
    if (std.mem.startsWith(u8, tok, "--") and std.mem.indexOfScalar(u8, tok, '=') == null) {
        const name = tok[2..];
        for (value_option_long) |n| if (std.mem.eql(u8, name, n)) return true;
        return false;
    }
    return false;
}

fn shouldAttach(opt_tok: []const u8, next_tok: []const u8) bool {
    // yazap skips empty argv elements; rewrite `-q ""` into `-q=` so an empty
    // query is captured (same approach as hc's normalizeArgv).
    return isBareValueOption(opt_tok) and next_tok.len == 0;
}

fn inputFromMatches(matches: ArgMatches) Input {
    // Prefer -q over -f when both are present (same as the hand-rolled parser).
    if (matches.getSingleValue(opt_query)) |q| return .{ .query = q };
    if (matches.getSingleValue(opt_file)) |f| return .{ .file = f };
    return .stdin;
}

/// Parses argv. Returns the query input source, or `invalid_options` when yazap
/// rejects the argv (it already printed a diagnostic). `-h/--help` never
/// returns: yazap prints help and exits.
pub fn run(
    allocator: std.mem.Allocator,
    io: std.Io,
    argv: []const [:0]const u8,
) !Outcome {
    const app = try createApp(allocator);
    defer {
        app.deinit();
        allocator.destroy(app);
    }

    const argv_norm = try lib.normalizeArgv(allocator, argv, shouldAttach);

    const matches = blk: {
        const yazap_out = try YazapStdoutRedirect.begin();
        defer yazap_out.restore();
        break :blk app.parseFrom(io, argv_norm) catch |err| switch (err) {
            error.UnrecognizedCommand,
            error.SubcommandNotProvided,
            error.UnrecognizedOption,
            error.OptionValueNotProvided,
            error.UnexpectedOptionValue,
            error.EmptyOptionValue,
            error.InvalidOptionValue,
            error.TooFewOptionValue,
            error.TooManyOptionValue,
            error.PositionalArgumentNotProvided,
            => return .invalid_options,
            else => return err,
        };
    };

    return .{ .ok = inputFromMatches(matches) };
}

test "query option selects query input" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const argv = [_][:0]const u8{ "-q", "from string s in \"a\" select s.md5;" };
    const outcome = try run(arena.allocator(), std.testing.io, &argv);
    try std.testing.expectEqualDeep(Outcome{
        .ok = .{ .query = "from string s in \"a\" select s.md5;" },
    }, outcome);
}

test "file option selects file input" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const argv = [_][:0]const u8{ "-f", "query.l2h" };
    const outcome = try run(arena.allocator(), std.testing.io, &argv);
    try std.testing.expectEqualDeep(Outcome{ .ok = .{ .file = "query.l2h" } }, outcome);
}

test "long options work" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const argv = [_][:0]const u8{ "--query", "x;" };
    const outcome = try run(arena.allocator(), std.testing.io, &argv);
    try std.testing.expectEqualDeep(Outcome{ .ok = .{ .query = "x;" } }, outcome);
}

test "empty argv selects stdin" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const outcome = try run(arena.allocator(), std.testing.io, &.{});
    try std.testing.expectEqualDeep(Outcome{ .ok = .stdin }, outcome);
}

test "query wins over file when both given" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const argv = [_][:0]const u8{ "-f", "a.l2h", "-q", "y;" };
    const outcome = try run(arena.allocator(), std.testing.io, &argv);
    try std.testing.expectEqualDeep(Outcome{ .ok = .{ .query = "y;" } }, outcome);
}

test "unknown option is rejected" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const argv = [_][:0]const u8{ "-z", "nope" };
    const outcome = try run(arena.allocator(), std.testing.io, &argv);
    try std.testing.expectEqual(Outcome.invalid_options, outcome);
}

test "empty query value is accepted" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const argv = [_][:0]const u8{ "-q", "" };
    const outcome = try run(arena.allocator(), std.testing.io, &argv);
    try std.testing.expectEqualDeep(Outcome{ .ok = .{ .query = "" } }, outcome);
}
