//! Command line interface for the `l2h` executable.
//!
//! Options: `-q/--query`, `-f/--file`; no options means read the query from
//! standard input. `-n/--syntax-check` parses and type-checks without executing.
//! Help is generated by yazap (`l2h -h`).

const std = @import("std");
const yazap = @import("yazap");
const lib = @import("lib");

const App = yazap.App;
const Arg = yazap.Arg;
const ArgMatches = yazap.ArgMatches;
const YazapStdoutRedirect = lib.YazapStdoutRedirect;

pub const PROGRAM_NAME = "l2h";

pub const opt_query = "query";
pub const opt_file = "file";
pub const opt_syntax_check = "syntax-check";

/// Where the query text comes from after successful parse.
pub const Input = union(enum) {
    query: []const u8,
    file: []const u8,
    stdin,
};

/// Parsed CLI: query source plus whether to skip interpretation.
pub const RunResult = struct {
    input: Input,
    syntax_check: bool,
};

fn appName() []const u8 {
    return "Hash Query";
}

fn valueOption(
    name: []const u8,
    short_name: u8,
    description: []const u8,
    placeholder: []const u8,
) Arg {
    var a = Arg.singleValueOption(name, short_name, description);
    a.setProperty(.allow_empty_value);
    a.setValuePlaceholder(placeholder);
    return a;
}

fn createApp(allocator: std.mem.Allocator) !*App {
    const app = try allocator.create(App);
    errdefer allocator.destroy(app);

    const descr = try lib.productBanner(allocator, appName());
    app.* = App.init(allocator, PROGRAM_NAME, descr);

    var root = app.rootCommand();
    // Do not set help_on_empty_args: empty argv means stdin, not help.
    try root.addArg(valueOption(
        opt_query,
        'q',
        "query text from the command line",
        "query",
    ));
    try root.addArg(valueOption(
        opt_file,
        'f',
        "query from a file",
        "file",
    ));
    try root.addArg(Arg.booleanOption(
        opt_syntax_check,
        'n',
        "parse and type-check query without executing",
    ));

    return app;
}

/// Short names of options that take a value.
const value_option_short = [_]u8{ 'q', 'f' };

/// Long names of options that take a value.
const value_option_long = [_][]const u8{ "query", "file" };

fn shouldAttach(opt_tok: []const u8, next_tok: []const u8) bool {
    // yazap skips empty argv elements; rewrite `-q ""` into `-q=` so an empty
    // query is captured (same approach as hc's normalizeArgv).
    return lib.isBareNamedOption(opt_tok, &value_option_short, &value_option_long) and next_tok.len == 0;
}

fn inputFromMatches(matches: ArgMatches) Input {
    // Prefer -q over -f when both are present.
    if (matches.getSingleValue(opt_query)) |q| return .{ .query = q };
    if (matches.getSingleValue(opt_file)) |f| return .{ .file = f };
    return .stdin;
}

/// Parses argv. Returns the query input source and syntax-check flag. Yazap
/// argv rejections become `error.InvalidOptions` (diagnostic already printed).
/// `-h/--help` never returns: yazap prints help and exits.
pub fn run(
    allocator: std.mem.Allocator,
    io: std.Io,
    argv: []const [:0]const u8,
) !RunResult {
    const app = try createApp(allocator);
    defer {
        app.deinit();
        allocator.destroy(app);
    }

    const argv_norm = try lib.normalizeArgv(allocator, argv, shouldAttach);

    const matches = blk: {
        const yazap_out = try YazapStdoutRedirect.begin();
        defer yazap_out.restore();
        break :blk app.parseFrom(io, argv_norm) catch |err| switch (err) {
            error.UnrecognizedCommand,
            error.SubcommandNotProvided,
            error.UnrecognizedOption,
            error.OptionValueNotProvided,
            error.UnexpectedOptionValue,
            error.EmptyOptionValue,
            error.InvalidOptionValue,
            error.TooFewOptionValue,
            error.TooManyOptionValue,
            error.PositionalArgumentNotProvided,
            => return error.InvalidOptions,
            else => return err,
        };
    };

    return .{
        .input = inputFromMatches(matches),
        .syntax_check = matches.containsArg(opt_syntax_check),
    };
}

test "query option selects query input" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const argv = [_][:0]const u8{ "-q", "from string s in \"a\" select s.md5;" };
    const result = try run(arena.allocator(), std.testing.io, &argv);
    try std.testing.expectEqualDeep(Input{ .query = "from string s in \"a\" select s.md5;" }, result.input);
    try std.testing.expect(!result.syntax_check);
}

test "file option selects file input" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const argv = [_][:0]const u8{ "-f", "query.l2h" };
    const result = try run(arena.allocator(), std.testing.io, &argv);
    try std.testing.expectEqualDeep(Input{ .file = "query.l2h" }, result.input);
    try std.testing.expect(!result.syntax_check);
}

test "long options work" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const argv = [_][:0]const u8{ "--query", "x;" };
    const result = try run(arena.allocator(), std.testing.io, &argv);
    try std.testing.expectEqualDeep(Input{ .query = "x;" }, result.input);
}

test "empty argv selects stdin" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const result = try run(arena.allocator(), std.testing.io, &.{});
    try std.testing.expectEqualDeep(Input.stdin, result.input);
    try std.testing.expect(!result.syntax_check);
}

test "query wins over file when both given" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const argv = [_][:0]const u8{ "-f", "a.l2h", "-q", "y;" };
    const result = try run(arena.allocator(), std.testing.io, &argv);
    try std.testing.expectEqualDeep(Input{ .query = "y;" }, result.input);
}

test "unknown option is rejected" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const argv = [_][:0]const u8{ "-z", "nope" };
    try std.testing.expectError(error.InvalidOptions, run(arena.allocator(), std.testing.io, &argv));
}

test "empty query value is accepted" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const argv = [_][:0]const u8{ "-q", "" };
    const result = try run(arena.allocator(), std.testing.io, &argv);
    try std.testing.expectEqualDeep(Input{ .query = "" }, result.input);
}

test "short syntax-check flag" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const argv = [_][:0]const u8{ "-n", "-q", "from string s in \"a\" select s;" };
    const result = try run(arena.allocator(), std.testing.io, &argv);
    try std.testing.expect(result.syntax_check);
    try std.testing.expectEqualDeep(Input{ .query = "from string s in \"a\" select s;" }, result.input);
}

test "long syntax-check flag" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const argv = [_][:0]const u8{ "--syntax-check", "-f", "q.l2h" };
    const result = try run(arena.allocator(), std.testing.io, &argv);
    try std.testing.expect(result.syntax_check);
    try std.testing.expectEqualDeep(Input{ .file = "q.l2h" }, result.input);
}
