name: CI

env:
  Major: 5
  Minor: 1
  Build: 0
  Revision: ${{ github.run_number }}
  GITHUB_REF: "${{ github.ref }}"
  NSIS_ROOT: "C:/Program Files (x86)/NSIS"
  WINDDK: "C:/Program Files (x86)/Windows Kits/8.1"
  VS160COMNTOOLS: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools/"
  RELEASE_DIR: artifacts
  WINDOWS_TARGET: x86_64-pc-windows-msvc
  RELEASE_BIN: hc
  PROJECT_NAME: hc

on:
  push:
    branches: [ master ]
    tags:
      - "v*" # Run when tag matches v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, windows, x64]

    steps:
      - uses: actions/checkout@v2

      - name: Copy External
        shell: cmd
        run: xcopy d:\code\linq2hash\External External /S /Y
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 16.11
          
      - run: nuget restore src\linq2hash.sln
      - name: Build
        working-directory: src
        env:
          PROJECT_BASE_PATH: "${{runner.workspace}}\\${{ env.PROJECT_NAME }}\\src"
          BINPLACE_PLACEFILE: "${{runner.workspace}}\\${{ env.PROJECT_NAME }}\\binplace.txt"
          HC_TEST_DIR: "${{runner.workspace}}\\${{ env.PROJECT_NAME }}\\_tst.net"
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: |
          echo "$RUNNER_CONTEXT"
          msbuild hc.xml

      - name: Create artifact directory
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir ${{ env.RELEASE_DIR }}

      - name: Packaging
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          PROJECT_BASE_PATH: "${{runner.workspace}}\\${{ env.PROJECT_NAME }}\\src"
        run: |
          xcopy ${{ env.PROJECT_BASE_PATH }}\x64\Release\ru ${{ env.PROJECT_BASE_PATH }}\Binplace-x64\ru /S /Y
          tar -cvzf .\${{ env.RELEASE_DIR }}\${{ env.RELEASE_BIN }}-${{ env.Major }}.${{ env.Minor }}.${{ env.Build }}-${{ env.WINDOWS_TARGET }}.tar.gz -C ${{ env.PROJECT_BASE_PATH }}\Binplace-x64\Release ${{ env.RELEASE_BIN }}.exe

      - uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: windows
          path: .\${{ env.RELEASE_DIR }}
