name: CI

env:
  GITHUB_REF: "${{ github.ref }}"
  NSIS_ROOT: "C:/Program Files (x86)/NSIS"
  WINDDK: "C:/Program Files (x86)/Windows Kits/8.1"
  VS160COMNTOOLS: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools/"

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, windows, x64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Copy External
        shell: cmd
        run: xcopy d:\code\linq2hash\External External /S /Y

      - name: PROJECT_BASE_PATH
        shell: cmd
        run: set PROJECT_BASE_PATH=${{runner.temp}}\src

      - name: BINPLACE_PLACEFILE
        shell: cmd
        run: set BINPLACE_PLACEFILE=${{runner.temp}}\binplace.txt

      - name: HC_TEST_DIR
        shell: cmd
        run: set HC_TEST_DIR=${{runner.temp}}\_tst.net
        
      - name: vcvars64
        shell: cmd
        run: 'c:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat'
          
      - run: nuget restore src\linq2hash.sln
      - name: Build
        working-directory: src
        run: msbuild hc.xml